.TH "__iar_u32" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__iar_u32
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB228\fP of file \fBcmsis_iccarm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t v"

.PP
Definition at line \fB228\fP of file \fBcmsis_iccarm\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
