.TH "_ADC_Channel_Sample_Time_" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ADC_Channel_Sample_Time_ \- This struct provides an easy way for the user to set the sample time of a channel\&. All the options when selected will have an additional 12 cycles added to them in the hardware\&. So \fI3_Cycles is selected by the user, then total cycles taken to complete one conversion of that channel will be 3+12 = 15 cycles\&. Is used in _ADC_Channel\fP struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ADC_Defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fB_3_Cycles\fP"
.br
.ti -1c
.RI "uint8_t \fB_15_Cycles\fP"
.br
.ti -1c
.RI "uint8_t \fB_28_Cycles\fP"
.br
.ti -1c
.RI "uint8_t \fB_56_Cycles\fP"
.br
.ti -1c
.RI "uint8_t \fB_84_Cycles\fP"
.br
.ti -1c
.RI "uint8_t \fB_112_Cycles\fP"
.br
.ti -1c
.RI "uint8_t \fB_144_Cycles\fP"
.br
.ti -1c
.RI "uint8_t \fB_480_Cycles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This struct provides an easy way for the user to set the sample time of a channel\&. All the options when selected will have an additional 12 cycles added to them in the hardware\&. So \fI3_Cycles is selected by the user, then total cycles taken to complete one conversion of that channel will be 3+12 = 15 cycles\&. Is used in _ADC_Channel\fP struct\&. 


.PP
\fBSee also\fP
.RS 4
\fIADC_Channel\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fI_3_Cycles\fP 
.br
\fI_15_Cycles\fP 
.br
\fI_28_Cycles\fP 
.br
\fI_56_Cycles\fP 
.br
\fI_84_Cycles\fP 
.br
\fI_112_Cycles\fP 
.br
\fI_144_Cycles\fP 
.br
\fI_480_Cycles\fP 
.RE
.PP

.PP
Definition at line \fB104\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t _112_Cycles"

.PP
Definition at line \fB110\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t _144_Cycles"

.PP
Definition at line \fB111\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t _15_Cycles"

.PP
Definition at line \fB106\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t _28_Cycles"

.PP
Definition at line \fB107\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t _3_Cycles"

.PP
Definition at line \fB105\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t _480_Cycles"

.PP
Definition at line \fB112\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t _56_Cycles"

.PP
Definition at line \fB108\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t _84_Cycles"

.PP
Definition at line \fB109\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
