.TH "_ADC_Channel_" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ADC_Channel_ \- This sturct is used in ADC_Configuration struct\&. Encapsulates all the necessary configurations needed for any ADC channel\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ADC_Defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB_ADC_Channel_Enable_Disable_\fP \fBEnable\fP"
.br
.ti -1c
.RI "\fB_ADC_Channel_Sequence_Number_\fP \fBSequence_Number\fP"
.br
.ti -1c
.RI "\fB_ADC_Channel_Sample_Time_\fP \fBSample_Time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This sturct is used in ADC_Configuration struct\&. Encapsulates all the necessary configurations needed for any ADC channel\&. 


.PP
\fBParameters\fP
.RS 4
\fIEnable\fP 
.br
\fISequence_Number\fP 
.br
\fISample_Time\fP 
.RE
.PP
\fBSee also\fP
.RS 4
\fIADC_Channel_Enable_Disable\fP 

.PP
\fIADC_Channel_Sequence_Number\fP 

.PP
\fIADC_Channel_Sample_Time\fP 
.RE
.PP

.PP
Definition at line \fB130\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB_ADC_Channel_Enable_Disable_\fP Enable"

.PP
Definition at line \fB132\fP of file \fBADC_Defs\&.h\fP\&.
.SS "\fB_ADC_Channel_Sample_Time_\fP Sample_Time"

.PP
Definition at line \fB134\fP of file \fBADC_Defs\&.h\fP\&.
.SS "\fB_ADC_Channel_Sequence_Number_\fP Sequence_Number"

.PP
Definition at line \fB133\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
