.TH "_ADC_Channel_Sequence_Number_" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ADC_Channel_Sequence_Number_ \- This sturct is used in \fIADC_Channel\fP struct\&. Used to enable or disable a particular Channel of the ADC\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ADC_Defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBSequence_1\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_2\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_3\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_4\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_5\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_6\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_7\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_8\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_9\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_10\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_11\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_12\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_13\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_14\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_15\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_16\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This sturct is used in \fIADC_Channel\fP struct\&. Used to enable or disable a particular Channel of the ADC\&. 


.PP
\fBSee also\fP
.RS 4
\fIADC_Channel\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fISequence_1;\fP 
.br
\fISequence_2;\fP 
.br
\fISequence_3;\fP 
.br
\fISequence_4;\fP 
.br
\fISequence_5;\fP 
.br
\fISequence_6;\fP 
.br
\fISequence_7;\fP 
.br
\fISequence_8;\fP 
.br
\fISequence_9;\fP 
.br
\fISequence_10;\fP 
.br
\fISequence_11;\fP 
.br
\fISequence_12;\fP 
.br
\fISequence_13;\fP 
.br
\fISequence_14;\fP 
.br
\fISequence_15;\fP 
.br
\fISequence_16;\fP 
.RE
.PP

.PP
Definition at line \fB61\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t Sequence_1"

.PP
Definition at line \fB63\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_10"

.PP
Definition at line \fB72\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_11"

.PP
Definition at line \fB73\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_12"

.PP
Definition at line \fB74\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_13"

.PP
Definition at line \fB75\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_14"

.PP
Definition at line \fB76\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_15"

.PP
Definition at line \fB77\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_16"

.PP
Definition at line \fB78\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_2"

.PP
Definition at line \fB64\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_3"

.PP
Definition at line \fB65\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_4"

.PP
Definition at line \fB66\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_5"

.PP
Definition at line \fB67\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_6"

.PP
Definition at line \fB68\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_7"

.PP
Definition at line \fB69\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_8"

.PP
Definition at line \fB70\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Sequence_9"

.PP
Definition at line \fB71\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
