.TH "_ADC_Channel_Enable_Disable_" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ADC_Channel_Enable_Disable_ \- This sturct is used in \fIADC_Channel\fP struct\&. Used to enable or disable a particular Channel of the ADC\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ADC_Defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBEnable\fP"
.br
.ti -1c
.RI "bool \fBDisable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This sturct is used in \fIADC_Channel\fP struct\&. Used to enable or disable a particular Channel of the ADC\&. 


.PP
\fBSee also\fP
.RS 4
\fIADC_Channel\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fIEnable\fP 
.br
\fIDisable\fP 
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool Disable"

.PP
Definition at line \fB32\fP of file \fBADC_Defs\&.h\fP\&.
.SS "bool Enable"

.PP
Definition at line \fB31\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
