.TH "_USART_DMA_Enable_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USART_DMA_Enable_Type
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBTX_Enable\fP"
.br
.ti -1c
.RI "uint8_t \fBTX_Disable\fP"
.br
.ti -1c
.RI "uint8_t \fBRX_Enable\fP"
.br
.ti -1c
.RI "uint8_t \fBRX_Disable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB41\fP of file \fBUSART_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t RX_Disable"

.PP
Definition at line \fB45\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t RX_Enable"

.PP
Definition at line \fB44\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t TX_Disable"

.PP
Definition at line \fB43\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t TX_Enable"

.PP
Definition at line \fB42\fP of file \fBUSART_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
