.TH "_USART_Hardware_Flow_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USART_Hardware_Flow_Type
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBDisable\fP"
.br
.ti -1c
.RI "uint8_t \fBCTS_Enable\fP"
.br
.ti -1c
.RI "uint8_t \fBRTS_Enable\fP"
.br
.ti -1c
.RI "uint8_t \fBCTS_RTS_Enable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBUSART_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t CTS_Enable"

.PP
Definition at line \fB50\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t CTS_RTS_Enable"

.PP
Definition at line \fB52\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t Disable"

.PP
Definition at line \fB49\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t RTS_Enable"

.PP
Definition at line \fB51\fP of file \fBUSART_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
