.TH "_USART_Interrupt_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USART_Interrupt_Type
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBDisable\fP"
.br
.ti -1c
.RI "int \fBParity_Enable\fP"
.br
.ti -1c
.RI "int \fBTransmit_Empty_Enable\fP"
.br
.ti -1c
.RI "int \fBTransmission_Complete_Enable\fP"
.br
.ti -1c
.RI "int \fBReceiver_Empty_Enable\fP"
.br
.ti -1c
.RI "int \fBIDLE_Enable\fP"
.br
.ti -1c
.RI "int \fBCTS_Enable\fP"
.br
.ti -1c
.RI "int \fBError_Enable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBUSART_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int CTS_Enable"

.PP
Definition at line \fB37\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "int Disable"

.PP
Definition at line \fB31\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "int Error_Enable"

.PP
Definition at line \fB38\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "int IDLE_Enable"

.PP
Definition at line \fB36\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "int Parity_Enable"

.PP
Definition at line \fB32\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "int Receiver_Empty_Enable"

.PP
Definition at line \fB35\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "int Transmission_Complete_Enable"

.PP
Definition at line \fB34\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "int Transmit_Empty_Enable"

.PP
Definition at line \fB33\fP of file \fBUSART_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
