.TH "_USART_Mode_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USART_Mode_Type
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBDisable\fP"
.br
.ti -1c
.RI "uint8_t \fBAsynchronous\fP"
.br
.ti -1c
.RI "uint8_t \fBSynchronous\fP"
.br
.ti -1c
.RI "uint8_t \fBSingle_Wire_Half_Duplex\fP"
.br
.ti -1c
.RI "uint8_t \fBIrDA\fP"
.br
.ti -1c
.RI "uint8_t \fBLIN\fP"
.br
.ti -1c
.RI "uint8_t \fBSmartCard\fP"
.br
.ti -1c
.RI "uint8_t \fBSmartCard_Clock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBUSART_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t Asynchronous"

.PP
Definition at line \fB16\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t Disable"

.PP
Definition at line \fB15\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t IrDA"

.PP
Definition at line \fB19\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t LIN"

.PP
Definition at line \fB20\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t Single_Wire_Half_Duplex"

.PP
Definition at line \fB18\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t SmartCard"

.PP
Definition at line \fB21\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t SmartCard_Clock"

.PP
Definition at line \fB22\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint8_t Synchronous"

.PP
Definition at line \fB17\fP of file \fBUSART_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
