.TH "_USART_Parity_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_USART_Parity_Type
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBEnable\fP"
.br
.ti -1c
.RI "uint16_t \fBDisable\fP"
.br
.ti -1c
.RI "uint16_t \fBEven\fP"
.br
.ti -1c
.RI "uint16_t \fBOdd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB62\fP of file \fBUSART_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t Disable"

.PP
Definition at line \fB64\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint16_t Enable"

.PP
Definition at line \fB63\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint16_t Even"

.PP
Definition at line \fB65\fP of file \fBUSART_Defs\&.h\fP\&.
.SS "uint16_t Odd"

.PP
Definition at line \fB66\fP of file \fBUSART_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
