.TH "ADC_Configuration::Port" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Configuration::Port
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBADC_TypeDef\fP * \fB_ADC1_\fP"
.br
.ti -1c
.RI "\fBADC_TypeDef\fP * \fB_ADC2_\fP"
.br
.ti -1c
.RI "\fBADC_TypeDef\fP * \fB_ADC3_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB164\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBADC_TypeDef\fP* _ADC1_"

.PP
Definition at line \fB165\fP of file \fBADC_Defs\&.h\fP\&.
.SS "\fBADC_TypeDef\fP* _ADC2_"

.PP
Definition at line \fB166\fP of file \fBADC_Defs\&.h\fP\&.
.SS "\fBADC_TypeDef\fP* _ADC3_"

.PP
Definition at line \fB167\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
