.TH "ADC_Mode" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Mode \- This struct helps select the mode in which the conversions will happen\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ADC_Defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBSingle\fP"
.br
.ti -1c
.RI "uint8_t \fBContinuous\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This struct helps select the mode in which the conversions will happen\&. 


.PP
\fBAttention\fP
.RS 4
When an external trigger is used i\&.e\&. Regular_External_Trigger_Enable or Injected_External_Trigger_Enable is configured to be Enable, make sure to select 'Single' instead of Continuous\&.
.RE
.PP
.PP
.nf
.fi
.PP

.PP
\fBSee also\fP
.RS 4
ADC_Configuration 
.RE
.PP

.PP
Definition at line \fB150\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t Continuous"

.PP
Definition at line \fB153\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Single"

.PP
Definition at line \fB152\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
