.TH "ADC_Configuration::Resolution" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Configuration::Resolution
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBBit_12\fP"
.br
.ti -1c
.RI "uint8_t \fBBit_10\fP"
.br
.ti -1c
.RI "uint8_t \fBBit_8\fP"
.br
.ti -1c
.RI "uint8_t \fBBit_6\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB184\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t Bit_10"

.PP
Definition at line \fB186\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Bit_12"

.PP
Definition at line \fB185\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Bit_6"

.PP
Definition at line \fB188\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Bit_8"

.PP
Definition at line \fB187\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
