.TH "ADC_Config::Watchdog_Analog" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Config::Watchdog_Analog
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBEnable\fP"
.br
.ti -1c
.RI "uint8_t \fBChannel_Type\fP"
.br
.ti -1c
.RI "bool \fBChannel_Scan\fP"
.br
.ti -1c
.RI "uint8_t \fBChannel\fP"
.br
.ti -1c
.RI "uint16_t \fBHigher_Threshold\fP"
.br
.ti -1c
.RI "uint16_t \fBLower_Threshold\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB59\fP of file \fBADC\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t Channel"

.PP
Definition at line \fB64\fP of file \fBADC\&.h\fP\&.
.SS "bool Channel_Scan"

.PP
Definition at line \fB63\fP of file \fBADC\&.h\fP\&.
.SS "uint8_t Channel_Type"

.PP
Definition at line \fB62\fP of file \fBADC\&.h\fP\&.
.SS "bool Enable"

.PP
Definition at line \fB61\fP of file \fBADC\&.h\fP\&.
.SS "uint16_t Higher_Threshold"

.PP
Definition at line \fB65\fP of file \fBADC\&.h\fP\&.
.SS "uint16_t Lower_Threshold"

.PP
Definition at line \fB66\fP of file \fBADC\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
