.TH "ADC_Configuration::Regular_External_Trigger_Event" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Configuration::Regular_External_Trigger_Event
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBTimer_1_CC1\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_1_CC2\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_1_CC3\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_2_CC2\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_2_CC3\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_2_CC4\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_2_TRGO\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_3_CC1\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_3_TRGO\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_4_CC4\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_5_CC1\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_5_CC2\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_5_CC3\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_8_CC1\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_8_TRGO\fP"
.br
.ti -1c
.RI "uint8_t \fBEXTI_11\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB199\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t EXTI_11"

.PP
Definition at line \fB215\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_1_CC1"

.PP
Definition at line \fB200\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_1_CC2"

.PP
Definition at line \fB201\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_1_CC3"

.PP
Definition at line \fB202\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_2_CC2"

.PP
Definition at line \fB203\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_2_CC3"

.PP
Definition at line \fB204\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_2_CC4"

.PP
Definition at line \fB205\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_2_TRGO"

.PP
Definition at line \fB206\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_3_CC1"

.PP
Definition at line \fB207\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_3_TRGO"

.PP
Definition at line \fB208\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_4_CC4"

.PP
Definition at line \fB209\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_5_CC1"

.PP
Definition at line \fB210\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_5_CC2"

.PP
Definition at line \fB211\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_5_CC3"

.PP
Definition at line \fB212\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_8_CC1"

.PP
Definition at line \fB213\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_8_TRGO"

.PP
Definition at line \fB214\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
