.TH "ADC_Channel_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Channel_Type
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBRegular\fP"
.br
.ti -1c
.RI "uint8_t \fBInjected\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB157\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t Injected"

.PP
Definition at line \fB159\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Regular"

.PP
Definition at line \fB158\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
