.TH "ADC_Common_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Common_TypeDef
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCDR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB202\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t CCR"
ADC common control register, Address offset: ADC1 base address + 0x304 
.PP
Definition at line \fB205\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CDR"
ADC common regular data register for dual AND triple modes, Address offset: ADC1 base address + 0x308 
.PP
Definition at line \fB206\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CSR"
ADC Common status register, Address offset: ADC1 base address + 0x300 
.PP
Definition at line \fB204\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
