.TH "ADC_Configuration::_Watchdog_Analog_" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Configuration::_Watchdog_Analog_
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBChannel_Scan\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBADC_Channel_Type\fP \fBChannel_Type\fP"
.br
.ti -1c
.RI "bool \fBEnable\fP"
.br
.ti -1c
.RI "bool \fBDisable\fP"
.br
.ti -1c
.RI "struct ADC_Configuration::_Watchdog_Analog_::Channel_Scan \fBChannel_Scan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB239\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBADC_Channel_Type\fP Channel_Type"

.PP
Definition at line \fB241\fP of file \fBADC_Defs\&.h\fP\&.
.SS "bool Disable"

.PP
Definition at line \fB244\fP of file \fBADC_Defs\&.h\fP\&.
.SS "bool Enable"

.PP
Definition at line \fB243\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
