.TH "ADC_Configuration::_Watchdog_Analog_::Channel_Scan" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Configuration::_Watchdog_Analog_::Channel_Scan
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBAll_Channels\fP"
.br
.ti -1c
.RI "bool \fBSingle_Channel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB246\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool All_Channels"

.PP
Definition at line \fB248\fP of file \fBADC_Defs\&.h\fP\&.
.SS "bool Single_Channel"

.PP
Definition at line \fB249\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
