.TH "ADC_Configuration::Regular_External_Trigger_Enable" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Configuration::Regular_External_Trigger_Enable
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBTrigger_Disable\fP"
.br
.ti -1c
.RI "uint8_t \fBTrigger_On_Rising_Edge\fP"
.br
.ti -1c
.RI "uint8_t \fBTrigger_On_Falling_Edge\fP"
.br
.ti -1c
.RI "uint8_t \fBTrigger_On_Both_Edges\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB191\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t Trigger_Disable"

.PP
Definition at line \fB192\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Trigger_On_Both_Edges"

.PP
Definition at line \fB195\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Trigger_On_Falling_Edge"

.PP
Definition at line \fB194\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Trigger_On_Rising_Edge"

.PP
Definition at line \fB193\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
