.TH "ADC_Configuration::Injected_External_Trigger_Event" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Configuration::Injected_External_Trigger_Event
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBTimer_1_CC4\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_1_TRGO\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_2_CC1\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_2_TRGO\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_3_CC2\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_3_CC4\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_4_CC1\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_4_CC2\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_4_CC3\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_4_TRGO\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_5_CC4\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_5_TRGO\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_8_CC2\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_8_CC3\fP"
.br
.ti -1c
.RI "uint8_t \fBTimer_8_CC4\fP"
.br
.ti -1c
.RI "uint8_t \fBEXTI_15\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB218\fP of file \fBADC_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t EXTI_15"

.PP
Definition at line \fB234\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_1_CC4"

.PP
Definition at line \fB219\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_1_TRGO"

.PP
Definition at line \fB220\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_2_CC1"

.PP
Definition at line \fB221\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_2_TRGO"

.PP
Definition at line \fB222\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_3_CC2"

.PP
Definition at line \fB223\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_3_CC4"

.PP
Definition at line \fB224\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_4_CC1"

.PP
Definition at line \fB225\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_4_CC2"

.PP
Definition at line \fB226\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_4_CC3"

.PP
Definition at line \fB227\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_4_TRGO"

.PP
Definition at line \fB228\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_5_CC4"

.PP
Definition at line \fB229\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_5_TRGO"

.PP
Definition at line \fB230\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_8_CC2"

.PP
Definition at line \fB231\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_8_CC3"

.PP
Definition at line \fB232\fP of file \fBADC_Defs\&.h\fP\&.
.SS "uint8_t Timer_8_CC4"

.PP
Definition at line \fB233\fP of file \fBADC_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
