.TH "ADC_Config" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Config
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBExternal_Trigger\fP"
.br
.ti -1c
.RI "struct \fBWatchdog_Analog\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBADC_TypeDef\fP * \fBPort\fP"
.br
.ti -1c
.RI "uint8_t \fBData_Alignment\fP"
.br
.ti -1c
.RI "uint8_t \fBConversion_Mode\fP"
.br
.ti -1c
.RI "uint8_t \fBChannel_Type\fP"
.br
.ti -1c
.RI "struct ADC_Config::External_Trigger \fBExternal_Trigger\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_0\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_1\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_2\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_3\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_4\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_5\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_6\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_7\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_8\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_9\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_10\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_11\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_12\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_13\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_14\fP"
.br
.ti -1c
.RI "\fBADC_Pin\fP \fBChannel_15\fP"
.br
.ti -1c
.RI "uint8_t \fBResolution\fP"
.br
.ti -1c
.RI "struct ADC_Config::Watchdog_Analog \fBWatchdog_Analog\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBADC\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBADC_Pin\fP Channel_0"

.PP
Definition at line \fB40\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_1"

.PP
Definition at line \fB41\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_10"

.PP
Definition at line \fB50\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_11"

.PP
Definition at line \fB51\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_12"

.PP
Definition at line \fB52\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_13"

.PP
Definition at line \fB53\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_14"

.PP
Definition at line \fB54\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_15"

.PP
Definition at line \fB55\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_2"

.PP
Definition at line \fB42\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_3"

.PP
Definition at line \fB43\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_4"

.PP
Definition at line \fB44\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_5"

.PP
Definition at line \fB45\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_6"

.PP
Definition at line \fB46\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_7"

.PP
Definition at line \fB47\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_8"

.PP
Definition at line \fB48\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_Pin\fP Channel_9"

.PP
Definition at line \fB49\fP of file \fBADC\&.h\fP\&.
.SS "uint8_t Channel_Type"

.PP
Definition at line \fB31\fP of file \fBADC\&.h\fP\&.
.SS "uint8_t Conversion_Mode"

.PP
Definition at line \fB29\fP of file \fBADC\&.h\fP\&.
.SS "uint8_t Data_Alignment"

.PP
Definition at line \fB27\fP of file \fBADC\&.h\fP\&.
.SS "\fBADC_TypeDef\fP* Port"

.PP
Definition at line \fB25\fP of file \fBADC\&.h\fP\&.
.SS "uint8_t Resolution"

.PP
Definition at line \fB57\fP of file \fBADC\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
