.TH "ADC/ADC_Defs.h" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC/ADC_Defs.h
.SH SYNOPSIS
.br
.PP
\fR#include 'main\&.h'\fP
.br
\fR#include 'ADC\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_ADC_Channel_Enable_Disable_\fP"
.br
.RI "This sturct is used in \fIADC_Channel\fP struct\&. Used to enable or disable a particular Channel of the ADC\&. "
.ti -1c
.RI "struct \fB_ADC_Channel_Sequence_Number_\fP"
.br
.RI "This sturct is used in \fIADC_Channel\fP struct\&. Used to enable or disable a particular Channel of the ADC\&. "
.ti -1c
.RI "struct \fB_ADC_Channel_Sample_Time_\fP"
.br
.RI "This struct provides an easy way for the user to set the sample time of a channel\&. All the options when selected will have an additional 12 cycles added to them in the hardware\&. So \fI3_Cycles is selected by the user, then total cycles taken to complete one conversion of that channel will be 3+12 = 15 cycles\&. Is used in _ADC_Channel\fP struct\&. "
.ti -1c
.RI "struct \fB_ADC_Channel_\fP"
.br
.RI "This sturct is used in ADC_Configuration struct\&. Encapsulates all the necessary configurations needed for any ADC channel\&. "
.ti -1c
.RI "struct \fBADC_Mode\fP"
.br
.RI "This struct helps select the mode in which the conversions will happen\&. "
.ti -1c
.RI "struct \fBADC_Channel_Type\fP"
.br
.ti -1c
.RI "struct \fBADC_Configuration\fP"
.br
.ti -1c
.RI "struct \fBADC_Configuration::Port\fP"
.br
.ti -1c
.RI "struct \fBADC_Configuration::Data_Alignment\fP"
.br
.ti -1c
.RI "struct \fBADC_Configuration::Resolution\fP"
.br
.ti -1c
.RI "struct \fBADC_Configuration::Regular_External_Trigger_Enable\fP"
.br
.ti -1c
.RI "struct \fBADC_Configuration::Regular_External_Trigger_Event\fP"
.br
.ti -1c
.RI "struct \fBADC_Configuration::Injected_External_Trigger_Event\fP"
.br
.ti -1c
.RI "struct \fBADC_Configuration::_Watchdog_Analog_\fP"
.br
.ti -1c
.RI "struct \fBADC_Configuration::_Watchdog_Analog_::Channel_Scan\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct _ADC_Channel_Enable_Disable_ \fB_ADC_Channel_Enable_Disable_\fP"
.br
.RI "This sturct is used in \fIADC_Channel\fP struct\&. Used to enable or disable a particular Channel of the ADC\&. "
.ti -1c
.RI "typedef struct _ADC_Channel_Sequence_Number_ \fB_ADC_Channel_Sequence_Number_\fP"
.br
.RI "This sturct is used in \fIADC_Channel\fP struct\&. Used to enable or disable a particular Channel of the ADC\&. "
.ti -1c
.RI "typedef struct _ADC_Channel_Sample_Time_ \fB_ADC_Channel_Sample_Time_\fP"
.br
.RI "This struct provides an easy way for the user to set the sample time of a channel\&. All the options when selected will have an additional 12 cycles added to them in the hardware\&. So \fI3_Cycles is selected by the user, then total cycles taken to complete one conversion of that channel will be 3+12 = 15 cycles\&. Is used in _ADC_Channel\fP struct\&. "
.ti -1c
.RI "typedef struct _ADC_Channel_ \fB_ADC_Channel_\fP"
.br
.RI "This sturct is used in ADC_Configuration struct\&. Encapsulates all the necessary configurations needed for any ADC channel\&. "
.ti -1c
.RI "typedef struct ADC_Mode \fBADC_Mode\fP"
.br
.RI "This struct helps select the mode in which the conversions will happen\&. "
.ti -1c
.RI "typedef struct ADC_Channel_Type \fBADC_Channel_Type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Kunal Salvi (kunalsalviusu@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2024-08-20
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.PP
Definition in file \fBADC_Defs\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct _ADC_Channel_ _ADC_Channel_"

.PP
This sturct is used in ADC_Configuration struct\&. Encapsulates all the necessary configurations needed for any ADC channel\&. 
.PP
\fBParameters\fP
.RS 4
\fIEnable\fP 
.br
\fISequence_Number\fP 
.br
\fISample_Time\fP 
.RE
.PP
\fBSee also\fP
.RS 4
\fIADC_Channel_Enable_Disable\fP 

.PP
\fIADC_Channel_Sequence_Number\fP 

.PP
\fIADC_Channel_Sample_Time\fP 
.RE
.PP

.SS "typedef struct _ADC_Channel_Enable_Disable_ _ADC_Channel_Enable_Disable_"

.PP
This sturct is used in \fIADC_Channel\fP struct\&. Used to enable or disable a particular Channel of the ADC\&. 
.PP
\fBSee also\fP
.RS 4
\fIADC_Channel\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fIEnable\fP 
.br
\fIDisable\fP 
.RE
.PP

.SS "typedef struct _ADC_Channel_Sample_Time_ _ADC_Channel_Sample_Time_"

.PP
This struct provides an easy way for the user to set the sample time of a channel\&. All the options when selected will have an additional 12 cycles added to them in the hardware\&. So \fI3_Cycles is selected by the user, then total cycles taken to complete one conversion of that channel will be 3+12 = 15 cycles\&. Is used in _ADC_Channel\fP struct\&. 
.PP
\fBSee also\fP
.RS 4
\fIADC_Channel\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fI_3_Cycles\fP 
.br
\fI_15_Cycles\fP 
.br
\fI_28_Cycles\fP 
.br
\fI_56_Cycles\fP 
.br
\fI_84_Cycles\fP 
.br
\fI_112_Cycles\fP 
.br
\fI_144_Cycles\fP 
.br
\fI_480_Cycles\fP 
.RE
.PP

.SS "typedef struct _ADC_Channel_Sequence_Number_ _ADC_Channel_Sequence_Number_"

.PP
This sturct is used in \fIADC_Channel\fP struct\&. Used to enable or disable a particular Channel of the ADC\&. 
.PP
\fBSee also\fP
.RS 4
\fIADC_Channel\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fISequence_1;\fP 
.br
\fISequence_2;\fP 
.br
\fISequence_3;\fP 
.br
\fISequence_4;\fP 
.br
\fISequence_5;\fP 
.br
\fISequence_6;\fP 
.br
\fISequence_7;\fP 
.br
\fISequence_8;\fP 
.br
\fISequence_9;\fP 
.br
\fISequence_10;\fP 
.br
\fISequence_11;\fP 
.br
\fISequence_12;\fP 
.br
\fISequence_13;\fP 
.br
\fISequence_14;\fP 
.br
\fISequence_15;\fP 
.br
\fISequence_16;\fP 
.RE
.PP

.SS "typedef struct ADC_Mode ADC_Mode"

.PP
This struct helps select the mode in which the conversions will happen\&. 
.PP
\fBAttention\fP
.RS 4
When an external trigger is used i\&.e\&. Regular_External_Trigger_Enable or Injected_External_Trigger_Enable is configured to be Enable, make sure to select 'Single' instead of Continuous\&.
.RE
.PP
.PP
.nf
.fi
.PP

.PP
\fBSee also\fP
.RS 4
ADC_Configuration 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
