.TH "ADC_Pin" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Pin
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBEnable\fP"
.br
.ti -1c
.RI "uint8_t \fBSequence_Number\fP"
.br
.ti -1c
.RI "uint8_t \fBSample_Time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBADC\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool Enable"

.PP
Definition at line \fB18\fP of file \fBADC\&.h\fP\&.
.SS "uint8_t Sample_Time"

.PP
Definition at line \fB20\fP of file \fBADC\&.h\fP\&.
.SS "uint8_t Sequence_Number"

.PP
Definition at line \fB19\fP of file \fBADC\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
