.TH "APSR_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
APSR_Type \- Union type to access the Application Program Status Register (APSR)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_armv81mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:27"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:28"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:27"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:16"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union type to access the Application Program Status Register (APSR)\&. 
.PP
Definition at line \fB328\fP of file \fBcore_armv81mml\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
