.TH "ARM_MPU_Region_t" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARM_MPU_Region_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mpu_armv7\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBRBAR\fP"
.br
.RI "The region base address register value (RBAR) "
.ti -1c
.RI "uint32_t \fBRASR\fP"
.br
.RI "The region attribute and size register value (RASR) \fBMPU_RASR\fP\&. "
.ti -1c
.RI "uint32_t \fBRLAR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for a single MPU Region 
.PP
Definition at line \fB183\fP of file \fBmpu_armv7\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t RASR"

.PP
The region attribute and size register value (RASR) \fBMPU_RASR\fP\&. 
.PP
Definition at line \fB185\fP of file \fBmpu_armv7\&.h\fP\&.
.SS "uint32_t RBAR"

.PP
The region base address register value (RBAR) Region Base Address Register value 
.PP
Definition at line \fB184\fP of file \fBmpu_armv7\&.h\fP\&.
.SS "uint32_t RLAR"
Region Limit Address Register value 
.PP
Definition at line \fB124\fP of file \fBmpu_armv8\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
