.TH "CAN_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_TypeDef \- Controller Area Network\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRF0R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRF1R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBESR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBTR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [88]"
.br
.ti -1c
.RI "\fBCAN_TxMailBox_TypeDef\fP \fBsTxMailBox\fP [3]"
.br
.ti -1c
.RI "\fBCAN_FIFOMailBox_TypeDef\fP \fBsFIFOMailBox\fP [2]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [12]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFMR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFM1R\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFS1R\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFFA1R\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFA1R\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [8]"
.br
.ti -1c
.RI "\fBCAN_FilterRegister_TypeDef\fP \fBsFilterRegister\fP [28]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Controller Area Network\&. 
.PP
Definition at line \fB249\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t BTR"
CAN bit timing register, Address offset: 0x1C 
.br
 
.PP
Definition at line \fB258\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t ESR"
CAN error status register, Address offset: 0x18 
.br
 
.PP
Definition at line \fB257\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t FA1R"
CAN filter activation register, Address offset: 0x21C 
.br
 
.PP
Definition at line \fB270\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t FFA1R"
CAN filter FIFO assignment register, Address offset: 0x214 
.br
 
.PP
Definition at line \fB268\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t FM1R"
CAN filter mode register, Address offset: 0x204 
.br
 
.PP
Definition at line \fB264\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t FMR"
CAN filter master register, Address offset: 0x200 
.br
 
.PP
Definition at line \fB263\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t FS1R"
CAN filter scale register, Address offset: 0x20C 
.br
 
.PP
Definition at line \fB266\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t IER"
CAN interrupt enable register, Address offset: 0x14 
.br
 
.PP
Definition at line \fB256\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MCR"
CAN master control register, Address offset: 0x00 
.br
 
.PP
Definition at line \fB251\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MSR"
CAN master status register, Address offset: 0x04 
.br
 
.PP
Definition at line \fB252\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED0[88]"
Reserved, 0x020 - 0x17F 
.br
 
.PP
Definition at line \fB259\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED1[12]"
Reserved, 0x1D0 - 0x1FF 
.br
 
.PP
Definition at line \fB262\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED2"
Reserved, 0x208 
.br
 
.PP
Definition at line \fB265\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED3"
Reserved, 0x210 
.br
 
.PP
Definition at line \fB267\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED4"
Reserved, 0x218 
.br
 
.PP
Definition at line \fB269\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED5[8]"
Reserved, 0x220-0x23F 
.br
 
.PP
Definition at line \fB271\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t RF0R"
CAN receive FIFO 0 register, Address offset: 0x0C 
.br
 
.PP
Definition at line \fB254\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t RF1R"
CAN receive FIFO 1 register, Address offset: 0x10 
.br
 
.PP
Definition at line \fB255\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fBCAN_FIFOMailBox_TypeDef\fP sFIFOMailBox[2]"
CAN FIFO MailBox, Address offset: 0x1B0 - 0x1CC 
.PP
Definition at line \fB261\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fBCAN_FilterRegister_TypeDef\fP sFilterRegister[28]"
CAN Filter Register, Address offset: 0x240-0x31C 
.br
 
.PP
Definition at line \fB272\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fBCAN_TxMailBox_TypeDef\fP sTxMailBox[3]"
CAN Tx MailBox, Address offset: 0x180 - 0x1AC 
.PP
Definition at line \fB260\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t TSR"
CAN transmit status register, Address offset: 0x08 
.br
 
.PP
Definition at line \fB253\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
