.TH "CAN_TxMailBox_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_TxMailBox_TypeDef \- Controller Area Network TxMailBox\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTIR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTDTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTDLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTDHR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Controller Area Network TxMailBox\&. 
.PP
Definition at line \fB215\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t TDHR"
CAN mailbox data high register 
.PP
Definition at line \fB220\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t TDLR"
CAN mailbox data low register 
.PP
Definition at line \fB219\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t TDTR"
CAN mailbox data length control and time stamp register 
.PP
Definition at line \fB218\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t TIR"
CAN TX mailbox identifier register 
.PP
Definition at line \fB217\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
