.TH "CMSIS_ICB" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_ICB \- Implementation Control Block register (ICB)
.PP
 \- Type definitions for the Implementation Control Block Register\&.  

.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "\fBSystem Tick Timer (SysTick)\fP"
.br
.RI "Type definitions for the System Timer Registers\&. "
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBICB_Type\fP"
.br
.RI "Structure type to access the Implementation Control Block (ICB)\&. "
.in -1c
.in +1c
.ti -1c
.RI "#define \fBICB_ACTLR_DISCRITAXIRUW_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISCRITAXIRUW_Msk\fP   (1UL << \fBICB_ACTLR_DISCRITAXIRUW_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISCRITAXIRUR_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISCRITAXIRUR_Msk\fP   (1UL << \fBICB_ACTLR_DISCRITAXIRUR_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_EVENTBUSEN_Pos\fP   14U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_EVENTBUSEN_Msk\fP   (1UL << \fBICB_ACTLR_EVENTBUSEN_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_EVENTBUSEN_S_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_EVENTBUSEN_S_Msk\fP   (1UL << \fBICB_ACTLR_EVENTBUSEN_S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISITMATBFLUSH_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISITMATBFLUSH_Msk\fP   (1UL << \fBICB_ACTLR_DISITMATBFLUSH_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISNWAMODE_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISNWAMODE_Msk\fP   (1UL << \fBICB_ACTLR_DISNWAMODE_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_FPEXCODIS_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_FPEXCODIS_Msk\fP   (1UL << \fBICB_ACTLR_FPEXCODIS_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBICB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBICB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISCRITAXIRUW_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISCRITAXIRUW_Msk\fP   (1UL << \fBICB_ACTLR_DISCRITAXIRUW_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISCRITAXIRUR_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISCRITAXIRUR_Msk\fP   (1UL << \fBICB_ACTLR_DISCRITAXIRUR_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_EVENTBUSEN_Pos\fP   14U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_EVENTBUSEN_Msk\fP   (1UL << \fBICB_ACTLR_EVENTBUSEN_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_EVENTBUSEN_S_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_EVENTBUSEN_S_Msk\fP   (1UL << \fBICB_ACTLR_EVENTBUSEN_S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISITMATBFLUSH_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISITMATBFLUSH_Msk\fP   (1UL << \fBICB_ACTLR_DISITMATBFLUSH_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISNWAMODE_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISNWAMODE_Msk\fP   (1UL << \fBICB_ACTLR_DISNWAMODE_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_FPEXCODIS_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_FPEXCODIS_Msk\fP   (1UL << \fBICB_ACTLR_FPEXCODIS_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBICB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBICB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBICB_ACTLR_DISDI_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISDI_Msk\fP   (3UL << \fBICB_ACTLR_DISDI_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISOLAP_Pos\fP   7U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISOLAP_Msk\fP   (1UL << \fBICB_ACTLR_DISOLAP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISOLAPS_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISOLAPS_Msk\fP   (1UL << \fBICB_ACTLR_DISOLAPS_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISLOBR_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISLOBR_Msk\fP   (1UL << \fBICB_ACTLR_DISLOBR_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISLO_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISLO_Msk\fP   (1UL << \fBICB_ACTLR_DISLO_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISLOLEP_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISLOLEP_Msk\fP   (1UL << \fBICB_ACTLR_DISLOLEP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISFOLD_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBICB_ACTLR_DISFOLD_Msk\fP   (1UL << \fBICB_ACTLR_DISFOLD_Pos\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the Implementation Control Block Register\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define ICB_ACTLR_DISCRITAXIRUR_Msk   (1UL << \fBICB_ACTLR_DISCRITAXIRUR_Pos\fP)"
ACTLR: DISCRITAXIRUR Mask 
.PP
Definition at line \fB1019\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISCRITAXIRUR_Msk   (1UL << \fBICB_ACTLR_DISCRITAXIRUR_Pos\fP)"
ACTLR: DISCRITAXIRUR Mask 
.PP
Definition at line \fB1033\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_DISCRITAXIRUR_Pos   15U"
ACTLR: DISCRITAXIRUR Position 
.PP
Definition at line \fB1018\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISCRITAXIRUR_Pos   15U"
ACTLR: DISCRITAXIRUR Position 
.PP
Definition at line \fB1032\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_DISCRITAXIRUW_Msk   (1UL << \fBICB_ACTLR_DISCRITAXIRUW_Pos\fP)"
ACTLR: DISCRITAXIRUW Mask 
.PP
Definition at line \fB1013\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISCRITAXIRUW_Msk   (1UL << \fBICB_ACTLR_DISCRITAXIRUW_Pos\fP)"
ACTLR: DISCRITAXIRUW Mask 
.PP
Definition at line \fB1030\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_DISCRITAXIRUW_Pos   27U"
ACTLR: DISCRITAXIRUW Position 
.PP
Definition at line \fB1012\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISCRITAXIRUW_Pos   27U"
ACTLR: DISCRITAXIRUW Position 
.PP
Definition at line \fB1029\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_DISDI_Msk   (3UL << \fBICB_ACTLR_DISDI_Pos\fP)"
ACTLR: DISDI Mask 
.PP
Definition at line \fB1016\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISDI_Pos   16U"
ACTLR: DISDI Position 
.PP
Definition at line \fB1015\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISFOLD_Msk   (1UL << \fBICB_ACTLR_DISFOLD_Pos\fP)"
ACTLR: DISFOLD Mask 
.PP
Definition at line \fB1052\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISFOLD_Pos   2U"
ACTLR: DISFOLD Position 
.PP
Definition at line \fB1051\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISITMATBFLUSH_Msk   (1UL << \fBICB_ACTLR_DISITMATBFLUSH_Pos\fP)"
ACTLR: DISITMATBFLUSH Mask 
.PP
Definition at line \fB1028\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISITMATBFLUSH_Msk   (1UL << \fBICB_ACTLR_DISITMATBFLUSH_Pos\fP)"
ACTLR: DISITMATBFLUSH Mask 
.PP
Definition at line \fB1042\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_DISITMATBFLUSH_Pos   12U"
ACTLR: DISITMATBFLUSH Position 
.PP
Definition at line \fB1027\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISITMATBFLUSH_Pos   12U"
ACTLR: DISITMATBFLUSH Position 
.PP
Definition at line \fB1041\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_DISLO_Msk   (1UL << \fBICB_ACTLR_DISLO_Pos\fP)"
ACTLR: DISLO Mask 
.PP
Definition at line \fB1046\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISLO_Pos   4U"
ACTLR: DISLO Position 
.PP
Definition at line \fB1045\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISLOBR_Msk   (1UL << \fBICB_ACTLR_DISLOBR_Pos\fP)"
ACTLR: DISLOBR Mask 
.PP
Definition at line \fB1043\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISLOBR_Pos   5U"
ACTLR: DISLOBR Position 
.PP
Definition at line \fB1042\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISLOLEP_Msk   (1UL << \fBICB_ACTLR_DISLOLEP_Pos\fP)"
ACTLR: DISLOLEP Mask 
.PP
Definition at line \fB1049\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISLOLEP_Pos   3U"
ACTLR: DISLOLEP Position 
.PP
Definition at line \fB1048\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISNWAMODE_Msk   (1UL << \fBICB_ACTLR_DISNWAMODE_Pos\fP)"
ACTLR: DISNWAMODE Mask 
.PP
Definition at line \fB1031\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISNWAMODE_Msk   (1UL << \fBICB_ACTLR_DISNWAMODE_Pos\fP)"
ACTLR: DISNWAMODE Mask 
.PP
Definition at line \fB1045\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_DISNWAMODE_Pos   11U"
ACTLR: DISNWAMODE Position 
.PP
Definition at line \fB1030\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISNWAMODE_Pos   11U"
ACTLR: DISNWAMODE Position 
.PP
Definition at line \fB1044\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_DISOLAP_Msk   (1UL << \fBICB_ACTLR_DISOLAP_Pos\fP)"
ACTLR: DISOLAP Mask 
.PP
Definition at line \fB1037\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISOLAP_Pos   7U"
ACTLR: DISOLAP Position 
.PP
Definition at line \fB1036\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISOLAPS_Msk   (1UL << \fBICB_ACTLR_DISOLAPS_Pos\fP)"
ACTLR: DISOLAPS Mask 
.PP
Definition at line \fB1040\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_DISOLAPS_Pos   6U"
ACTLR: DISOLAPS Position 
.PP
Definition at line \fB1039\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_EVENTBUSEN_Msk   (1UL << \fBICB_ACTLR_EVENTBUSEN_Pos\fP)"
ACTLR: EVENTBUSEN Mask 
.PP
Definition at line \fB1022\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_EVENTBUSEN_Msk   (1UL << \fBICB_ACTLR_EVENTBUSEN_Pos\fP)"
ACTLR: EVENTBUSEN Mask 
.PP
Definition at line \fB1036\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_EVENTBUSEN_Pos   14U"
ACTLR: EVENTBUSEN Position 
.PP
Definition at line \fB1021\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_EVENTBUSEN_Pos   14U"
ACTLR: EVENTBUSEN Position 
.PP
Definition at line \fB1035\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_EVENTBUSEN_S_Msk   (1UL << \fBICB_ACTLR_EVENTBUSEN_S_Pos\fP)"
ACTLR: EVENTBUSEN_S Mask 
.PP
Definition at line \fB1025\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_EVENTBUSEN_S_Msk   (1UL << \fBICB_ACTLR_EVENTBUSEN_S_Pos\fP)"
ACTLR: EVENTBUSEN_S Mask 
.PP
Definition at line \fB1039\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_EVENTBUSEN_S_Pos   13U"
ACTLR: EVENTBUSEN_S Position 
.PP
Definition at line \fB1024\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_EVENTBUSEN_S_Pos   13U"
ACTLR: EVENTBUSEN_S Position 
.PP
Definition at line \fB1038\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_FPEXCODIS_Msk   (1UL << \fBICB_ACTLR_FPEXCODIS_Pos\fP)"
ACTLR: FPEXCODIS Mask 
.PP
Definition at line \fB1034\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_FPEXCODIS_Msk   (1UL << \fBICB_ACTLR_FPEXCODIS_Pos\fP)"
ACTLR: FPEXCODIS Mask 
.PP
Definition at line \fB1048\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ACTLR_FPEXCODIS_Pos   10U"
ACTLR: FPEXCODIS Position 
.PP
Definition at line \fB1033\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ACTLR_FPEXCODIS_Pos   10U"
ACTLR: FPEXCODIS Position 
.PP
Definition at line \fB1047\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBICB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB1056\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBICB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB1052\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define ICB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB1055\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define ICB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB1051\fP of file \fBcore_cm85\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
