.TH "CMSIS_register_aliases" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_register_aliases \- Backwards Compatibility Aliases
.PP
 \- Register alias definitions for backwards compatibility\&.  

.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "\fBFunctions and Instructions Reference\fP"
.br
.ti -1c
.RI "\fBNVIC Functions\fP"
.br
.RI "Functions that manage interrupts and exceptions via the NVIC\&. "
.in -1c
.in +1c
.ti -1c
.RI "typedef \fBICB_Type\fP \fBSCnSCB_Type\fP"
.br
.ti -1c
.RI "#define \fBID_ADR\fP   (ID_AFR)"
.br
.ti -1c
.RI "#define \fBID_ADR\fP   (ID_AFR)"
.br
.ti -1c
.RI "#define \fBID_ADR\fP   (ID_AFR)"
.br
.ti -1c
.RI "#define \fBID_ADR\fP   (ID_AFR)"
.br
.ti -1c
.RI "#define \fBID_ADR\fP   (ID_AFR)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISCRITAXIRUW_Pos\fP   (\fBICB_ACTLR_DISCRITAXIRUW_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISCRITAXIRUW_Msk\fP   (\fBICB_ACTLR_DISCRITAXIRUW_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDI_Pos\fP   (\fBICB_ACTLR_DISDI_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDI_Msk\fP   (\fBICB_ACTLR_DISDI_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISCRITAXIRUR_Pos\fP   (\fBICB_ACTLR_DISCRITAXIRUR_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISCRITAXIRUR_Msk\fP   (\fBICB_ACTLR_DISCRITAXIRUR_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_EVENTBUSEN_Pos\fP   (\fBICB_ACTLR_EVENTBUSEN_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_EVENTBUSEN_Msk\fP   (\fBICB_ACTLR_EVENTBUSEN_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_EVENTBUSEN_S_Pos\fP   (\fBICB_ACTLR_EVENTBUSEN_S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_EVENTBUSEN_S_Msk\fP   (\fBICB_ACTLR_EVENTBUSEN_S_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISITMATBFLUSH_Pos\fP   (\fBICB_ACTLR_DISITMATBFLUSH_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISITMATBFLUSH_Msk\fP   (\fBICB_ACTLR_DISITMATBFLUSH_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISNWAMODE_Pos\fP   (\fBICB_ACTLR_DISNWAMODE_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISNWAMODE_Msk\fP   (\fBICB_ACTLR_DISNWAMODE_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_FPEXCODIS_Pos\fP   (\fBICB_ACTLR_FPEXCODIS_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_FPEXCODIS_Msk\fP   (\fBICB_ACTLR_FPEXCODIS_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISOLAP_Pos\fP   (\fBICB_ACTLR_DISOLAP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISOLAP_Msk\fP   (\fBICB_ACTLR_DISOLAP_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISOLAPS_Pos\fP   (\fBICB_ACTLR_DISOLAPS_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISOLAPS_Msk\fP   (\fBICB_ACTLR_DISOLAPS_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISLOBR_Pos\fP   (\fBICB_ACTLR_DISLOBR_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISLOBR_Msk\fP   (\fBICB_ACTLR_DISLOBR_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISLO_Pos\fP   (\fBICB_ACTLR_DISLO_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISLO_Msk\fP   (\fBICB_ACTLR_DISLO_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISLOLEP_Pos\fP   (\fBICB_ACTLR_DISLOLEP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISLOLEP_Msk\fP   (\fBICB_ACTLR_DISLOLEP_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Pos\fP   (\fBICB_ACTLR_DISFOLD_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Msk\fP   (\fBICB_ACTLR_DISFOLD_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   (\fBICB_ICTR_INTLINESNUM_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (\fBICB_ICTR_INTLINESNUM_Msk\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB\fP   (\fBICB\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_NS\fP   (ICB_NS)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Register alias definitions for backwards compatibility\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define ID_ADR   (ID_AFR)"
SCB Auxiliary Feature Register 
.PP
Definition at line \fB3169\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define ID_ADR   (ID_AFR)"
SCB Auxiliary Feature Register 
.PP
Definition at line \fB2194\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define ID_ADR   (ID_AFR)"
SCB Auxiliary Feature Register 
.PP
Definition at line \fB2269\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define ID_ADR   (ID_AFR)"
SCB Auxiliary Feature Register 
.PP
Definition at line \fB2269\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define ID_ADR   (ID_AFR)"
SCB Auxiliary Feature Register 
.PP
Definition at line \fB3677\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB   (\fBICB\fP)"

.PP
Definition at line \fB3729\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISCRITAXIRUR_Msk   (\fBICB_ACTLR_DISCRITAXIRUR_Msk\fP)"

.PP
Definition at line \fB3690\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISCRITAXIRUR_Pos   (\fBICB_ACTLR_DISCRITAXIRUR_Pos\fP)"

.PP
Definition at line \fB3689\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISCRITAXIRUW_Msk   (\fBICB_ACTLR_DISCRITAXIRUW_Msk\fP)"

.PP
Definition at line \fB3684\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISCRITAXIRUW_Pos   (\fBICB_ACTLR_DISCRITAXIRUW_Pos\fP)"

.PP
Definition at line \fB3683\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISDI_Msk   (\fBICB_ACTLR_DISDI_Msk\fP)"

.PP
Definition at line \fB3687\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISDI_Pos   (\fBICB_ACTLR_DISDI_Pos\fP)"

.PP
Definition at line \fB3686\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Msk   (\fBICB_ACTLR_DISFOLD_Msk\fP)"

.PP
Definition at line \fB3723\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Pos   (\fBICB_ACTLR_DISFOLD_Pos\fP)"

.PP
Definition at line \fB3722\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISITMATBFLUSH_Msk   (\fBICB_ACTLR_DISITMATBFLUSH_Msk\fP)"

.PP
Definition at line \fB3699\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISITMATBFLUSH_Pos   (\fBICB_ACTLR_DISITMATBFLUSH_Pos\fP)"

.PP
Definition at line \fB3698\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISLO_Msk   (\fBICB_ACTLR_DISLO_Msk\fP)"

.PP
Definition at line \fB3717\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISLO_Pos   (\fBICB_ACTLR_DISLO_Pos\fP)"

.PP
Definition at line \fB3716\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISLOBR_Msk   (\fBICB_ACTLR_DISLOBR_Msk\fP)"

.PP
Definition at line \fB3714\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISLOBR_Pos   (\fBICB_ACTLR_DISLOBR_Pos\fP)"

.PP
Definition at line \fB3713\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISLOLEP_Msk   (\fBICB_ACTLR_DISLOLEP_Msk\fP)"

.PP
Definition at line \fB3720\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISLOLEP_Pos   (\fBICB_ACTLR_DISLOLEP_Pos\fP)"

.PP
Definition at line \fB3719\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISNWAMODE_Msk   (\fBICB_ACTLR_DISNWAMODE_Msk\fP)"

.PP
Definition at line \fB3702\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISNWAMODE_Pos   (\fBICB_ACTLR_DISNWAMODE_Pos\fP)"

.PP
Definition at line \fB3701\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISOLAP_Msk   (\fBICB_ACTLR_DISOLAP_Msk\fP)"

.PP
Definition at line \fB3708\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISOLAP_Pos   (\fBICB_ACTLR_DISOLAP_Pos\fP)"

.PP
Definition at line \fB3707\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISOLAPS_Msk   (\fBICB_ACTLR_DISOLAPS_Msk\fP)"

.PP
Definition at line \fB3711\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISOLAPS_Pos   (\fBICB_ACTLR_DISOLAPS_Pos\fP)"

.PP
Definition at line \fB3710\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_EVENTBUSEN_Msk   (\fBICB_ACTLR_EVENTBUSEN_Msk\fP)"

.PP
Definition at line \fB3693\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_EVENTBUSEN_Pos   (\fBICB_ACTLR_EVENTBUSEN_Pos\fP)"

.PP
Definition at line \fB3692\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_EVENTBUSEN_S_Msk   (\fBICB_ACTLR_EVENTBUSEN_S_Msk\fP)"

.PP
Definition at line \fB3696\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_EVENTBUSEN_S_Pos   (\fBICB_ACTLR_EVENTBUSEN_S_Pos\fP)"

.PP
Definition at line \fB3695\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_FPEXCODIS_Msk   (\fBICB_ACTLR_FPEXCODIS_Msk\fP)"

.PP
Definition at line \fB3705\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_FPEXCODIS_Pos   (\fBICB_ACTLR_FPEXCODIS_Pos\fP)"

.PP
Definition at line \fB3704\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (\fBICB_ICTR_INTLINESNUM_Msk\fP)"

.PP
Definition at line \fB3727\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   (\fBICB_ICTR_INTLINESNUM_Pos\fP)"

.PP
Definition at line \fB3726\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define SCnSCB_NS   (ICB_NS)"

.PP
Definition at line \fB3730\fP of file \fBcore_cm55\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBICB_Type\fP SCnSCB_Type"

.PP
Definition at line \fB3680\fP of file \fBcore_cm55\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
