.TH "CMSIS_Core_FunctionInterface" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_FunctionInterface \- Functions and Instructions Reference
.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "\fBCache Functions\fP"
.br
.RI "Functions that configure Instruction and Data cache\&. "
.ti -1c
.RI "\fBCMSIS Core Register Access Functions\fP"
.br
.ti -1c
.RI "\fBNVIC Functions\fP"
.br
.RI "Functions that manage interrupts and exceptions via the NVIC\&. "
.ti -1c
.RI "\fBPAC Key functions\fP"
.br
.RI "Functions that access the PAC keys\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
