.TH "CMSIS_Core_PacKeyFunctions" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_PacKeyFunctions \- PAC Key functions
.PP
 \- Functions that access the PAC keys\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Functions that access the PAC keys\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
