.TH "Inc/cmsis_compiler.h" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/cmsis_compiler.h \- CMSIS compiler generic header file\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SH "Detailed Description"
.PP 
CMSIS compiler generic header file\&. 


.PP
\fBVersion\fP
.RS 4
V5\&.1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
09\&. October 2018 
.RE
.PP

.PP
Definition in file \fBcmsis_compiler\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
