.TH "CMSIS_SCnSCB" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_SCnSCB \- System Controls not in SCB (SCnSCB)
.PP
 \- Type definitions for the System Control and ID Register not in the SCB\&.  

.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "\fBSystem Tick Timer (SysTick)\fP"
.br
.RI "Type definitions for the System Timer Registers\&. "
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSCnSCB_Type\fP"
.br
.RI "Structure type to access the System Control and ID Register not in the SCB\&. "
.in -1c
.in +1c
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_ITCMUAEN_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_ITCMUAEN_Msk\fP   (1UL << \fBSCnSCB_ACTLR_ITCMUAEN_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_ITCMLAEN_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_ITCMLAEN_Msk\fP   (1UL << \fBSCnSCB_ACTLR_ITCMLAEN_Pos\fP)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISOOFP_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISOOFP_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISOOFP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFPCA_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFPCA_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISFPCA_Pos\fP)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISFOLD_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDEFWBUF_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDEFWBUF_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISDEFWBUF_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Msk\fP   (1UL /*<< \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISFOLD_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Msk\fP   (1UL /*<< \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Msk\fP   (1UL /*<< \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISFOLD_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDEFWBUF_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDEFWBUF_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISDEFWBUF_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Msk\fP   (1UL /*<< \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP*/)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDYNADD_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDYNADD_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISDYNADD_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISISSCH1_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISISSCH1_Msk\fP   (0x1FUL << \fBSCnSCB_ACTLR_DISISSCH1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDI_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDI_Msk\fP   (0x1FUL << SCnSCB_ACTLR_DISDI_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISCRITAXIRUR_Pos\fP   15U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISCRITAXIRUR_Msk\fP   (1UL << SCnSCB_ACTLR_DISCRITAXIRUR_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISBTACALLOC_Pos\fP   14U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISBTACALLOC_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISBTACALLOC_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISBTACREAD_Pos\fP   13U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISBTACREAD_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISBTACREAD_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISITMATBFLUSH_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISITMATBFLUSH_Msk\fP   (1UL << SCnSCB_ACTLR_DISITMATBFLUSH_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISRAMODE_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISRAMODE_Msk\fP   (1UL << \fBSCnSCB_ACTLR_DISRAMODE_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_FPEXCODIS_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_FPEXCODIS_Msk\fP   (1UL << SCnSCB_ACTLR_FPEXCODIS_Pos)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the System Control and ID Register not in the SCB\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SCnSCB_ACTLR_DISBTACALLOC_Msk   (1UL << \fBSCnSCB_ACTLR_DISBTACALLOC_Pos\fP)"
ACTLR: DISBTACALLOC Mask 
.PP
Definition at line \fB955\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISBTACALLOC_Pos   14U"
ACTLR: DISBTACALLOC Position 
.PP
Definition at line \fB954\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISBTACREAD_Msk   (1UL << \fBSCnSCB_ACTLR_DISBTACREAD_Pos\fP)"
ACTLR: DISBTACREAD Mask 
.PP
Definition at line \fB958\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISBTACREAD_Pos   13U"
ACTLR: DISBTACREAD Position 
.PP
Definition at line \fB957\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISCRITAXIRUR_Msk   (1UL << SCnSCB_ACTLR_DISCRITAXIRUR_Pos)"
ACTLR: DISCRITAXIRUR Mask 
.PP
Definition at line \fB952\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISCRITAXIRUR_Pos   15U"
ACTLR: DISCRITAXIRUR Position 
.PP
Definition at line \fB951\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISDEFWBUF_Msk   (1UL << \fBSCnSCB_ACTLR_DISDEFWBUF_Pos\fP)"
ACTLR: DISDEFWBUF Mask 
.PP
Definition at line \fB746\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISDEFWBUF_Msk   (1UL << \fBSCnSCB_ACTLR_DISDEFWBUF_Pos\fP)"
ACTLR: DISDEFWBUF Mask 
.PP
Definition at line \fB673\fP of file \fBcore_sc300\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISDEFWBUF_Pos   1U"
ACTLR: DISDEFWBUF Position 
.PP
Definition at line \fB745\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISDEFWBUF_Pos   1U"
ACTLR: DISDEFWBUF Position 
.PP
Definition at line \fB672\fP of file \fBcore_sc300\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISDI_Msk   (0x1FUL << SCnSCB_ACTLR_DISDI_Pos)"
ACTLR: DISDI Mask 
.PP
Definition at line \fB949\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISDI_Pos   16U"
ACTLR: DISDI Position 
.PP
Definition at line \fB948\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISDYNADD_Msk   (1UL << \fBSCnSCB_ACTLR_DISDYNADD_Pos\fP)"
ACTLR: DISDYNADD Mask 
.PP
Definition at line \fB943\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISDYNADD_Pos   26U"
ACTLR: DISDYNADD Position 
.PP
Definition at line \fB942\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Msk   (1UL << \fBSCnSCB_ACTLR_DISFOLD_Pos\fP)"
ACTLR: DISFOLD Mask 
.PP
Definition at line \fB743\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Msk   (1UL << \fBSCnSCB_ACTLR_DISFOLD_Pos\fP)"
ACTLR: DISFOLD Mask 
.PP
Definition at line \fB970\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Msk   (1UL << \fBSCnSCB_ACTLR_DISFOLD_Pos\fP)"
ACTLR: DISFOLD Mask 
.PP
Definition at line \fB670\fP of file \fBcore_sc300\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Pos   2U"
ACTLR: DISFOLD Position 
.PP
Definition at line \fB742\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Pos   2U"
ACTLR: DISFOLD Position 
.PP
Definition at line \fB969\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Pos   2U"
ACTLR: DISFOLD Position 
.PP
Definition at line \fB669\fP of file \fBcore_sc300\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISFPCA_Msk   (1UL << \fBSCnSCB_ACTLR_DISFPCA_Pos\fP)"
ACTLR: DISFPCA Mask 
.PP
Definition at line \fB740\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISFPCA_Pos   8U"
ACTLR: DISFPCA Position 
.PP
Definition at line \fB739\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISISSCH1_Msk   (0x1FUL << \fBSCnSCB_ACTLR_DISISSCH1_Pos\fP)"
ACTLR: DISISSCH1 Mask 
.PP
Definition at line \fB946\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISISSCH1_Pos   21U"
ACTLR: DISISSCH1 Position 
.PP
Definition at line \fB945\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISITMATBFLUSH_Msk   (1UL << SCnSCB_ACTLR_DISITMATBFLUSH_Pos)"
ACTLR: DISITMATBFLUSH Mask 
.PP
Definition at line \fB961\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISITMATBFLUSH_Pos   12U"
ACTLR: DISITMATBFLUSH Position 
.PP
Definition at line \fB960\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Msk   (1UL /*<< \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP*/)"
ACTLR: DISMCYCINT Mask 
.PP
Definition at line \fB749\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Msk   (1UL /*<< \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP*/)"
ACTLR: DISMCYCINT Mask 
.PP
Definition at line \fB973\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Msk   (1UL /*<< \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP*/)"
ACTLR: DISMCYCINT Mask 
.PP
Definition at line \fB473\fP of file \fBcore_sc000\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Msk   (1UL /*<< \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP*/)"
ACTLR: DISMCYCINT Mask 
.PP
Definition at line \fB676\fP of file \fBcore_sc300\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Pos   0U"
ACTLR: DISMCYCINT Position 
.PP
Definition at line \fB748\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Pos   0U"
ACTLR: DISMCYCINT Position 
.PP
Definition at line \fB972\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Pos   0U"
ACTLR: DISMCYCINT Position 
.PP
Definition at line \fB472\fP of file \fBcore_sc000\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Pos   0U"
ACTLR: DISMCYCINT Position 
.PP
Definition at line \fB675\fP of file \fBcore_sc300\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISOOFP_Msk   (1UL << \fBSCnSCB_ACTLR_DISOOFP_Pos\fP)"
ACTLR: DISOOFP Mask 
.PP
Definition at line \fB737\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISOOFP_Pos   9U"
ACTLR: DISOOFP Position 
.PP
Definition at line \fB736\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISRAMODE_Msk   (1UL << \fBSCnSCB_ACTLR_DISRAMODE_Pos\fP)"
ACTLR: DISRAMODE Mask 
.PP
Definition at line \fB964\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_DISRAMODE_Pos   11U"
ACTLR: DISRAMODE Position 
.PP
Definition at line \fB963\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_FPEXCODIS_Msk   (1UL << SCnSCB_ACTLR_FPEXCODIS_Pos)"
ACTLR: FPEXCODIS Mask 
.PP
Definition at line \fB967\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_FPEXCODIS_Pos   10U"
ACTLR: FPEXCODIS Position 
.PP
Definition at line \fB966\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_ITCMLAEN_Msk   (1UL << \fBSCnSCB_ACTLR_ITCMLAEN_Pos\fP)"
ACTLR: Instruction TCM Lower Alias Enable Mask 
.PP
Definition at line \fB459\fP of file \fBcore_cm1\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_ITCMLAEN_Pos   3U"
ACTLR: Instruction TCM Lower Alias Enable Position 
.PP
Definition at line \fB458\fP of file \fBcore_cm1\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_ITCMUAEN_Msk   (1UL << \fBSCnSCB_ACTLR_ITCMUAEN_Pos\fP)"
ACTLR: Instruction TCM Upper Alias Enable Mask 
.PP
Definition at line \fB456\fP of file \fBcore_cm1\&.h\fP\&.
.SS "#define SCnSCB_ACTLR_ITCMUAEN_Pos   4U"
ACTLR: Instruction TCM Upper Alias Enable Position 
.PP
Definition at line \fB455\fP of file \fBcore_cm1\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB1011\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB950\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB673\fP of file \fBcore_cm3\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB950\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB950\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB733\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB939\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB666\fP of file \fBcore_sc300\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line \fB1008\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB1010\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB949\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB672\fP of file \fBcore_cm3\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB949\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB949\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB732\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB938\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB665\fP of file \fBcore_sc300\&.h\fP\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line \fB1007\fP of file \fBcore_starmc1\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
