.TH "CMSIS_Core_DCBFunctions" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_DCBFunctions \- Debug Control Functions
.PP
 \- Functions that access the Debug Control Block\&.  

.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "\fBDebug Identification Functions\fP"
.br
.RI "Functions that access the Debug Identification Block\&. "
.in -1c
.in +1c
.ti -1c
.RI "__STATIC_INLINE void \fBDCB_SetAuthCtrl\fP (uint32_t value)"
.br
.RI "Set Debug Authentication Control Register\&. "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBDCB_GetAuthCtrl\fP (void)"
.br
.RI "Get Debug Authentication Control Register\&. "
.in -1c
.SH "Detailed Description"
.PP 
Functions that access the Debug Control Block\&. 


.SH "Function Documentation"
.PP 
.SS "__STATIC_INLINE uint32_t DCB_GetAuthCtrl (void )"

.PP
Get Debug Authentication Control Register\&. Reads Debug Authentication Control register\&. 
.PP
\fBReturns\fP
.RS 4
Debug Authentication Control Register\&. 
.RE
.PP

.PP
Definition at line \fB3995\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "__STATIC_INLINE void DCB_SetAuthCtrl (uint32_t value)"

.PP
Set Debug Authentication Control Register\&. writes to Debug Authentication Control register\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP value to be writen\&. 
.RE
.PP

.PP
Definition at line \fB3980\fP of file \fBcore_armv81mml\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
