.TH "Inc/cmsis_version.h" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/cmsis_version.h \- CMSIS Core(M) Version definitions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CMSIS_VERSION_H\fP"
.br
.ti -1c
.RI "#define \fB__CM_CMSIS_VERSION_MAIN\fP   ( 5U)"
.br
.ti -1c
.RI "#define \fB__CM_CMSIS_VERSION_SUB\fP   ( 6U)"
.br
.ti -1c
.RI "#define \fB__CM_CMSIS_VERSION\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Core(M) Version definitions\&. 


.PP
\fBVersion\fP
.RS 4
V5\&.0\&.5 
.RE
.PP
\fBDate\fP
.RS 4
02\&. February 2022 
.RE
.PP

.PP
Definition in file \fBcmsis_version\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define __CM_CMSIS_VERSION"
\fBValue:\fP
.nf
                                   ((__CM_CMSIS_VERSION_MAIN << 16U) | \\
                                   __CM_CMSIS_VERSION_SUB           )
.PP
.fi
CMSIS Core(M) version number 
.PP
Definition at line \fB37\fP of file \fBcmsis_version\&.h\fP\&.
.SS "#define __CM_CMSIS_VERSION_MAIN   ( 5U)"
[31:16] CMSIS Core(M) main version 
.PP
Definition at line \fB35\fP of file \fBcmsis_version\&.h\fP\&.
.SS "#define __CM_CMSIS_VERSION_SUB   ( 6U)"
[15:0] CMSIS Core(M) sub version 
.PP
Definition at line \fB36\fP of file \fBcmsis_version\&.h\fP\&.
.SS "#define __CMSIS_VERSION_H"

.PP
Definition at line \fB32\fP of file \fBcmsis_version\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
