.TH "CMSIS_DIB" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_DIB \- Debug Identification Block
.PP
 \- Type definitions for the Debug Identification Block Registers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "\fBCore register bit field macros\fP"
.br
.RI "Macros for use with bit field definitions (xxx_Pos, xxx_Msk)\&. "
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBDIB_Type\fP"
.br
.RI "Structure type to access the Debug Identification Block Registers (DIB)\&. "
.in -1c
.in +1c
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Msk\fP   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Msk\fP   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Msk\fP   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Msk\fP   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Msk\fP   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Msk\fP   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Msk\fP   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Msk\fP   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Msk\fP   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Msk\fP   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Msk\fP   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Msk\fP   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Msk\fP   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Msk\fP   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Msk\fP   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Msk\fP   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Msk\fP   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Msk\fP   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Msk\fP   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Msk\fP   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Msk\fP   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Msk\fP   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Msk\fP   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Msk\fP   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Msk\fP   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Msk\fP   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Msk\fP   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Msk\fP   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Msk\fP   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Msk\fP   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Msk\fP   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Msk\fP   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Msk\fP   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Msk\fP   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Msk\fP   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Msk\fP   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Msk\fP   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Msk\fP   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Msk\fP   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Msk\fP   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Msk\fP   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Msk\fP   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Msk\fP   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Msk\fP   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Msk\fP   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Msk\fP   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Msk\fP   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Msk\fP   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Msk\fP   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Msk\fP   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Msk\fP   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Msk\fP   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Msk\fP   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Msk\fP   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Msk\fP   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Msk\fP   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Msk\fP   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Msk\fP   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Msk\fP   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Msk\fP   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Msk\fP   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Msk\fP   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Msk\fP   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Msk\fP   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Msk\fP   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Msk\fP   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Msk\fP   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Msk\fP   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Msk\fP   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Msk\fP   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Msk\fP   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Msk\fP   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Msk\fP   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Msk\fP   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Msk\fP   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Msk\fP   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Msk\fP   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Msk\fP   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Msk\fP   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Msk\fP   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLAR_KEY_Msk\fP   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_nTT_Msk\fP   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLK_Msk\fP   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DLSR_SLI_Msk\fP   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSID_Msk\fP   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Pos\fP   21U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHITECT_Msk\fP   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_PRESENT_Msk\fP   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_REVISION_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHVER_Msk\fP   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVARCH_ARCHPART_Msk\fP   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_SUB_Msk\fP   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBDIB_DDEVTYPE_MAJOR_Msk\fP   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUNID_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SUNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUID_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SUID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUNID_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSUNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUID_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSUID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUNID_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SUNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUID_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SUID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUNID_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSUNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUID_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSUID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUNID_Pos\fP   22U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SUNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUID_Pos\fP   20U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_SUID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_SUID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUNID_Pos\fP   18U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUNID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSUNID_Pos\fP )"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUID_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBDIB_DAUTHSTATUS_NSUID_Msk\fP   (0x3UL << \fBDIB_DAUTHSTATUS_NSUID_Pos\fP )"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the Debug Identification Block Registers\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define DIB_DAUTHSTATUS_NSID_Msk   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
DIB DAUTHSTATUS: Non-secure Invasive Debug Mask 
.PP
Definition at line \fB3031\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Msk   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
DIB DAUTHSTATUS: Non-secure Invasive Debug Mask 
.PP
Definition at line \fB1238\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Msk   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
DIB DAUTHSTATUS: Non-secure Invasive Debug Mask 
.PP
Definition at line \fB2061\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Msk   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
DIB DAUTHSTATUS: Non-secure Invasive Debug Mask 
.PP
Definition at line \fB1313\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Msk   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
DIB DAUTHSTATUS: Non-secure Invasive Debug Mask 
.PP
Definition at line \fB2136\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Msk   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
DIB DAUTHSTATUS: Non-secure Invasive Debug Mask 
.PP
Definition at line \fB2136\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Msk   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
DIB DAUTHSTATUS: Non-secure Invasive Debug Mask 
.PP
Definition at line \fB3527\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Msk   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
DIB DAUTHSTATUS: Non-secure Invasive Debug Mask 
.PP
Definition at line \fB3432\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Msk   (0x3UL /*<< \fBDIB_DAUTHSTATUS_NSID_Pos\fP*/)"
DIB DAUTHSTATUS: Non-secure Invasive Debug Mask 
.PP
Definition at line \fB2063\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Pos   0U"
DIB DAUTHSTATUS: Non-secure Invasive Debug Position 
.PP
Definition at line \fB3030\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Pos   0U"
DIB DAUTHSTATUS: Non-secure Invasive Debug Position 
.PP
Definition at line \fB1237\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Pos   0U"
DIB DAUTHSTATUS: Non-secure Invasive Debug Position 
.PP
Definition at line \fB2060\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Pos   0U"
DIB DAUTHSTATUS: Non-secure Invasive Debug Position 
.PP
Definition at line \fB1312\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Pos   0U"
DIB DAUTHSTATUS: Non-secure Invasive Debug Position 
.PP
Definition at line \fB2135\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Pos   0U"
DIB DAUTHSTATUS: Non-secure Invasive Debug Position 
.PP
Definition at line \fB2135\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Pos   0U"
DIB DAUTHSTATUS: Non-secure Invasive Debug Position 
.PP
Definition at line \fB3526\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Pos   0U"
DIB DAUTHSTATUS: Non-secure Invasive Debug Position 
.PP
Definition at line \fB3431\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSID_Pos   0U"
DIB DAUTHSTATUS: Non-secure Invasive Debug Position 
.PP
Definition at line \fB2062\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Mask 
.PP
Definition at line \fB3028\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Mask 
.PP
Definition at line \fB1235\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Mask 
.PP
Definition at line \fB2058\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Mask 
.PP
Definition at line \fB1310\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Mask 
.PP
Definition at line \fB2133\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Mask 
.PP
Definition at line \fB2133\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Mask 
.PP
Definition at line \fB3524\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Mask 
.PP
Definition at line \fB3429\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Mask 
.PP
Definition at line \fB2060\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Pos   2U"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Position 
.PP
Definition at line \fB3027\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Pos   2U"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Position 
.PP
Definition at line \fB1234\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Pos   2U"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Position 
.PP
Definition at line \fB2057\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Pos   2U"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Position 
.PP
Definition at line \fB1309\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Pos   2U"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Position 
.PP
Definition at line \fB2132\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Pos   2U"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Position 
.PP
Definition at line \fB2132\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Pos   2U"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Position 
.PP
Definition at line \fB3523\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Pos   2U"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Position 
.PP
Definition at line \fB3428\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSNID_Pos   2U"
DIB DAUTHSTATUS: Non-secure Non-invasive Debug Position 
.PP
Definition at line \fB2059\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSUID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Unprivileged Invasive Debug Allowed Mask 
.PP
Definition at line \fB3019\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSUID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Unprivileged Invasive Debug Allowed Mask 
.PP
Definition at line \fB3515\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSUID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Unprivileged Invasive Debug Allowed Mask 
.PP
Definition at line \fB3420\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUID_Pos   16U"
DIB DAUTHSTATUS: Non-secure Unprivileged Invasive Debug Allowed Position 
.PP
Definition at line \fB3018\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUID_Pos   16U"
DIB DAUTHSTATUS: Non-secure Unprivileged Invasive Debug Allowed Position 
.PP
Definition at line \fB3514\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUID_Pos   16U"
DIB DAUTHSTATUS: Non-secure Unprivileged Invasive Debug Allowed Position 
.PP
Definition at line \fB3419\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSUNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Unprivileged Non-invasive Debug Allo Mask 
.PP
Definition at line \fB3016\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSUNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Unprivileged Non-invasive Debug Allo Mask 
.PP
Definition at line \fB3512\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_NSUNID_Pos\fP )"
DIB DAUTHSTATUS: Non-secure Unprivileged Non-invasive Debug Allo Mask 
.PP
Definition at line \fB3417\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUNID_Pos   18U"
DIB DAUTHSTATUS: Non-secure Unprivileged Non-invasive Debug Allo Position 
.PP
Definition at line \fB3015\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUNID_Pos   18U"
DIB DAUTHSTATUS: Non-secure Unprivileged Non-invasive Debug Allo Position 
.PP
Definition at line \fB3511\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_NSUNID_Pos   18U"
DIB DAUTHSTATUS: Non-secure Unprivileged Non-invasive Debug Allo Position 
.PP
Definition at line \fB3416\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
DIB DAUTHSTATUS: Secure Invasive Debug Mask 
.PP
Definition at line \fB3025\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
DIB DAUTHSTATUS: Secure Invasive Debug Mask 
.PP
Definition at line \fB1232\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
DIB DAUTHSTATUS: Secure Invasive Debug Mask 
.PP
Definition at line \fB2055\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
DIB DAUTHSTATUS: Secure Invasive Debug Mask 
.PP
Definition at line \fB1307\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
DIB DAUTHSTATUS: Secure Invasive Debug Mask 
.PP
Definition at line \fB2130\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
DIB DAUTHSTATUS: Secure Invasive Debug Mask 
.PP
Definition at line \fB2130\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
DIB DAUTHSTATUS: Secure Invasive Debug Mask 
.PP
Definition at line \fB3521\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
DIB DAUTHSTATUS: Secure Invasive Debug Mask 
.PP
Definition at line \fB3426\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SID_Pos\fP )"
DIB DAUTHSTATUS: Secure Invasive Debug Mask 
.PP
Definition at line \fB2057\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Pos   4U"
DIB DAUTHSTATUS: Secure Invasive Debug Position 
.PP
Definition at line \fB3024\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Pos   4U"
DIB DAUTHSTATUS: Secure Invasive Debug Position 
.PP
Definition at line \fB1231\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Pos   4U"
DIB DAUTHSTATUS: Secure Invasive Debug Position 
.PP
Definition at line \fB2054\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Pos   4U"
DIB DAUTHSTATUS: Secure Invasive Debug Position 
.PP
Definition at line \fB1306\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Pos   4U"
DIB DAUTHSTATUS: Secure Invasive Debug Position 
.PP
Definition at line \fB2129\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Pos   4U"
DIB DAUTHSTATUS: Secure Invasive Debug Position 
.PP
Definition at line \fB2129\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Pos   4U"
DIB DAUTHSTATUS: Secure Invasive Debug Position 
.PP
Definition at line \fB3520\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Pos   4U"
DIB DAUTHSTATUS: Secure Invasive Debug Position 
.PP
Definition at line \fB3425\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SID_Pos   4U"
DIB DAUTHSTATUS: Secure Invasive Debug Position 
.PP
Definition at line \fB2056\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Non-invasive Debug Mask 
.PP
Definition at line \fB3022\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Non-invasive Debug Mask 
.PP
Definition at line \fB1229\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Non-invasive Debug Mask 
.PP
Definition at line \fB2052\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Non-invasive Debug Mask 
.PP
Definition at line \fB1304\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Non-invasive Debug Mask 
.PP
Definition at line \fB2127\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Non-invasive Debug Mask 
.PP
Definition at line \fB2127\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Non-invasive Debug Mask 
.PP
Definition at line \fB3518\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Non-invasive Debug Mask 
.PP
Definition at line \fB3423\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Non-invasive Debug Mask 
.PP
Definition at line \fB2054\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Pos   6U"
DIB DAUTHSTATUS: Secure Non-invasive Debug Position 
.PP
Definition at line \fB3021\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Pos   6U"
DIB DAUTHSTATUS: Secure Non-invasive Debug Position 
.PP
Definition at line \fB1228\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Pos   6U"
DIB DAUTHSTATUS: Secure Non-invasive Debug Position 
.PP
Definition at line \fB2051\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Pos   6U"
DIB DAUTHSTATUS: Secure Non-invasive Debug Position 
.PP
Definition at line \fB1303\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Pos   6U"
DIB DAUTHSTATUS: Secure Non-invasive Debug Position 
.PP
Definition at line \fB2126\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Pos   6U"
DIB DAUTHSTATUS: Secure Non-invasive Debug Position 
.PP
Definition at line \fB2126\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Pos   6U"
DIB DAUTHSTATUS: Secure Non-invasive Debug Position 
.PP
Definition at line \fB3517\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Pos   6U"
DIB DAUTHSTATUS: Secure Non-invasive Debug Position 
.PP
Definition at line \fB3422\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SNID_Pos   6U"
DIB DAUTHSTATUS: Secure Non-invasive Debug Position 
.PP
Definition at line \fB2053\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SUID_Pos\fP )"
DIB DAUTHSTATUS: Secure Unprivileged Invasive Debug Allowed Mask 
.PP
Definition at line \fB3013\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SUID_Pos\fP )"
DIB DAUTHSTATUS: Secure Unprivileged Invasive Debug Allowed Mask 
.PP
Definition at line \fB3509\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SUID_Pos\fP )"
DIB DAUTHSTATUS: Secure Unprivileged Invasive Debug Allowed Mask 
.PP
Definition at line \fB3414\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUID_Pos   20U"
DIB DAUTHSTATUS: Secure Unprivileged Invasive Debug Allowed Position 
.PP
Definition at line \fB3012\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUID_Pos   20U"
DIB DAUTHSTATUS: Secure Unprivileged Invasive Debug Allowed Position 
.PP
Definition at line \fB3508\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUID_Pos   20U"
DIB DAUTHSTATUS: Secure Unprivileged Invasive Debug Allowed Position 
.PP
Definition at line \fB3413\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SUNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Unprivileged Non-invasive Debug Allowed Mask 
.PP
Definition at line \fB3010\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SUNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Unprivileged Non-invasive Debug Allowed Mask 
.PP
Definition at line \fB3506\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUNID_Msk   (0x3UL << \fBDIB_DAUTHSTATUS_SUNID_Pos\fP )"
DIB DAUTHSTATUS: Secure Unprivileged Non-invasive Debug Allowed Mask 
.PP
Definition at line \fB3411\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUNID_Pos   22U"
DIB DAUTHSTATUS: Secure Unprivileged Non-invasive Debug Allowed Position 
.PP
Definition at line \fB3009\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUNID_Pos   22U"
DIB DAUTHSTATUS: Secure Unprivileged Non-invasive Debug Allowed Position 
.PP
Definition at line \fB3505\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DAUTHSTATUS_SUNID_Pos   22U"
DIB DAUTHSTATUS: Secure Unprivileged Non-invasive Debug Allowed Position 
.PP
Definition at line \fB3410\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Msk   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
DIB DDEVARCH: Architect Mask 
.PP
Definition at line \fB3035\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Msk   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
DIB DDEVARCH: Architect Mask 
.PP
Definition at line \fB1242\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Msk   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
DIB DDEVARCH: Architect Mask 
.PP
Definition at line \fB2065\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Msk   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
DIB DDEVARCH: Architect Mask 
.PP
Definition at line \fB1317\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Msk   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
DIB DDEVARCH: Architect Mask 
.PP
Definition at line \fB2140\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Msk   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
DIB DDEVARCH: Architect Mask 
.PP
Definition at line \fB2140\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Msk   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
DIB DDEVARCH: Architect Mask 
.PP
Definition at line \fB3531\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Msk   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
DIB DDEVARCH: Architect Mask 
.PP
Definition at line \fB3436\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Msk   (0x7FFUL << \fBDIB_DDEVARCH_ARCHITECT_Pos\fP )"
DIB DDEVARCH: Architect Mask 
.PP
Definition at line \fB2067\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Pos   21U"
DIB DDEVARCH: Architect Position 
.PP
Definition at line \fB3034\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Pos   21U"
DIB DDEVARCH: Architect Position 
.PP
Definition at line \fB1241\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Pos   21U"
DIB DDEVARCH: Architect Position 
.PP
Definition at line \fB2064\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Pos   21U"
DIB DDEVARCH: Architect Position 
.PP
Definition at line \fB1316\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Pos   21U"
DIB DDEVARCH: Architect Position 
.PP
Definition at line \fB2139\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Pos   21U"
DIB DDEVARCH: Architect Position 
.PP
Definition at line \fB2139\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Pos   21U"
DIB DDEVARCH: Architect Position 
.PP
Definition at line \fB3530\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Pos   21U"
DIB DDEVARCH: Architect Position 
.PP
Definition at line \fB3435\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHITECT_Pos   21U"
DIB DDEVARCH: Architect Position 
.PP
Definition at line \fB2066\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Msk   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
DIB DDEVARCH: Architecture Part Mask 
.PP
Definition at line \fB3047\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Msk   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
DIB DDEVARCH: Architecture Part Mask 
.PP
Definition at line \fB1254\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Msk   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
DIB DDEVARCH: Architecture Part Mask 
.PP
Definition at line \fB2077\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Msk   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
DIB DDEVARCH: Architecture Part Mask 
.PP
Definition at line \fB1329\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Msk   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
DIB DDEVARCH: Architecture Part Mask 
.PP
Definition at line \fB2152\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Msk   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
DIB DDEVARCH: Architecture Part Mask 
.PP
Definition at line \fB2152\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Msk   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
DIB DDEVARCH: Architecture Part Mask 
.PP
Definition at line \fB3543\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Msk   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
DIB DDEVARCH: Architecture Part Mask 
.PP
Definition at line \fB3448\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Msk   (0xFFFUL /*<< \fBDIB_DDEVARCH_ARCHPART_Pos\fP*/)"
DIB DDEVARCH: Architecture Part Mask 
.PP
Definition at line \fB2079\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Pos   0U"
DIB DDEVARCH: Architecture Part Position 
.PP
Definition at line \fB3046\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Pos   0U"
DIB DDEVARCH: Architecture Part Position 
.PP
Definition at line \fB1253\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Pos   0U"
DIB DDEVARCH: Architecture Part Position 
.PP
Definition at line \fB2076\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Pos   0U"
DIB DDEVARCH: Architecture Part Position 
.PP
Definition at line \fB1328\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Pos   0U"
DIB DDEVARCH: Architecture Part Position 
.PP
Definition at line \fB2151\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Pos   0U"
DIB DDEVARCH: Architecture Part Position 
.PP
Definition at line \fB2151\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Pos   0U"
DIB DDEVARCH: Architecture Part Position 
.PP
Definition at line \fB3542\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Pos   0U"
DIB DDEVARCH: Architecture Part Position 
.PP
Definition at line \fB3447\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHPART_Pos   0U"
DIB DDEVARCH: Architecture Part Position 
.PP
Definition at line \fB2078\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Msk   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
DIB DDEVARCH: Architecture Version Mask 
.PP
Definition at line \fB3044\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Msk   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
DIB DDEVARCH: Architecture Version Mask 
.PP
Definition at line \fB1251\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Msk   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
DIB DDEVARCH: Architecture Version Mask 
.PP
Definition at line \fB2074\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Msk   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
DIB DDEVARCH: Architecture Version Mask 
.PP
Definition at line \fB1326\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Msk   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
DIB DDEVARCH: Architecture Version Mask 
.PP
Definition at line \fB2149\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Msk   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
DIB DDEVARCH: Architecture Version Mask 
.PP
Definition at line \fB2149\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Msk   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
DIB DDEVARCH: Architecture Version Mask 
.PP
Definition at line \fB3540\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Msk   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
DIB DDEVARCH: Architecture Version Mask 
.PP
Definition at line \fB3445\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Msk   (0xFUL << \fBDIB_DDEVARCH_ARCHVER_Pos\fP )"
DIB DDEVARCH: Architecture Version Mask 
.PP
Definition at line \fB2076\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Pos   12U"
DIB DDEVARCH: Architecture Version Position 
.PP
Definition at line \fB3043\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Pos   12U"
DIB DDEVARCH: Architecture Version Position 
.PP
Definition at line \fB1250\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Pos   12U"
DIB DDEVARCH: Architecture Version Position 
.PP
Definition at line \fB2073\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Pos   12U"
DIB DDEVARCH: Architecture Version Position 
.PP
Definition at line \fB1325\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Pos   12U"
DIB DDEVARCH: Architecture Version Position 
.PP
Definition at line \fB2148\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Pos   12U"
DIB DDEVARCH: Architecture Version Position 
.PP
Definition at line \fB2148\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Pos   12U"
DIB DDEVARCH: Architecture Version Position 
.PP
Definition at line \fB3539\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Pos   12U"
DIB DDEVARCH: Architecture Version Position 
.PP
Definition at line \fB3444\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_ARCHVER_Pos   12U"
DIB DDEVARCH: Architecture Version Position 
.PP
Definition at line \fB2075\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Msk   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
DIB DDEVARCH: DEVARCH Present Mask 
.PP
Definition at line \fB3038\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Msk   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
DIB DDEVARCH: DEVARCH Present Mask 
.PP
Definition at line \fB1245\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Msk   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
DIB DDEVARCH: DEVARCH Present Mask 
.PP
Definition at line \fB2068\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Msk   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
DIB DDEVARCH: DEVARCH Present Mask 
.PP
Definition at line \fB1320\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Msk   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
DIB DDEVARCH: DEVARCH Present Mask 
.PP
Definition at line \fB2143\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Msk   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
DIB DDEVARCH: DEVARCH Present Mask 
.PP
Definition at line \fB2143\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Msk   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
DIB DDEVARCH: DEVARCH Present Mask 
.PP
Definition at line \fB3534\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Msk   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
DIB DDEVARCH: DEVARCH Present Mask 
.PP
Definition at line \fB3439\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Msk   (0x1FUL << \fBDIB_DDEVARCH_PRESENT_Pos\fP )"
DIB DDEVARCH: DEVARCH Present Mask 
.PP
Definition at line \fB2070\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Pos   20U"
DIB DDEVARCH: DEVARCH Present Position 
.PP
Definition at line \fB3037\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Pos   20U"
DIB DDEVARCH: DEVARCH Present Position 
.PP
Definition at line \fB1244\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Pos   20U"
DIB DDEVARCH: DEVARCH Present Position 
.PP
Definition at line \fB2067\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Pos   20U"
DIB DDEVARCH: DEVARCH Present Position 
.PP
Definition at line \fB1319\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Pos   20U"
DIB DDEVARCH: DEVARCH Present Position 
.PP
Definition at line \fB2142\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Pos   20U"
DIB DDEVARCH: DEVARCH Present Position 
.PP
Definition at line \fB2142\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Pos   20U"
DIB DDEVARCH: DEVARCH Present Position 
.PP
Definition at line \fB3533\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Pos   20U"
DIB DDEVARCH: DEVARCH Present Position 
.PP
Definition at line \fB3438\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_PRESENT_Pos   20U"
DIB DDEVARCH: DEVARCH Present Position 
.PP
Definition at line \fB2069\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Msk   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
DIB DDEVARCH: Revision Mask 
.PP
Definition at line \fB3041\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Msk   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
DIB DDEVARCH: Revision Mask 
.PP
Definition at line \fB1248\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Msk   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
DIB DDEVARCH: Revision Mask 
.PP
Definition at line \fB2071\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Msk   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
DIB DDEVARCH: Revision Mask 
.PP
Definition at line \fB1323\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Msk   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
DIB DDEVARCH: Revision Mask 
.PP
Definition at line \fB2146\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Msk   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
DIB DDEVARCH: Revision Mask 
.PP
Definition at line \fB2146\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Msk   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
DIB DDEVARCH: Revision Mask 
.PP
Definition at line \fB3537\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Msk   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
DIB DDEVARCH: Revision Mask 
.PP
Definition at line \fB3442\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Msk   (0xFUL << \fBDIB_DDEVARCH_REVISION_Pos\fP )"
DIB DDEVARCH: Revision Mask 
.PP
Definition at line \fB2073\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Pos   16U"
DIB DDEVARCH: Revision Position 
.PP
Definition at line \fB3040\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Pos   16U"
DIB DDEVARCH: Revision Position 
.PP
Definition at line \fB1247\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Pos   16U"
DIB DDEVARCH: Revision Position 
.PP
Definition at line \fB2070\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Pos   16U"
DIB DDEVARCH: Revision Position 
.PP
Definition at line \fB1322\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Pos   16U"
DIB DDEVARCH: Revision Position 
.PP
Definition at line \fB2145\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Pos   16U"
DIB DDEVARCH: Revision Position 
.PP
Definition at line \fB2145\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Pos   16U"
DIB DDEVARCH: Revision Position 
.PP
Definition at line \fB3536\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Pos   16U"
DIB DDEVARCH: Revision Position 
.PP
Definition at line \fB3441\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVARCH_REVISION_Pos   16U"
DIB DDEVARCH: Revision Position 
.PP
Definition at line \fB2072\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Msk   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
DIB DDEVTYPE: Major type Mask 
.PP
Definition at line \fB3054\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Msk   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
DIB DDEVTYPE: Major type Mask 
.PP
Definition at line \fB1261\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Msk   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
DIB DDEVTYPE: Major type Mask 
.PP
Definition at line \fB2084\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Msk   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
DIB DDEVTYPE: Major type Mask 
.PP
Definition at line \fB1336\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Msk   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
DIB DDEVTYPE: Major type Mask 
.PP
Definition at line \fB2159\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Msk   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
DIB DDEVTYPE: Major type Mask 
.PP
Definition at line \fB2159\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Msk   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
DIB DDEVTYPE: Major type Mask 
.PP
Definition at line \fB3550\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Msk   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
DIB DDEVTYPE: Major type Mask 
.PP
Definition at line \fB3455\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Msk   (0xFUL /*<< \fBDIB_DDEVTYPE_MAJOR_Pos\fP*/)"
DIB DDEVTYPE: Major type Mask 
.PP
Definition at line \fB2086\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Pos   0U"
DIB DDEVTYPE: Major type Position 
.PP
Definition at line \fB3053\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Pos   0U"
DIB DDEVTYPE: Major type Position 
.PP
Definition at line \fB1260\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Pos   0U"
DIB DDEVTYPE: Major type Position 
.PP
Definition at line \fB2083\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Pos   0U"
DIB DDEVTYPE: Major type Position 
.PP
Definition at line \fB1335\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Pos   0U"
DIB DDEVTYPE: Major type Position 
.PP
Definition at line \fB2158\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Pos   0U"
DIB DDEVTYPE: Major type Position 
.PP
Definition at line \fB2158\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Pos   0U"
DIB DDEVTYPE: Major type Position 
.PP
Definition at line \fB3549\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Pos   0U"
DIB DDEVTYPE: Major type Position 
.PP
Definition at line \fB3454\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_MAJOR_Pos   0U"
DIB DDEVTYPE: Major type Position 
.PP
Definition at line \fB2085\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Msk   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
DIB DDEVTYPE: Sub-type Mask 
.PP
Definition at line \fB3051\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Msk   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
DIB DDEVTYPE: Sub-type Mask 
.PP
Definition at line \fB1258\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Msk   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
DIB DDEVTYPE: Sub-type Mask 
.PP
Definition at line \fB2081\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Msk   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
DIB DDEVTYPE: Sub-type Mask 
.PP
Definition at line \fB1333\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Msk   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
DIB DDEVTYPE: Sub-type Mask 
.PP
Definition at line \fB2156\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Msk   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
DIB DDEVTYPE: Sub-type Mask 
.PP
Definition at line \fB2156\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Msk   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
DIB DDEVTYPE: Sub-type Mask 
.PP
Definition at line \fB3547\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Msk   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
DIB DDEVTYPE: Sub-type Mask 
.PP
Definition at line \fB3452\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Msk   (0xFUL << \fBDIB_DDEVTYPE_SUB_Pos\fP )"
DIB DDEVTYPE: Sub-type Mask 
.PP
Definition at line \fB2083\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Pos   4U"
DIB DDEVTYPE: Sub-type Position 
.PP
Definition at line \fB3050\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Pos   4U"
DIB DDEVTYPE: Sub-type Position 
.PP
Definition at line \fB1257\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Pos   4U"
DIB DDEVTYPE: Sub-type Position 
.PP
Definition at line \fB2080\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Pos   4U"
DIB DDEVTYPE: Sub-type Position 
.PP
Definition at line \fB1332\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Pos   4U"
DIB DDEVTYPE: Sub-type Position 
.PP
Definition at line \fB2155\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Pos   4U"
DIB DDEVTYPE: Sub-type Position 
.PP
Definition at line \fB2155\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Pos   4U"
DIB DDEVTYPE: Sub-type Position 
.PP
Definition at line \fB3546\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Pos   4U"
DIB DDEVTYPE: Sub-type Position 
.PP
Definition at line \fB3451\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DDEVTYPE_SUB_Pos   4U"
DIB DDEVTYPE: Sub-type Position 
.PP
Definition at line \fB2082\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Msk   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
DIB DLAR: KEY Mask 
.PP
Definition at line \fB2996\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Msk   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
DIB DLAR: KEY Mask 
.PP
Definition at line \fB1215\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Msk   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
DIB DLAR: KEY Mask 
.PP
Definition at line \fB2038\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Msk   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
DIB DLAR: KEY Mask 
.PP
Definition at line \fB1290\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Msk   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
DIB DLAR: KEY Mask 
.PP
Definition at line \fB2113\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Msk   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
DIB DLAR: KEY Mask 
.PP
Definition at line \fB2113\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Msk   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
DIB DLAR: KEY Mask 
.PP
Definition at line \fB3492\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Msk   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
DIB DLAR: KEY Mask 
.PP
Definition at line \fB3397\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Msk   (0xFFFFFFFFUL /*<< \fBDIB_DLAR_KEY_Pos\fP */)"
DIB DLAR: KEY Mask 
.PP
Definition at line \fB2040\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Pos   0U"
DIB DLAR: KEY Position 
.PP
Definition at line \fB2995\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Pos   0U"
DIB DLAR: KEY Position 
.PP
Definition at line \fB1214\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Pos   0U"
DIB DLAR: KEY Position 
.PP
Definition at line \fB2037\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Pos   0U"
DIB DLAR: KEY Position 
.PP
Definition at line \fB1289\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Pos   0U"
DIB DLAR: KEY Position 
.PP
Definition at line \fB2112\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Pos   0U"
DIB DLAR: KEY Position 
.PP
Definition at line \fB2112\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Pos   0U"
DIB DLAR: KEY Position 
.PP
Definition at line \fB3491\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Pos   0U"
DIB DLAR: KEY Position 
.PP
Definition at line \fB3396\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DLAR_KEY_Pos   0U"
DIB DLAR: KEY Position 
.PP
Definition at line \fB2039\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Msk   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
DIB DLSR: Not thirty-two bit Mask 
.PP
Definition at line \fB3000\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Msk   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
DIB DLSR: Not thirty-two bit Mask 
.PP
Definition at line \fB1219\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Msk   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
DIB DLSR: Not thirty-two bit Mask 
.PP
Definition at line \fB2042\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Msk   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
DIB DLSR: Not thirty-two bit Mask 
.PP
Definition at line \fB1294\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Msk   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
DIB DLSR: Not thirty-two bit Mask 
.PP
Definition at line \fB2117\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Msk   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
DIB DLSR: Not thirty-two bit Mask 
.PP
Definition at line \fB2117\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Msk   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
DIB DLSR: Not thirty-two bit Mask 
.PP
Definition at line \fB3496\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Msk   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
DIB DLSR: Not thirty-two bit Mask 
.PP
Definition at line \fB3401\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Msk   (0x1UL << \fBDIB_DLSR_nTT_Pos\fP )"
DIB DLSR: Not thirty-two bit Mask 
.PP
Definition at line \fB2044\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Pos   2U"
DIB DLSR: Not thirty-two bit Position 
.PP
Definition at line \fB2999\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Pos   2U"
DIB DLSR: Not thirty-two bit Position 
.PP
Definition at line \fB1218\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Pos   2U"
DIB DLSR: Not thirty-two bit Position 
.PP
Definition at line \fB2041\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Pos   2U"
DIB DLSR: Not thirty-two bit Position 
.PP
Definition at line \fB1293\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Pos   2U"
DIB DLSR: Not thirty-two bit Position 
.PP
Definition at line \fB2116\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Pos   2U"
DIB DLSR: Not thirty-two bit Position 
.PP
Definition at line \fB2116\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Pos   2U"
DIB DLSR: Not thirty-two bit Position 
.PP
Definition at line \fB3495\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Pos   2U"
DIB DLSR: Not thirty-two bit Position 
.PP
Definition at line \fB3400\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DLSR_nTT_Pos   2U"
DIB DLSR: Not thirty-two bit Position 
.PP
Definition at line \fB2043\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Msk   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
DIB DLSR: Software Lock implemented Mask 
.PP
Definition at line \fB3006\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Msk   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
DIB DLSR: Software Lock implemented Mask 
.PP
Definition at line \fB1225\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Msk   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
DIB DLSR: Software Lock implemented Mask 
.PP
Definition at line \fB2048\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Msk   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
DIB DLSR: Software Lock implemented Mask 
.PP
Definition at line \fB1300\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Msk   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
DIB DLSR: Software Lock implemented Mask 
.PP
Definition at line \fB2123\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Msk   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
DIB DLSR: Software Lock implemented Mask 
.PP
Definition at line \fB2123\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Msk   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
DIB DLSR: Software Lock implemented Mask 
.PP
Definition at line \fB3502\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Msk   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
DIB DLSR: Software Lock implemented Mask 
.PP
Definition at line \fB3407\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Msk   (0x1UL /*<< \fBDIB_DLSR_SLI_Pos\fP*/)"
DIB DLSR: Software Lock implemented Mask 
.PP
Definition at line \fB2050\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Pos   0U"
DIB DLSR: Software Lock implemented Position 
.PP
Definition at line \fB3005\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Pos   0U"
DIB DLSR: Software Lock implemented Position 
.PP
Definition at line \fB1224\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Pos   0U"
DIB DLSR: Software Lock implemented Position 
.PP
Definition at line \fB2047\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Pos   0U"
DIB DLSR: Software Lock implemented Position 
.PP
Definition at line \fB1299\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Pos   0U"
DIB DLSR: Software Lock implemented Position 
.PP
Definition at line \fB2122\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Pos   0U"
DIB DLSR: Software Lock implemented Position 
.PP
Definition at line \fB2122\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Pos   0U"
DIB DLSR: Software Lock implemented Position 
.PP
Definition at line \fB3501\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Pos   0U"
DIB DLSR: Software Lock implemented Position 
.PP
Definition at line \fB3406\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DLSR_SLI_Pos   0U"
DIB DLSR: Software Lock implemented Position 
.PP
Definition at line \fB2049\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Msk   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
DIB DLSR: Software Lock status Mask 
.PP
Definition at line \fB3003\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Msk   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
DIB DLSR: Software Lock status Mask 
.PP
Definition at line \fB1222\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Msk   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
DIB DLSR: Software Lock status Mask 
.PP
Definition at line \fB2045\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Msk   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
DIB DLSR: Software Lock status Mask 
.PP
Definition at line \fB1297\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Msk   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
DIB DLSR: Software Lock status Mask 
.PP
Definition at line \fB2120\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Msk   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
DIB DLSR: Software Lock status Mask 
.PP
Definition at line \fB2120\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Msk   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
DIB DLSR: Software Lock status Mask 
.PP
Definition at line \fB3499\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Msk   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
DIB DLSR: Software Lock status Mask 
.PP
Definition at line \fB3404\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Msk   (0x1UL << \fBDIB_DLSR_SLK_Pos\fP )"
DIB DLSR: Software Lock status Mask 
.PP
Definition at line \fB2047\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Pos   1U"
DIB DLSR: Software Lock status Position 
.PP
Definition at line \fB3002\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Pos   1U"
DIB DLSR: Software Lock status Position 
.PP
Definition at line \fB1221\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Pos   1U"
DIB DLSR: Software Lock status Position 
.PP
Definition at line \fB2044\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Pos   1U"
DIB DLSR: Software Lock status Position 
.PP
Definition at line \fB1296\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Pos   1U"
DIB DLSR: Software Lock status Position 
.PP
Definition at line \fB2119\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Pos   1U"
DIB DLSR: Software Lock status Position 
.PP
Definition at line \fB2119\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Pos   1U"
DIB DLSR: Software Lock status Position 
.PP
Definition at line \fB3498\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Pos   1U"
DIB DLSR: Software Lock status Position 
.PP
Definition at line \fB3403\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define DIB_DLSR_SLK_Pos   1U"
DIB DLSR: Software Lock status Position 
.PP
Definition at line \fB2046\fP of file \fBcore_starmc1\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
