.TH "CMSIS_core_register" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_core_register \- Defines and Type Definitions
.PP
 \- Type definitions and defines for Cortex-M processor based devices\&.  

.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "\fBStatus and Control Registers\fP"
.br
.RI "Core Register type definitions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type definitions and defines for Cortex-M processor based devices\&. 

Type definitions and defines for STAR-MC1 processor based devices\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
