.TH "CMSIS_core_bitfield" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_core_bitfield \- Core register bit field macros
.PP
 \- Macros for use with bit field definitions (xxx_Pos, xxx_Msk)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "\fBCore Definitions\fP"
.br
.RI "Definitions for base addresses, unions, and structures\&. "
.in -1c
.in +1c
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.ti -1c
.RI "#define \fB_VAL2FLD\fP(field,  value)"
.br
.RI "Mask and shift a bit field value for use in a register bit range\&. "
.ti -1c
.RI "#define \fB_FLD2VAL\fP(field,  value)"
.br
.RI "Mask and shift a register value to extract a bit filed value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Macros for use with bit field definitions (xxx_Pos, xxx_Msk)\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB3081\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB1288\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB2111\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB521\fP of file \fBcore_cm0\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB635\fP of file \fBcore_cm0plus\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB547\fP of file \fBcore_cm1\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB1363\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB1367\fP of file \fBcore_cm3\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB2186\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB2186\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB1537\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB3577\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB1764\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB3482\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB649\fP of file \fBcore_sc000\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB1350\fP of file \fBcore_sc300\&.h\fP\&.
.SS "#define _FLD2VAL( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) & field ## _Msk) >> field ## _Pos)
.PP
.fi

.PP
Mask and shift a register value to extract a bit filed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of register\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted bit field value\&. 
.RE
.PP

.PP
Definition at line \fB2113\fP of file \fBcore_starmc1\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB3073\fP of file \fBcore_armv81mml\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB1280\fP of file \fBcore_armv8mbl\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB2103\fP of file \fBcore_armv8mml\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB513\fP of file \fBcore_cm0\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB627\fP of file \fBcore_cm0plus\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB539\fP of file \fBcore_cm1\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB1355\fP of file \fBcore_cm23\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB1359\fP of file \fBcore_cm3\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB2178\fP of file \fBcore_cm33\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB2178\fP of file \fBcore_cm35p\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB1529\fP of file \fBcore_cm4\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB3569\fP of file \fBcore_cm55\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB1756\fP of file \fBcore_cm7\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB3474\fP of file \fBcore_cm85\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB641\fP of file \fBcore_sc000\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB1342\fP of file \fBcore_sc300\&.h\fP\&.
.SS "#define _VAL2FLD( field,  value)"
\fBValue:\fP
.nf
(((uint32_t)(value) << field ## _Pos) & field ## _Msk)
.PP
.fi

.PP
Mask and shift a bit field value for use in a register bit range\&. 
.PP
\fBParameters\fP
.RS 4
\fIfield\fP Name of the register bit field\&. 
.br
\fIvalue\fP Value of the bit field\&. This parameter is interpreted as an uint32_t type\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masked and shifted value\&. 
.RE
.PP

.PP
Definition at line \fB2105\fP of file \fBcore_starmc1\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
