.TH "CMSIS_Core_DIBFunctions" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_DIBFunctions \- Debug Identification Functions
.PP
 \- Functions that access the Debug Identification Block\&.  

.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "\fBSysTick Functions\fP"
.br
.RI "Functions that configure the System\&. "
.in -1c
.in +1c
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBDIB_GetAuthStatus\fP (void)"
.br
.RI "Get Debug Authentication Status Register\&. "
.in -1c
.SH "Detailed Description"
.PP 
Functions that access the Debug Identification Block\&. 


.SH "Function Documentation"
.PP 
.SS "__STATIC_INLINE uint32_t DIB_GetAuthStatus (void )"

.PP
Get Debug Authentication Status Register\&. Reads Debug Authentication Status register\&. 
.PP
\fBReturns\fP
.RS 4
Debug Authentication Status Register\&. 
.RE
.PP

.PP
Definition at line \fB4047\fP of file \fBcore_armv81mml\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
