.TH "CMSIS_Core_FpuFunctions" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_FpuFunctions \- FPU Functions
.PP
 \- Function that provides FPU type\&.  

.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "\fBMVE Functions\fP"
.br
.RI "Function that provides MVE type\&. "
.in -1c
.in +1c
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBSCB_GetFPUType\fP (void)"
.br
.RI "get FPU type "
.in -1c
.SH "Detailed Description"
.PP 
Function that provides FPU type\&. 


.SH "Function Documentation"
.PP 
.SS "__STATIC_INLINE uint32_t SCB_GetFPUType (void )"

.PP
get FPU type returns the FPU type 
.PP
\fBReturns\fP
.RS 4

.IP "\(bu" 2
\fB0\fP: No FPU
.IP "\(bu" 2
\fB1\fP: Single precision FPU
.IP "\(bu" 2
\fB2\fP: Double + Single precision FPU 
.PP
.RE
.PP

.PP
Definition at line \fB3862\fP of file \fBcore_armv81mml\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
