.TH "Configuration_section_for_CMSIS" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration_section_for_CMSIS \- Configuration_section_for_CMSIS
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CM4_REV\fP   0x0001U"
.br
.RI "Configuration of the Cortex-M4 Processor and Core Peripherals\&. "
.ti -1c
.RI "#define \fB__MPU_PRESENT\fP   1U"
.br
.ti -1c
.RI "#define \fB__NVIC_PRIO_BITS\fP   4U"
.br
.ti -1c
.RI "#define \fB__Vendor_SysTickConfig\fP   0U"
.br
.ti -1c
.RI "#define \fB__FPU_PRESENT\fP   1U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __CM4_REV   0x0001U"

.PP
Configuration of the Cortex-M4 Processor and Core Peripherals\&. Core revision r0p1 
.br
 
.PP
Definition at line \fB47\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define __FPU_PRESENT   1U"
FPU present 
.br
 
.PP
Definition at line \fB51\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define __MPU_PRESENT   1U"
STM32F4XX provides an MPU 
.br
 
.PP
Definition at line \fB48\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define __NVIC_PRIO_BITS   4U"
STM32F4XX uses 4 Bits for the Priority Levels 
.PP
Definition at line \fB49\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define __Vendor_SysTickConfig   0U"
Set to 1 if different SysTick Config is used 
.br
 
.PP
Definition at line \fB50\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
