.TH "CoreDebug_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreDebug_Type \- Structure type to access the Core Debug Register (CoreDebug)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_armv81mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__IOM uint32_t \fBDHCSR\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBDCRSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDCRDR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDEMCR\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBDSCEMCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDAUTHCTRL\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDSCSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [1U]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Core Debug Register (CoreDebug)\&. 


.PP
\fBDeprecated\fP
.RS 4
Structure type to access the Core Debug Register (CoreDebug)\&. 
.RE
.PP

.PP
\fBDeprecated\fP
.RS 4
Structure type to access the Core Debug Register (CoreDebug)\&. 
.RE
.PP

.PP
\fBDeprecated\fP
.RS 4
Structure type to access the Core Debug Register (CoreDebug)\&. 
.RE
.PP

.PP
\fBDeprecated\fP
.RS 4
Structure type to access the Core Debug Register (CoreDebug)\&. 
.RE
.PP

.PP
\fBDeprecated\fP
.RS 4
Structure type to access the Core Debug Register (CoreDebug)\&. 
.RE
.PP

.PP
\fBDeprecated\fP
.RS 4
Structure type to access the Core Debug Register (CoreDebug)\&. 
.RE
.PP

.PP
\fBDeprecated\fP
.RS 4
Structure type to access the Core Debug Register (CoreDebug)\&. 
.RE
.PP

.PP
\fBDeprecated\fP
.RS 4
Structure type to access the Core Debug Register (CoreDebug)\&. 
.RE
.PP

.PP
Definition at line \fB2623\fP of file \fBcore_armv81mml\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
