.TH "CRC_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC_TypeDef \- CRC calculation unit\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBIDR\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CRC calculation unit\&. 
.PP
Definition at line \fB279\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t CR"
CRC Control register, Address offset: 0x08 
.PP
Definition at line \fB285\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DR"
CRC Data register, Address offset: 0x00 
.PP
Definition at line \fB281\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint8_t IDR"
CRC Independent data register, Address offset: 0x04 
.PP
Definition at line \fB282\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint8_t RESERVED0"
Reserved, 0x05 
.br
 
.PP
Definition at line \fB283\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint16_t RESERVED1"
Reserved, 0x06 
.br
 
.PP
Definition at line \fB284\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
