.TH "DBGMCU_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DBGMCU_TypeDef \- Debug MCU\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIDCODE\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB1FZ\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB2FZ\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Debug MCU\&. 
.PP
Definition at line \fB314\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t APB1FZ"
Debug MCU APB1 freeze register, Address offset: 0x08 
.PP
Definition at line \fB318\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t APB2FZ"
Debug MCU APB2 freeze register, Address offset: 0x0C 
.PP
Definition at line \fB319\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CR"
Debug MCU configuration register, Address offset: 0x04 
.PP
Definition at line \fB317\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t IDCODE"
MCU device ID code, Address offset: 0x00 
.PP
Definition at line \fB316\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
