.TH "deprecated" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.PP


.PP
.IP "\fBGlobal \fB__ARMv81MML_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__ARMv81MML_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__ARMv81MML_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__ARMv8MBL_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__ARMv8MBL_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__ARMv8MBL_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__ARMv8MML_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__ARMv8MML_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__ARMv8MML_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__CM0_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__CM0_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__CM0_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__CM0PLUS_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__CM0PLUS_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__CM0PLUS_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__CM1_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__CM1_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__CM1_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__CM23_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__CM23_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__CM23_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__CM33_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__CM33_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__CM33_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__CM35P_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__CM35P_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__CM35P_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__CM3_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__CM3_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__CM3_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__CM4_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__CM4_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__CM4_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__CM55_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__CM55_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__CM55_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__CM7_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__CM7_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__CM7_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__SC000_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__SC000_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__SC000_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fB__SC300_CMSIS_VERSION\fP 
.IP "" 1c
CMSIS HAL version number  

.PP
.IP "\fBGlobal \fB__SC300_CMSIS_VERSION_MAIN\fP 
.IP "" 1c
[31:16] CMSIS HAL main version  

.PP
.IP "\fBGlobal \fB__SC300_CMSIS_VERSION_SUB\fP 
.IP "" 1c
[15:0] CMSIS HAL sub version  

.PP
.IP "\fBGlobal \fBCoreDebug\fP 
.IP "" 1c
Core Debug configuration struct 

.PP
Core Debug configuration struct 

.PP
Core Debug configuration struct 

.PP
Core Debug configuration struct 

.PP
Core Debug configuration struct 

.PP
Core Debug configuration struct 

.PP
Core Debug configuration struct 

.PP
Core Debug configuration struct  

.PP
.IP "\fBGlobal \fBCoreDebug_BASE\fP 
.IP "" 1c
Core Debug Base Address 

.PP
Core Debug Base Address 

.PP
Core Debug Base Address 

.PP
Core Debug Base Address 

.PP
Core Debug Base Address 

.PP
Core Debug Base Address 

.PP
Core Debug Base Address 

.PP
Core Debug Base Address  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_FSDMA_Msk\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: FSDMA, Mask 

.PP
CoreDebug DAUTHCTRL: FSDMA, Mask 

.PP
CoreDebug DAUTHCTRL: FSDMA, Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_FSDMA_Pos\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: FSDMA, Position 

.PP
CoreDebug DAUTHCTRL: FSDMA, Position 

.PP
CoreDebug DAUTHCTRL: FSDMA, Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_INTSPIDEN_Msk\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: INTSPIDEN Mask 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Mask 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Mask 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Mask 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Mask 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Mask 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Mask 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_INTSPIDEN_Pos\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: INTSPIDEN Position 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Position 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Position 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Position 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Position 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Position 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Position 

.PP
CoreDebug DAUTHCTRL: INTSPIDEN Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_INTSPNIDEN_Msk\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: INTSPNIDEN, Mask 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Mask 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Mask 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Mask 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Mask 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Mask 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Mask 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_INTSPNIDEN_Pos\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: INTSPNIDEN, Position 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Position 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Position 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Position 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Position 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Position 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Position 

.PP
CoreDebug DAUTHCTRL: INTSPNIDEN, Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_SPIDENSEL_Msk\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: SPIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_SPIDENSEL_Pos\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: SPIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPIDENSEL Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_SPNIDENSEL_Msk\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: SPNIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Mask 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_SPNIDENSEL_Pos\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: SPNIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Position 

.PP
CoreDebug DAUTHCTRL: SPNIDENSEL Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_UIDAPEN_Msk\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: UIDAPEN, Mask 

.PP
CoreDebug DAUTHCTRL: UIDAPEN, Mask 

.PP
CoreDebug DAUTHCTRL: UIDAPEN, Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_UIDAPEN_Pos\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: UIDAPEN, Position 

.PP
CoreDebug DAUTHCTRL: UIDAPEN, Position 

.PP
CoreDebug DAUTHCTRL: UIDAPEN, Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_UIDEN_Msk\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: UIDEN, Mask 

.PP
CoreDebug DAUTHCTRL: UIDEN, Mask 

.PP
CoreDebug DAUTHCTRL: UIDEN, Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DAUTHCTRL_UIDEN_Pos\fP 
.IP "" 1c
CoreDebug DAUTHCTRL: UIDEN, Position 

.PP
CoreDebug DAUTHCTRL: UIDEN, Position 

.PP
CoreDebug DAUTHCTRL: UIDEN, Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DCRSR_REGSEL_Msk\fP 
.IP "" 1c
CoreDebug DCRSR: REGSEL Mask 

.PP
CoreDebug DCRSR: REGSEL Mask 

.PP
CoreDebug DCRSR: REGSEL Mask 

.PP
CoreDebug DCRSR: REGSEL Mask 

.PP
CoreDebug DCRSR: REGSEL Mask 

.PP
CoreDebug DCRSR: REGSEL Mask 

.PP
CoreDebug DCRSR: REGSEL Mask 

.PP
CoreDebug DCRSR: REGSEL Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DCRSR_REGSEL_Pos\fP 
.IP "" 1c
CoreDebug DCRSR: REGSEL Position 

.PP
CoreDebug DCRSR: REGSEL Position 

.PP
CoreDebug DCRSR: REGSEL Position 

.PP
CoreDebug DCRSR: REGSEL Position 

.PP
CoreDebug DCRSR: REGSEL Position 

.PP
CoreDebug DCRSR: REGSEL Position 

.PP
CoreDebug DCRSR: REGSEL Position 

.PP
CoreDebug DCRSR: REGSEL Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DCRSR_REGWnR_Msk\fP 
.IP "" 1c
CoreDebug DCRSR: REGWnR Mask 

.PP
CoreDebug DCRSR: REGWnR Mask 

.PP
CoreDebug DCRSR: REGWnR Mask 

.PP
CoreDebug DCRSR: REGWnR Mask 

.PP
CoreDebug DCRSR: REGWnR Mask 

.PP
CoreDebug DCRSR: REGWnR Mask 

.PP
CoreDebug DCRSR: REGWnR Mask 

.PP
CoreDebug DCRSR: REGWnR Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DCRSR_REGWnR_Pos\fP 
.IP "" 1c
CoreDebug DCRSR: REGWnR Position 

.PP
CoreDebug DCRSR: REGWnR Position 

.PP
CoreDebug DCRSR: REGWnR Position 

.PP
CoreDebug DCRSR: REGWnR Position 

.PP
CoreDebug DCRSR: REGWnR Position 

.PP
CoreDebug DCRSR: REGWnR Position 

.PP
CoreDebug DCRSR: REGWnR Position 

.PP
CoreDebug DCRSR: REGWnR Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_DWTENA_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: DWTENA Mask 

.PP
CoreDebug DEMCR: DWTENA Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_DWTENA_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: DWTENA Position 

.PP
CoreDebug DEMCR: DWTENA Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_MON_EN_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: MON_EN Mask 

.PP
CoreDebug DEMCR: MON_EN Mask 

.PP
CoreDebug DEMCR: MON_EN Mask 

.PP
CoreDebug DEMCR: MON_EN Mask 

.PP
CoreDebug DEMCR: MON_EN Mask 

.PP
CoreDebug DEMCR: MON_EN Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_MON_EN_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: MON_EN Position 

.PP
CoreDebug DEMCR: MON_EN Position 

.PP
CoreDebug DEMCR: MON_EN Position 

.PP
CoreDebug DEMCR: MON_EN Position 

.PP
CoreDebug DEMCR: MON_EN Position 

.PP
CoreDebug DEMCR: MON_EN Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_MON_PEND_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: MON_PEND Mask 

.PP
CoreDebug DEMCR: MON_PEND Mask 

.PP
CoreDebug DEMCR: MON_PEND Mask 

.PP
CoreDebug DEMCR: MON_PEND Mask 

.PP
CoreDebug DEMCR: MON_PEND Mask 

.PP
CoreDebug DEMCR: MON_PEND Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_MON_PEND_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: MON_PEND Position 

.PP
CoreDebug DEMCR: MON_PEND Position 

.PP
CoreDebug DEMCR: MON_PEND Position 

.PP
CoreDebug DEMCR: MON_PEND Position 

.PP
CoreDebug DEMCR: MON_PEND Position 

.PP
CoreDebug DEMCR: MON_PEND Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_MON_REQ_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: MON_REQ Mask 

.PP
CoreDebug DEMCR: MON_REQ Mask 

.PP
CoreDebug DEMCR: MON_REQ Mask 

.PP
CoreDebug DEMCR: MON_REQ Mask 

.PP
CoreDebug DEMCR: MON_REQ Mask 

.PP
CoreDebug DEMCR: MON_REQ Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_MON_REQ_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: MON_REQ Position 

.PP
CoreDebug DEMCR: MON_REQ Position 

.PP
CoreDebug DEMCR: MON_REQ Position 

.PP
CoreDebug DEMCR: MON_REQ Position 

.PP
CoreDebug DEMCR: MON_REQ Position 

.PP
CoreDebug DEMCR: MON_REQ Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_MON_STEP_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: MON_STEP Mask 

.PP
CoreDebug DEMCR: MON_STEP Mask 

.PP
CoreDebug DEMCR: MON_STEP Mask 

.PP
CoreDebug DEMCR: MON_STEP Mask 

.PP
CoreDebug DEMCR: MON_STEP Mask 

.PP
CoreDebug DEMCR: MON_STEP Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_MON_STEP_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: MON_STEP Position 

.PP
CoreDebug DEMCR: MON_STEP Position 

.PP
CoreDebug DEMCR: MON_STEP Position 

.PP
CoreDebug DEMCR: MON_STEP Position 

.PP
CoreDebug DEMCR: MON_STEP Position 

.PP
CoreDebug DEMCR: MON_STEP Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_TRCENA_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: TRCENA Mask 

.PP
CoreDebug DEMCR: TRCENA Mask 

.PP
CoreDebug DEMCR: TRCENA Mask 

.PP
CoreDebug DEMCR: TRCENA Mask 

.PP
CoreDebug DEMCR: TRCENA Mask 

.PP
CoreDebug DEMCR: TRCENA Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_TRCENA_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: TRCENA Position 

.PP
CoreDebug DEMCR: TRCENA Position 

.PP
CoreDebug DEMCR: TRCENA Position 

.PP
CoreDebug DEMCR: TRCENA Position 

.PP
CoreDebug DEMCR: TRCENA Position 

.PP
CoreDebug DEMCR: TRCENA Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_BUSERR_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: VC_BUSERR Mask 

.PP
CoreDebug DEMCR: VC_BUSERR Mask 

.PP
CoreDebug DEMCR: VC_BUSERR Mask 

.PP
CoreDebug DEMCR: VC_BUSERR Mask 

.PP
CoreDebug DEMCR: VC_BUSERR Mask 

.PP
CoreDebug DEMCR: VC_BUSERR Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_BUSERR_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: VC_BUSERR Position 

.PP
CoreDebug DEMCR: VC_BUSERR Position 

.PP
CoreDebug DEMCR: VC_BUSERR Position 

.PP
CoreDebug DEMCR: VC_BUSERR Position 

.PP
CoreDebug DEMCR: VC_BUSERR Position 

.PP
CoreDebug DEMCR: VC_BUSERR Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_CHKERR_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: VC_CHKERR Mask 

.PP
CoreDebug DEMCR: VC_CHKERR Mask 

.PP
CoreDebug DEMCR: VC_CHKERR Mask 

.PP
CoreDebug DEMCR: VC_CHKERR Mask 

.PP
CoreDebug DEMCR: VC_CHKERR Mask 

.PP
CoreDebug DEMCR: VC_CHKERR Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_CHKERR_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: VC_CHKERR Position 

.PP
CoreDebug DEMCR: VC_CHKERR Position 

.PP
CoreDebug DEMCR: VC_CHKERR Position 

.PP
CoreDebug DEMCR: VC_CHKERR Position 

.PP
CoreDebug DEMCR: VC_CHKERR Position 

.PP
CoreDebug DEMCR: VC_CHKERR Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_CORERESET_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: VC_CORERESET Mask 

.PP
CoreDebug DEMCR: VC_CORERESET Mask 

.PP
CoreDebug DEMCR: VC_CORERESET Mask 

.PP
CoreDebug DEMCR: VC_CORERESET Mask 

.PP
CoreDebug DEMCR: VC_CORERESET Mask 

.PP
CoreDebug DEMCR: VC_CORERESET Mask 

.PP
CoreDebug DEMCR: VC_CORERESET Mask 

.PP
CoreDebug DEMCR: VC_CORERESET Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_CORERESET_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: VC_CORERESET Position 

.PP
CoreDebug DEMCR: VC_CORERESET Position 

.PP
CoreDebug DEMCR: VC_CORERESET Position 

.PP
CoreDebug DEMCR: VC_CORERESET Position 

.PP
CoreDebug DEMCR: VC_CORERESET Position 

.PP
CoreDebug DEMCR: VC_CORERESET Position 

.PP
CoreDebug DEMCR: VC_CORERESET Position 

.PP
CoreDebug DEMCR: VC_CORERESET Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_HARDERR_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: VC_HARDERR Mask 

.PP
CoreDebug DEMCR: VC_HARDERR Mask 

.PP
CoreDebug DEMCR: VC_HARDERR Mask 

.PP
CoreDebug DEMCR: VC_HARDERR Mask 

.PP
CoreDebug DEMCR: VC_HARDERR Mask 

.PP
CoreDebug DEMCR: VC_HARDERR Mask 

.PP
CoreDebug DEMCR: VC_HARDERR Mask 

.PP
CoreDebug DEMCR: VC_HARDERR Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_HARDERR_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: VC_HARDERR Position 

.PP
CoreDebug DEMCR: VC_HARDERR Position 

.PP
CoreDebug DEMCR: VC_HARDERR Position 

.PP
CoreDebug DEMCR: VC_HARDERR Position 

.PP
CoreDebug DEMCR: VC_HARDERR Position 

.PP
CoreDebug DEMCR: VC_HARDERR Position 

.PP
CoreDebug DEMCR: VC_HARDERR Position 

.PP
CoreDebug DEMCR: VC_HARDERR Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_INTERR_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: VC_INTERR Mask 

.PP
CoreDebug DEMCR: VC_INTERR Mask 

.PP
CoreDebug DEMCR: VC_INTERR Mask 

.PP
CoreDebug DEMCR: VC_INTERR Mask 

.PP
CoreDebug DEMCR: VC_INTERR Mask 

.PP
CoreDebug DEMCR: VC_INTERR Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_INTERR_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: VC_INTERR Position 

.PP
CoreDebug DEMCR: VC_INTERR Position 

.PP
CoreDebug DEMCR: VC_INTERR Position 

.PP
CoreDebug DEMCR: VC_INTERR Position 

.PP
CoreDebug DEMCR: VC_INTERR Position 

.PP
CoreDebug DEMCR: VC_INTERR Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_MMERR_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: VC_MMERR Mask 

.PP
CoreDebug DEMCR: VC_MMERR Mask 

.PP
CoreDebug DEMCR: VC_MMERR Mask 

.PP
CoreDebug DEMCR: VC_MMERR Mask 

.PP
CoreDebug DEMCR: VC_MMERR Mask 

.PP
CoreDebug DEMCR: VC_MMERR Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_MMERR_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: VC_MMERR Position 

.PP
CoreDebug DEMCR: VC_MMERR Position 

.PP
CoreDebug DEMCR: VC_MMERR Position 

.PP
CoreDebug DEMCR: VC_MMERR Position 

.PP
CoreDebug DEMCR: VC_MMERR Position 

.PP
CoreDebug DEMCR: VC_MMERR Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_NOCPERR_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: VC_NOCPERR Mask 

.PP
CoreDebug DEMCR: VC_NOCPERR Mask 

.PP
CoreDebug DEMCR: VC_NOCPERR Mask 

.PP
CoreDebug DEMCR: VC_NOCPERR Mask 

.PP
CoreDebug DEMCR: VC_NOCPERR Mask 

.PP
CoreDebug DEMCR: VC_NOCPERR Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_NOCPERR_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: VC_NOCPERR Position 

.PP
CoreDebug DEMCR: VC_NOCPERR Position 

.PP
CoreDebug DEMCR: VC_NOCPERR Position 

.PP
CoreDebug DEMCR: VC_NOCPERR Position 

.PP
CoreDebug DEMCR: VC_NOCPERR Position 

.PP
CoreDebug DEMCR: VC_NOCPERR Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_STATERR_Msk\fP 
.IP "" 1c
CoreDebug DEMCR: VC_STATERR Mask 

.PP
CoreDebug DEMCR: VC_STATERR Mask 

.PP
CoreDebug DEMCR: VC_STATERR Mask 

.PP
CoreDebug DEMCR: VC_STATERR Mask 

.PP
CoreDebug DEMCR: VC_STATERR Mask 

.PP
CoreDebug DEMCR: VC_STATERR Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DEMCR_VC_STATERR_Pos\fP 
.IP "" 1c
CoreDebug DEMCR: VC_STATERR Position 

.PP
CoreDebug DEMCR: VC_STATERR Position 

.PP
CoreDebug DEMCR: VC_STATERR Position 

.PP
CoreDebug DEMCR: VC_STATERR Position 

.PP
CoreDebug DEMCR: VC_STATERR Position 

.PP
CoreDebug DEMCR: VC_STATERR Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_DEBUGEN_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: C_DEBUGEN Mask 

.PP
CoreDebug DHCSR: C_DEBUGEN Mask 

.PP
CoreDebug DHCSR: C_DEBUGEN Mask 

.PP
CoreDebug DHCSR: C_DEBUGEN Mask 

.PP
CoreDebug DHCSR: C_DEBUGEN Mask 

.PP
CoreDebug DHCSR: C_DEBUGEN Mask 

.PP
CoreDebug DHCSR: C_DEBUGEN Mask 

.PP
CoreDebug DHCSR: C_DEBUGEN Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_DEBUGEN_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: C_DEBUGEN Position 

.PP
CoreDebug DHCSR: C_DEBUGEN Position 

.PP
CoreDebug DHCSR: C_DEBUGEN Position 

.PP
CoreDebug DHCSR: C_DEBUGEN Position 

.PP
CoreDebug DHCSR: C_DEBUGEN Position 

.PP
CoreDebug DHCSR: C_DEBUGEN Position 

.PP
CoreDebug DHCSR: C_DEBUGEN Position 

.PP
CoreDebug DHCSR: C_DEBUGEN Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_HALT_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: C_HALT Mask 

.PP
CoreDebug DHCSR: C_HALT Mask 

.PP
CoreDebug DHCSR: C_HALT Mask 

.PP
CoreDebug DHCSR: C_HALT Mask 

.PP
CoreDebug DHCSR: C_HALT Mask 

.PP
CoreDebug DHCSR: C_HALT Mask 

.PP
CoreDebug DHCSR: C_HALT Mask 

.PP
CoreDebug DHCSR: C_HALT Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_HALT_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: C_HALT Position 

.PP
CoreDebug DHCSR: C_HALT Position 

.PP
CoreDebug DHCSR: C_HALT Position 

.PP
CoreDebug DHCSR: C_HALT Position 

.PP
CoreDebug DHCSR: C_HALT Position 

.PP
CoreDebug DHCSR: C_HALT Position 

.PP
CoreDebug DHCSR: C_HALT Position 

.PP
CoreDebug DHCSR: C_HALT Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_MASKINTS_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: C_MASKINTS Mask 

.PP
CoreDebug DHCSR: C_MASKINTS Mask 

.PP
CoreDebug DHCSR: C_MASKINTS Mask 

.PP
CoreDebug DHCSR: C_MASKINTS Mask 

.PP
CoreDebug DHCSR: C_MASKINTS Mask 

.PP
CoreDebug DHCSR: C_MASKINTS Mask 

.PP
CoreDebug DHCSR: C_MASKINTS Mask 

.PP
CoreDebug DHCSR: C_MASKINTS Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_MASKINTS_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: C_MASKINTS Position 

.PP
CoreDebug DHCSR: C_MASKINTS Position 

.PP
CoreDebug DHCSR: C_MASKINTS Position 

.PP
CoreDebug DHCSR: C_MASKINTS Position 

.PP
CoreDebug DHCSR: C_MASKINTS Position 

.PP
CoreDebug DHCSR: C_MASKINTS Position 

.PP
CoreDebug DHCSR: C_MASKINTS Position 

.PP
CoreDebug DHCSR: C_MASKINTS Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_PMOV_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: C_PMOV Mask 

.PP
CoreDebug DHCSR: C_PMOV Mask 

.PP
CoreDebug DHCSR: C_PMOV Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_PMOV_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: C_PMOV Position 

.PP
CoreDebug DHCSR: C_PMOV Position 

.PP
CoreDebug DHCSR: C_PMOV Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_SNAPSTALL_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: C_SNAPSTALL Mask 

.PP
CoreDebug DHCSR: C_SNAPSTALL Mask 

.PP
CoreDebug DHCSR: C_SNAPSTALL Mask 

.PP
CoreDebug DHCSR: C_SNAPSTALL Mask 

.PP
CoreDebug DHCSR: C_SNAPSTALL Mask 

.PP
CoreDebug DHCSR: C_SNAPSTALL Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_SNAPSTALL_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: C_SNAPSTALL Position 

.PP
CoreDebug DHCSR: C_SNAPSTALL Position 

.PP
CoreDebug DHCSR: C_SNAPSTALL Position 

.PP
CoreDebug DHCSR: C_SNAPSTALL Position 

.PP
CoreDebug DHCSR: C_SNAPSTALL Position 

.PP
CoreDebug DHCSR: C_SNAPSTALL Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_STEP_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: C_STEP Mask 

.PP
CoreDebug DHCSR: C_STEP Mask 

.PP
CoreDebug DHCSR: C_STEP Mask 

.PP
CoreDebug DHCSR: C_STEP Mask 

.PP
CoreDebug DHCSR: C_STEP Mask 

.PP
CoreDebug DHCSR: C_STEP Mask 

.PP
CoreDebug DHCSR: C_STEP Mask 

.PP
CoreDebug DHCSR: C_STEP Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_C_STEP_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: C_STEP Position 

.PP
CoreDebug DHCSR: C_STEP Position 

.PP
CoreDebug DHCSR: C_STEP Position 

.PP
CoreDebug DHCSR: C_STEP Position 

.PP
CoreDebug DHCSR: C_STEP Position 

.PP
CoreDebug DHCSR: C_STEP Position 

.PP
CoreDebug DHCSR: C_STEP Position 

.PP
CoreDebug DHCSR: C_STEP Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_DBGKEY_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: DBGKEY Mask 

.PP
CoreDebug DHCSR: DBGKEY Mask 

.PP
CoreDebug DHCSR: DBGKEY Mask 

.PP
CoreDebug DHCSR: DBGKEY Mask 

.PP
CoreDebug DHCSR: DBGKEY Mask 

.PP
CoreDebug DHCSR: DBGKEY Mask 

.PP
CoreDebug DHCSR: DBGKEY Mask 

.PP
CoreDebug DHCSR: DBGKEY Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_DBGKEY_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: DBGKEY Position 

.PP
CoreDebug DHCSR: DBGKEY Position 

.PP
CoreDebug DHCSR: DBGKEY Position 

.PP
CoreDebug DHCSR: DBGKEY Position 

.PP
CoreDebug DHCSR: DBGKEY Position 

.PP
CoreDebug DHCSR: DBGKEY Position 

.PP
CoreDebug DHCSR: DBGKEY Position 

.PP
CoreDebug DHCSR: DBGKEY Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_FPD_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_FPD Mask 

.PP
CoreDebug DHCSR: S_FPD Mask 

.PP
CoreDebug DHCSR: S_FPD Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_FPD_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_FPD Position 

.PP
CoreDebug DHCSR: S_FPD Position 

.PP
CoreDebug DHCSR: S_FPD Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_HALT_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_HALT Mask 

.PP
CoreDebug DHCSR: S_HALT Mask 

.PP
CoreDebug DHCSR: S_HALT Mask 

.PP
CoreDebug DHCSR: S_HALT Mask 

.PP
CoreDebug DHCSR: S_HALT Mask 

.PP
CoreDebug DHCSR: S_HALT Mask 

.PP
CoreDebug DHCSR: S_HALT Mask 

.PP
CoreDebug DHCSR: S_HALT Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_HALT_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_HALT Position 

.PP
CoreDebug DHCSR: S_HALT Position 

.PP
CoreDebug DHCSR: S_HALT Position 

.PP
CoreDebug DHCSR: S_HALT Position 

.PP
CoreDebug DHCSR: S_HALT Position 

.PP
CoreDebug DHCSR: S_HALT Position 

.PP
CoreDebug DHCSR: S_HALT Position 

.PP
CoreDebug DHCSR: S_HALT Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_LOCKUP_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_LOCKUP Mask 

.PP
CoreDebug DHCSR: S_LOCKUP Mask 

.PP
CoreDebug DHCSR: S_LOCKUP Mask 

.PP
CoreDebug DHCSR: S_LOCKUP Mask 

.PP
CoreDebug DHCSR: S_LOCKUP Mask 

.PP
CoreDebug DHCSR: S_LOCKUP Mask 

.PP
CoreDebug DHCSR: S_LOCKUP Mask 

.PP
CoreDebug DHCSR: S_LOCKUP Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_LOCKUP_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_LOCKUP Position 

.PP
CoreDebug DHCSR: S_LOCKUP Position 

.PP
CoreDebug DHCSR: S_LOCKUP Position 

.PP
CoreDebug DHCSR: S_LOCKUP Position 

.PP
CoreDebug DHCSR: S_LOCKUP Position 

.PP
CoreDebug DHCSR: S_LOCKUP Position 

.PP
CoreDebug DHCSR: S_LOCKUP Position 

.PP
CoreDebug DHCSR: S_LOCKUP Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_NSUIDE_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_NSUIDE Mask 

.PP
CoreDebug DHCSR: S_NSUIDE Mask 

.PP
CoreDebug DHCSR: S_NSUIDE Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_NSUIDE_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_NSUIDE Position 

.PP
CoreDebug DHCSR: S_NSUIDE Position 

.PP
CoreDebug DHCSR: S_NSUIDE Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_REGRDY_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_REGRDY Mask 

.PP
CoreDebug DHCSR: S_REGRDY Mask 

.PP
CoreDebug DHCSR: S_REGRDY Mask 

.PP
CoreDebug DHCSR: S_REGRDY Mask 

.PP
CoreDebug DHCSR: S_REGRDY Mask 

.PP
CoreDebug DHCSR: S_REGRDY Mask 

.PP
CoreDebug DHCSR: S_REGRDY Mask 

.PP
CoreDebug DHCSR: S_REGRDY Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_REGRDY_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_REGRDY Position 

.PP
CoreDebug DHCSR: S_REGRDY Position 

.PP
CoreDebug DHCSR: S_REGRDY Position 

.PP
CoreDebug DHCSR: S_REGRDY Position 

.PP
CoreDebug DHCSR: S_REGRDY Position 

.PP
CoreDebug DHCSR: S_REGRDY Position 

.PP
CoreDebug DHCSR: S_REGRDY Position 

.PP
CoreDebug DHCSR: S_REGRDY Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_RESET_ST_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_RESET_ST Mask 

.PP
CoreDebug DHCSR: S_RESET_ST Mask 

.PP
CoreDebug DHCSR: S_RESET_ST Mask 

.PP
CoreDebug DHCSR: S_RESET_ST Mask 

.PP
CoreDebug DHCSR: S_RESET_ST Mask 

.PP
CoreDebug DHCSR: S_RESET_ST Mask 

.PP
CoreDebug DHCSR: S_RESET_ST Mask 

.PP
CoreDebug DHCSR: S_RESET_ST Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_RESET_ST_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_RESET_ST Position 

.PP
CoreDebug DHCSR: S_RESET_ST Position 

.PP
CoreDebug DHCSR: S_RESET_ST Position 

.PP
CoreDebug DHCSR: S_RESET_ST Position 

.PP
CoreDebug DHCSR: S_RESET_ST Position 

.PP
CoreDebug DHCSR: S_RESET_ST Position 

.PP
CoreDebug DHCSR: S_RESET_ST Position 

.PP
CoreDebug DHCSR: S_RESET_ST Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_RESTART_ST_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_RESTART_ST Mask 

.PP
CoreDebug DHCSR: S_RESTART_ST Mask 

.PP
CoreDebug DHCSR: S_RESTART_ST Mask 

.PP
CoreDebug DHCSR: S_RESTART_ST Mask 

.PP
CoreDebug DHCSR: S_RESTART_ST Mask 

.PP
CoreDebug DHCSR: S_RESTART_ST Mask 

.PP
CoreDebug DHCSR: S_RESTART_ST Mask 

.PP
CoreDebug DHCSR: S_RESTART_ST Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_RESTART_ST_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_RESTART_ST Position 

.PP
CoreDebug DHCSR: S_RESTART_ST Position 

.PP
CoreDebug DHCSR: S_RESTART_ST Position 

.PP
CoreDebug DHCSR: S_RESTART_ST Position 

.PP
CoreDebug DHCSR: S_RESTART_ST Position 

.PP
CoreDebug DHCSR: S_RESTART_ST Position 

.PP
CoreDebug DHCSR: S_RESTART_ST Position 

.PP
CoreDebug DHCSR: S_RESTART_ST Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_RETIRE_ST_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_RETIRE_ST Mask 

.PP
CoreDebug DHCSR: S_RETIRE_ST Mask 

.PP
CoreDebug DHCSR: S_RETIRE_ST Mask 

.PP
CoreDebug DHCSR: S_RETIRE_ST Mask 

.PP
CoreDebug DHCSR: S_RETIRE_ST Mask 

.PP
CoreDebug DHCSR: S_RETIRE_ST Mask 

.PP
CoreDebug DHCSR: S_RETIRE_ST Mask 

.PP
CoreDebug DHCSR: S_RETIRE_ST Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_RETIRE_ST_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_RETIRE_ST Position 

.PP
CoreDebug DHCSR: S_RETIRE_ST Position 

.PP
CoreDebug DHCSR: S_RETIRE_ST Position 

.PP
CoreDebug DHCSR: S_RETIRE_ST Position 

.PP
CoreDebug DHCSR: S_RETIRE_ST Position 

.PP
CoreDebug DHCSR: S_RETIRE_ST Position 

.PP
CoreDebug DHCSR: S_RETIRE_ST Position 

.PP
CoreDebug DHCSR: S_RETIRE_ST Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_SDE_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_SDE Mask 

.PP
CoreDebug DHCSR: S_SDE Mask 

.PP
CoreDebug DHCSR: S_SDE Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_SDE_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_SDE Position 

.PP
CoreDebug DHCSR: S_SDE Position 

.PP
CoreDebug DHCSR: S_SDE Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_SLEEP_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_SLEEP Mask 

.PP
CoreDebug DHCSR: S_SLEEP Mask 

.PP
CoreDebug DHCSR: S_SLEEP Mask 

.PP
CoreDebug DHCSR: S_SLEEP Mask 

.PP
CoreDebug DHCSR: S_SLEEP Mask 

.PP
CoreDebug DHCSR: S_SLEEP Mask 

.PP
CoreDebug DHCSR: S_SLEEP Mask 

.PP
CoreDebug DHCSR: S_SLEEP Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_SLEEP_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_SLEEP Position 

.PP
CoreDebug DHCSR: S_SLEEP Position 

.PP
CoreDebug DHCSR: S_SLEEP Position 

.PP
CoreDebug DHCSR: S_SLEEP Position 

.PP
CoreDebug DHCSR: S_SLEEP Position 

.PP
CoreDebug DHCSR: S_SLEEP Position 

.PP
CoreDebug DHCSR: S_SLEEP Position 

.PP
CoreDebug DHCSR: S_SLEEP Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_SUIDE_Msk\fP 
.IP "" 1c
CoreDebug DHCSR: S_SUIDE Mask 

.PP
CoreDebug DHCSR: S_SUIDE Mask 

.PP
CoreDebug DHCSR: S_SUIDE Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DHCSR_S_SUIDE_Pos\fP 
.IP "" 1c
CoreDebug DHCSR: S_SUIDE Position 

.PP
CoreDebug DHCSR: S_SUIDE Position 

.PP
CoreDebug DHCSR: S_SUIDE Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCEMCR_CLR_MON_PEND_Msk\fP 
.IP "" 1c
CoreDebug DSCEMCR: CLR_MON_PEND, Mask 

.PP
CoreDebug DSCEMCR: CLR_MON_PEND, Mask 

.PP
CoreDebug DSCEMCR: CLR_MON_PEND, Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCEMCR_CLR_MON_PEND_Pos\fP 
.IP "" 1c
CoreDebug DSCEMCR: CLR_MON_PEND, Position 

.PP
CoreDebug DSCEMCR: CLR_MON_PEND, Position 

.PP
CoreDebug DSCEMCR: CLR_MON_PEND, Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCEMCR_CLR_MON_REQ_Msk\fP 
.IP "" 1c
CoreDebug DSCEMCR: CLR_MON_REQ, Mask 

.PP
CoreDebug DSCEMCR: CLR_MON_REQ, Mask 

.PP
CoreDebug DSCEMCR: CLR_MON_REQ, Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCEMCR_CLR_MON_REQ_Pos\fP 
.IP "" 1c
CoreDebug DSCEMCR: CLR_MON_REQ, Position 

.PP
CoreDebug DSCEMCR: CLR_MON_REQ, Position 

.PP
CoreDebug DSCEMCR: CLR_MON_REQ, Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCEMCR_SET_MON_PEND_Msk\fP 
.IP "" 1c
CoreDebug DSCEMCR: SET_MON_PEND, Mask 

.PP
CoreDebug DSCEMCR: SET_MON_PEND, Mask 

.PP
CoreDebug DSCEMCR: SET_MON_PEND, Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCEMCR_SET_MON_PEND_Pos\fP 
.IP "" 1c
CoreDebug DSCEMCR: SET_MON_PEND, Position 

.PP
CoreDebug DSCEMCR: SET_MON_PEND, Position 

.PP
CoreDebug DSCEMCR: SET_MON_PEND, Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCEMCR_SET_MON_REQ_Msk\fP 
.IP "" 1c
CoreDebug DSCEMCR: SET_MON_REQ, Mask 

.PP
CoreDebug DSCEMCR: SET_MON_REQ, Mask 

.PP
CoreDebug DSCEMCR: SET_MON_REQ, Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCEMCR_SET_MON_REQ_Pos\fP 
.IP "" 1c
CoreDebug DSCEMCR: SET_MON_REQ, Position 

.PP
CoreDebug DSCEMCR: SET_MON_REQ, Position 

.PP
CoreDebug DSCEMCR: SET_MON_REQ, Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCSR_CDS_Msk\fP 
.IP "" 1c
CoreDebug DSCSR: CDS Mask 

.PP
CoreDebug DSCSR: CDS Mask 

.PP
CoreDebug DSCSR: CDS Mask 

.PP
CoreDebug DSCSR: CDS Mask 

.PP
CoreDebug DSCSR: CDS Mask 

.PP
CoreDebug DSCSR: CDS Mask 

.PP
CoreDebug DSCSR: CDS Mask 

.PP
CoreDebug DSCSR: CDS Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCSR_CDS_Pos\fP 
.IP "" 1c
CoreDebug DSCSR: CDS Position 

.PP
CoreDebug DSCSR: CDS Position 

.PP
CoreDebug DSCSR: CDS Position 

.PP
CoreDebug DSCSR: CDS Position 

.PP
CoreDebug DSCSR: CDS Position 

.PP
CoreDebug DSCSR: CDS Position 

.PP
CoreDebug DSCSR: CDS Position 

.PP
CoreDebug DSCSR: CDS Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCSR_SBRSEL_Msk\fP 
.IP "" 1c
CoreDebug DSCSR: SBRSEL Mask 

.PP
CoreDebug DSCSR: SBRSEL Mask 

.PP
CoreDebug DSCSR: SBRSEL Mask 

.PP
CoreDebug DSCSR: SBRSEL Mask 

.PP
CoreDebug DSCSR: SBRSEL Mask 

.PP
CoreDebug DSCSR: SBRSEL Mask 

.PP
CoreDebug DSCSR: SBRSEL Mask 

.PP
CoreDebug DSCSR: SBRSEL Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCSR_SBRSEL_Pos\fP 
.IP "" 1c
CoreDebug DSCSR: SBRSEL Position 

.PP
CoreDebug DSCSR: SBRSEL Position 

.PP
CoreDebug DSCSR: SBRSEL Position 

.PP
CoreDebug DSCSR: SBRSEL Position 

.PP
CoreDebug DSCSR: SBRSEL Position 

.PP
CoreDebug DSCSR: SBRSEL Position 

.PP
CoreDebug DSCSR: SBRSEL Position 

.PP
CoreDebug DSCSR: SBRSEL Position  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCSR_SBRSELEN_Msk\fP 
.IP "" 1c
CoreDebug DSCSR: SBRSELEN Mask 

.PP
CoreDebug DSCSR: SBRSELEN Mask 

.PP
CoreDebug DSCSR: SBRSELEN Mask 

.PP
CoreDebug DSCSR: SBRSELEN Mask 

.PP
CoreDebug DSCSR: SBRSELEN Mask 

.PP
CoreDebug DSCSR: SBRSELEN Mask 

.PP
CoreDebug DSCSR: SBRSELEN Mask 

.PP
CoreDebug DSCSR: SBRSELEN Mask  

.PP
.IP "\fBGlobal \fBCoreDebug_DSCSR_SBRSELEN_Pos\fP 
.IP "" 1c
CoreDebug DSCSR: SBRSELEN Position 

.PP
CoreDebug DSCSR: SBRSELEN Position 

.PP
CoreDebug DSCSR: SBRSELEN Position 

.PP
CoreDebug DSCSR: SBRSELEN Position 

.PP
CoreDebug DSCSR: SBRSELEN Position 

.PP
CoreDebug DSCSR: SBRSELEN Position 

.PP
CoreDebug DSCSR: SBRSELEN Position 

.PP
CoreDebug DSCSR: SBRSELEN Position  

.PP
.IP "\fBStruct \fBCoreDebug_Type\fP 
.IP "" 1c
Structure type to access the Core Debug Register (CoreDebug)\&. 

.PP
Structure type to access the Core Debug Register (CoreDebug)\&. 

.PP
Structure type to access the Core Debug Register (CoreDebug)\&. 

.PP
Structure type to access the Core Debug Register (CoreDebug)\&. 

.PP
Structure type to access the Core Debug Register (CoreDebug)\&. 

.PP
Structure type to access the Core Debug Register (CoreDebug)\&. 

.PP
Structure type to access the Core Debug Register (CoreDebug)\&. 

.PP
Structure type to access the Core Debug Register (CoreDebug)\&.  

.PP
.IP "\fBGlobal \fBSCB_CACR_ECCEN_Msk\fP 
.IP "" 1c
SCB CACR: ECCEN Mask  

.PP
.IP "\fBGlobal \fBSCB_CACR_ECCEN_Pos\fP 
.IP "" 1c
SCB CACR: ECCEN Position 

.PP

