.TH "DMA_Stream_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Stream_TypeDef \- DMA Controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBNDTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBM0AR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBM1AR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DMA Controller\&. 
.PP
Definition at line \fB345\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t CR"
DMA stream x configuration register 
.br
 
.PP
Definition at line \fB347\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t FCR"
DMA stream x FIFO control register 
.br
 
.PP
Definition at line \fB352\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t M0AR"
DMA stream x memory 0 address register 
.br
 
.PP
Definition at line \fB350\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t M1AR"
DMA stream x memory 1 address register 
.br
 
.PP
Definition at line \fB351\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t NDTR"
DMA stream x number of data register 
.br
 
.PP
Definition at line \fB348\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PAR"
DMA stream x peripheral address register 
.PP
Definition at line \fB349\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
