.TH "DMA_Configuration::Request" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Configuration::Request
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDMA_Request\fP \fBSPI3_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBSPI3_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBSPI2_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBSPI2_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBSPI1_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBSPI1_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBI2S2_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBI2S2_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBI2S3_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBI2S3_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBI2C1_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBI2C1_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBI2C2_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBI2C2_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBI2C3_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBI2C3_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUSART1_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUSART1_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUSART2_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUSART2_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUSART3_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUSART3_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUART4_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUART4_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUART5_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUART5_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUART6_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUART6_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUART7_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUART7_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUART8_RX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBUART8_TX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM1_UP\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM1_CH1\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM1_CH2\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM1_CH3\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM1_CH4\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM1_TRIG\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM1_COM\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM8_UP\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM8_CH1\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM8_CH2\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM8_CH3\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM8_CH4\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM8_TRIG\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM8_COM\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM2_UP\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM2_CH1\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM2_CH2\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM2_CH3\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM2_CH4\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM3_CH1\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM3_CH2\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM3_CH3\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM3_CH4\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM3_UP\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM3_TRIG\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM4_CH1\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM4_CH2\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM4_CH3\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM4_UP\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM5_CH1\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM5_CH2\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM5_CH3\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM5_CH4\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM5_UP\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM5_TRIG\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM6_UP\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBTIM7_UP\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fB_DAC1\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fB_DAC2\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fBSDIO_RXTX\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fB_DCMI\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fB_ADC1\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fB_ADC2\fP"
.br
.ti -1c
.RI "\fBDMA_Request\fP \fB_ADC3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBDMA_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBDMA_Request\fP _ADC1"

.PP
Definition at line \fB140\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP _ADC2"

.PP
Definition at line \fB141\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP _ADC3"

.PP
Definition at line \fB142\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP _DAC1"

.PP
Definition at line \fB130\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP _DAC2"

.PP
Definition at line \fB131\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP _DCMI"

.PP
Definition at line \fB137\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP I2C1_RX"

.PP
Definition at line \fB50\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP I2C1_TX"

.PP
Definition at line \fB51\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP I2C2_RX"

.PP
Definition at line \fB52\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP I2C2_TX"

.PP
Definition at line \fB53\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP I2C3_RX"

.PP
Definition at line \fB54\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP I2C3_TX"

.PP
Definition at line \fB55\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP I2S2_RX"

.PP
Definition at line \fB44\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP I2S2_TX"

.PP
Definition at line \fB45\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP I2S3_RX"

.PP
Definition at line \fB46\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP I2S3_TX"

.PP
Definition at line \fB47\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP SDIO_RXTX"

.PP
Definition at line \fB134\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP SPI1_RX"

.PP
Definition at line \fB40\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP SPI1_TX"

.PP
Definition at line \fB41\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP SPI2_RX"

.PP
Definition at line \fB37\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP SPI2_TX"

.PP
Definition at line \fB38\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP SPI3_RX"

.PP
Definition at line \fB34\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP SPI3_TX"

.PP
Definition at line \fB35\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM1_CH1"

.PP
Definition at line \fB78\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM1_CH2"

.PP
Definition at line \fB79\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM1_CH3"

.PP
Definition at line \fB80\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM1_CH4"

.PP
Definition at line \fB81\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM1_COM"

.PP
Definition at line \fB83\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM1_TRIG"

.PP
Definition at line \fB82\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM1_UP"

.PP
Definition at line \fB77\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM2_CH1"

.PP
Definition at line \fB96\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM2_CH2"

.PP
Definition at line \fB97\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM2_CH3"

.PP
Definition at line \fB98\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM2_CH4"

.PP
Definition at line \fB99\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM2_UP"

.PP
Definition at line \fB95\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM3_CH1"

.PP
Definition at line \fB102\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM3_CH2"

.PP
Definition at line \fB103\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM3_CH3"

.PP
Definition at line \fB104\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM3_CH4"

.PP
Definition at line \fB105\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM3_TRIG"

.PP
Definition at line \fB107\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM3_UP"

.PP
Definition at line \fB106\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM4_CH1"

.PP
Definition at line \fB110\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM4_CH2"

.PP
Definition at line \fB111\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM4_CH3"

.PP
Definition at line \fB112\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM4_UP"

.PP
Definition at line \fB113\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM5_CH1"

.PP
Definition at line \fB116\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM5_CH2"

.PP
Definition at line \fB117\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM5_CH3"

.PP
Definition at line \fB118\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM5_CH4"

.PP
Definition at line \fB119\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM5_TRIG"

.PP
Definition at line \fB121\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM5_UP"

.PP
Definition at line \fB120\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM6_UP"

.PP
Definition at line \fB123\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM7_UP"

.PP
Definition at line \fB125\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM8_CH1"

.PP
Definition at line \fB87\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM8_CH2"

.PP
Definition at line \fB88\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM8_CH3"

.PP
Definition at line \fB89\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM8_CH4"

.PP
Definition at line \fB90\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM8_COM"

.PP
Definition at line \fB92\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM8_TRIG"

.PP
Definition at line \fB91\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP TIM8_UP"

.PP
Definition at line \fB86\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP UART4_RX"

.PP
Definition at line \fB64\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP UART4_TX"

.PP
Definition at line \fB65\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP UART5_RX"

.PP
Definition at line \fB66\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP UART5_TX"

.PP
Definition at line \fB67\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP UART6_RX"

.PP
Definition at line \fB68\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP UART6_TX"

.PP
Definition at line \fB69\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP UART7_RX"

.PP
Definition at line \fB70\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP UART7_TX"

.PP
Definition at line \fB71\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP UART8_RX"

.PP
Definition at line \fB72\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP UART8_TX"

.PP
Definition at line \fB73\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP USART1_RX"

.PP
Definition at line \fB58\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP USART1_TX"

.PP
Definition at line \fB59\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP USART2_RX"

.PP
Definition at line \fB60\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP USART2_TX"

.PP
Definition at line \fB61\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP USART3_RX"

.PP
Definition at line \fB62\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "\fBDMA_Request\fP USART3_TX"

.PP
Definition at line \fB63\fP of file \fBDMA_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
