.TH "DMA_Config" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Config
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDMA_Request\fP \fBRequest\fP"
.br
.ti -1c
.RI "uint32_t \fBflow_control\fP"
.br
.ti -1c
.RI "uint32_t \fBtransfer_direction\fP"
.br
.ti -1c
.RI "uint32_t \fBpriority_level\fP"
.br
.ti -1c
.RI "uint32_t \fBcircular_mode\fP"
.br
.ti -1c
.RI "uint32_t \fBinterrupts\fP"
.br
.ti -1c
.RI "uint16_t \fBmemory_pointer_increment\fP"
.br
.ti -1c
.RI "uint16_t \fBperipheral_pointer_increment\fP"
.br
.ti -1c
.RI "uint32_t \fBperipheral_data_size\fP"
.br
.ti -1c
.RI "uint32_t \fBmemory_data_size\fP"
.br
.ti -1c
.RI "uint32_t \fBperipheral_address\fP"
.br
.ti -1c
.RI "uint32_t \fBmemory_address\fP"
.br
.ti -1c
.RI "uint16_t \fBbuffer_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB37\fP of file \fBDMA\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t buffer_length"

.PP
Definition at line \fB52\fP of file \fBDMA\&.h\fP\&.
.SS "uint32_t circular_mode"

.PP
Definition at line \fB43\fP of file \fBDMA\&.h\fP\&.
.SS "uint32_t flow_control"

.PP
Definition at line \fB40\fP of file \fBDMA\&.h\fP\&.
.SS "uint32_t interrupts"

.PP
Definition at line \fB44\fP of file \fBDMA\&.h\fP\&.
.SS "uint32_t memory_address"

.PP
Definition at line \fB51\fP of file \fBDMA\&.h\fP\&.
.SS "uint32_t memory_data_size"

.PP
Definition at line \fB49\fP of file \fBDMA\&.h\fP\&.
.SS "uint16_t memory_pointer_increment"

.PP
Definition at line \fB45\fP of file \fBDMA\&.h\fP\&.
.SS "uint32_t peripheral_address"

.PP
Definition at line \fB50\fP of file \fBDMA\&.h\fP\&.
.SS "uint32_t peripheral_data_size"

.PP
Definition at line \fB48\fP of file \fBDMA\&.h\fP\&.
.SS "uint16_t peripheral_pointer_increment"

.PP
Definition at line \fB46\fP of file \fBDMA\&.h\fP\&.
.SS "uint32_t priority_level"

.PP
Definition at line \fB42\fP of file \fBDMA\&.h\fP\&.
.SS "\fBDMA_Request\fP Request"

.PP
Definition at line \fB39\fP of file \fBDMA\&.h\fP\&.
.SS "uint32_t transfer_direction"

.PP
Definition at line \fB41\fP of file \fBDMA\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
