.TH "DMA_Configuration::Priority_Level" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Configuration::Priority_Level
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBLow\fP"
.br
.ti -1c
.RI "uint32_t \fBMedium\fP"
.br
.ti -1c
.RI "uint32_t \fBHigh\fP"
.br
.ti -1c
.RI "uint32_t \fBVery_high\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB161\fP of file \fBDMA_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t High"

.PP
Definition at line \fB165\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "uint32_t Low"

.PP
Definition at line \fB163\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "uint32_t Medium"

.PP
Definition at line \fB164\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "uint32_t Very_high"

.PP
Definition at line \fB166\fP of file \fBDMA_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
