.TH "DMA_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_TypeDef
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBLISR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHISR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBLIFCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHIFCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB355\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t HIFCR"
DMA high interrupt flag clear register, Address offset: 0x0C 
.PP
Definition at line \fB360\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HISR"
DMA high interrupt status register, Address offset: 0x04 
.PP
Definition at line \fB358\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t LIFCR"
DMA low interrupt flag clear register, Address offset: 0x08 
.PP
Definition at line \fB359\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t LISR"
DMA low interrupt status register, Address offset: 0x00 
.PP
Definition at line \fB357\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
