.TH "DMA_Flags_Typedef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Flags_Typedef
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBTransfer_Complete_Flag\fP"
.br
.ti -1c
.RI "bool \fBHalf_Transfer_Complete_Flag\fP"
.br
.ti -1c
.RI "bool \fBTransfer_Error_Flag\fP"
.br
.ti -1c
.RI "bool \fBDirect_Mode_Error_Flag\fP"
.br
.ti -1c
.RI "bool \fBFifo_Error_Flag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBDMA_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool Direct_Mode_Error_Flag"

.PP
Definition at line \fB19\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "bool Fifo_Error_Flag"

.PP
Definition at line \fB20\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "bool Half_Transfer_Complete_Flag"

.PP
Definition at line \fB17\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "bool Transfer_Complete_Flag"

.PP
Definition at line \fB16\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "bool Transfer_Error_Flag"

.PP
Definition at line \fB18\fP of file \fBDMA_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
