.TH "DMA_Configuration::DMA_Interrupts" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Configuration::DMA_Interrupts
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBTransfer_Complete\fP"
.br
.ti -1c
.RI "uint32_t \fBHalf_Transfer_Complete\fP"
.br
.ti -1c
.RI "uint32_t \fBTransfer_Error\fP"
.br
.ti -1c
.RI "uint32_t \fBDirect_Mode_Error\fP"
.br
.ti -1c
.RI "uint32_t \fBFifo_Error\fP"
.br
.ti -1c
.RI "uint32_t \fBDisable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB190\fP of file \fBDMA_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t Direct_Mode_Error"

.PP
Definition at line \fB195\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "uint32_t Disable"

.PP
Definition at line \fB197\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "uint32_t Fifo_Error"

.PP
Definition at line \fB196\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "uint32_t Half_Transfer_Complete"

.PP
Definition at line \fB193\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "uint32_t Transfer_Complete"

.PP
Definition at line \fB192\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "uint32_t Transfer_Error"

.PP
Definition at line \fB194\fP of file \fBDMA_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
