.TH "DMA_Configuration::Transfer_Direction" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Configuration::Transfer_Direction
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBPeripheral_to_memory\fP"
.br
.ti -1c
.RI "uint32_t \fBMemory_to_peripheral\fP"
.br
.ti -1c
.RI "uint32_t \fBMemory_to_memory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB153\fP of file \fBDMA_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t Memory_to_memory"

.PP
Definition at line \fB157\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "uint32_t Memory_to_peripheral"

.PP
Definition at line \fB156\fP of file \fBDMA_Defs\&.h\fP\&.
.SS "uint32_t Peripheral_to_memory"

.PP
Definition at line \fB155\fP of file \fBDMA_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
