.TH "DWT_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DWT_Type \- Structure type to access the Data Watchpoint and Trace Register (DWT)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_armv81mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__IOM uint32_t \fBCTRL\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCYCCNT\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCPICNT\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBEXCCNT\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBSLEEPCNT\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBLSUCNT\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBFOLDCNT\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBPCSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP0\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION0\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP1\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION1\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED6\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP3\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED7\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION3\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED8\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP4\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED9\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION4\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED10\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP5\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED11\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION5\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED12\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP6\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED13\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION6\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED14\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP7\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED15\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION7\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED16\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP8\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED17\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION8\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED18\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP9\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED19\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION9\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED20\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP10\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED21\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION10\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED22\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP11\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED23\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION11\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED24\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP12\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED25\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION12\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED26\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP13\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED27\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION13\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED28\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP14\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED29\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION14\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED30\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCOMP15\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED31\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBFUNCTION15\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED32\fP [934U]"
.br
.ti -1c
.RI "__IM uint32_t \fBLSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED33\fP [1U]"
.br
.ti -1c
.RI "__IM uint32_t \fBDEVARCH\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [6U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBMASK0\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBMASK1\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBMASK2\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBMASK3\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBLAR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Data Watchpoint and Trace Register (DWT)\&. 
.PP
Definition at line \fB1179\fP of file \fBcore_armv81mml\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
