.TH "EMSS_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EMSS_Type
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__IOM uint32_t \fBCACR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBITCMCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDTCMCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB560\fP of file \fBcore_starmc1\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
