.TH "ErrBnk_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrBnk_Type \- Structure type to access the Error Banking Registers (ERRBNK)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_cm55\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__IOM uint32_t \fBIEBR0\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBIEBR1\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [2U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBDEBR0\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDEBR1\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [2U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBTEBR0\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBTEBR1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Error Banking Registers (ERRBNK)\&. 
.PP
Definition at line \fB1615\fP of file \fBcore_cm55\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
