.TH "ETH_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ETH_TypeDef \- Ethernet MAC\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACFFR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACHTHR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACHTLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACMIIAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACMIIDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACFCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACVLANTR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [2]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACRWUFFR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACPMTCSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACDBGR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACIMR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACA0HR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACA0LR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACA1HR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACA1LR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACA2HR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACA2LR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACA3HR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMACA3LR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [40]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCRIR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCTIR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCRIMR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCTIMR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [14]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCTGFSCCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCTGFMSCCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [5]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCTGFCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [10]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCRFCECR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCRFAECR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED6\fP [10]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCRGUFCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED7\fP [334]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPTPTSCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPTPSSIR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPTPTSHR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPTPTSLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPTPTSHUR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPTPTSLUR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPTPTSAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPTPTTHR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPTPTTLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRESERVED8\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPTPTSSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED9\fP [565]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMABMR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMATPDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMARPDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMARDLAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMATDLAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMASR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMAOMR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMAIER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMAMFBOCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMARSWTR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED10\fP [8]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMACHTDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMACHRDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMACHTBAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMACHRBAR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Ethernet MAC\&. 
.PP
Definition at line \fB367\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t DMABMR"

.PP
Definition at line \fB421\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMACHRBAR"

.PP
Definition at line \fB435\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMACHRDR"

.PP
Definition at line \fB433\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMACHTBAR"

.PP
Definition at line \fB434\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMACHTDR"

.PP
Definition at line \fB432\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMAIER"

.PP
Definition at line \fB428\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMAMFBOCR"

.PP
Definition at line \fB429\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMAOMR"

.PP
Definition at line \fB427\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMARDLAR"

.PP
Definition at line \fB424\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMARPDR"

.PP
Definition at line \fB423\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMARSWTR"

.PP
Definition at line \fB430\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMASR"

.PP
Definition at line \fB426\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMATDLAR"

.PP
Definition at line \fB425\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DMATPDR"

.PP
Definition at line \fB422\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACA0HR"

.PP
Definition at line \fB384\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACA0LR"

.PP
Definition at line \fB385\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACA1HR"

.PP
Definition at line \fB386\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACA1LR"

.PP
Definition at line \fB387\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACA2HR"

.PP
Definition at line \fB388\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACA2LR"

.PP
Definition at line \fB389\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACA3HR"

.PP
Definition at line \fB390\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACA3LR"

.PP
Definition at line \fB391\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACCR"

.PP
Definition at line \fB369\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACDBGR"

.PP
Definition at line \fB381\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACFCR"

.PP
Definition at line \fB375\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACFFR"

.PP
Definition at line \fB370\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACHTHR"

.PP
Definition at line \fB371\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACHTLR"

.PP
Definition at line \fB372\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACIMR"

.PP
Definition at line \fB383\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACMIIAR"

.PP
Definition at line \fB373\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACMIIDR"

.PP
Definition at line \fB374\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACPMTCSR"

.PP
Definition at line \fB379\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACRWUFFR"

.PP
Definition at line \fB378\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACSR"

.PP
Definition at line \fB382\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MACVLANTR"

.PP
Definition at line \fB376\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCCR"

.PP
Definition at line \fB393\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCRFAECR"

.PP
Definition at line \fB405\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCRFCECR"

.PP
Definition at line \fB404\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCRGUFCR"

.PP
Definition at line \fB407\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCRIMR"

.PP
Definition at line \fB396\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCRIR"

.PP
Definition at line \fB394\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCTGFCR"

.PP
Definition at line \fB402\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCTGFMSCCR"

.PP
Definition at line \fB400\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCTGFSCCR"

.PP
Definition at line \fB399\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCTIMR"

.PP
Definition at line \fB397\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MMCTIR"

.PP
Definition at line \fB395\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PTPSSIR"

.PP
Definition at line \fB410\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PTPTSAR"

.PP
Definition at line \fB415\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PTPTSCR"

.PP
Definition at line \fB409\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PTPTSHR"

.PP
Definition at line \fB411\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PTPTSHUR"

.PP
Definition at line \fB413\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PTPTSLR"

.PP
Definition at line \fB412\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PTPTSLUR"

.PP
Definition at line \fB414\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PTPTSSR"

.PP
Definition at line \fB419\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PTPTTHR"

.PP
Definition at line \fB416\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PTPTTLR"

.PP
Definition at line \fB417\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED0[2]"

.PP
Definition at line \fB377\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED1"

.PP
Definition at line \fB380\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED10[8]"

.PP
Definition at line \fB431\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED2[40]"

.PP
Definition at line \fB392\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED3[14]"

.PP
Definition at line \fB398\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED4[5]"

.PP
Definition at line \fB401\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED5[10]"

.PP
Definition at line \fB403\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED6[10]"

.PP
Definition at line \fB406\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED7[334]"

.PP
Definition at line \fB408\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t RESERVED8"

.PP
Definition at line \fB418\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED9[565]"

.PP
Definition at line \fB420\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
