.TH "EWIC_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EWIC_Type \- Structure type to access the External Wakeup Interrupt Controller Registers (EWIC)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_cm55\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__OM uint32_t \fBEVENTSPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [31U]"
.br
.ti -1c
.RI "__IM uint32_t \fBEVENTMASKA\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBEVENTMASK\fP [15]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the External Wakeup Interrupt Controller Registers (EWIC)\&. 
.PP
Definition at line \fB1570\fP of file \fBcore_cm55\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
