.TH "Exported_macros" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exported_macros \- Exported_macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_ADC_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_ADC_MULTIMODE_MASTER_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_ADC_COMMON_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_CAN_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_CRC_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_DAC_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_DCMI_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_STREAM_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_GPIO_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_I2C_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_SMBUS_ALL_INSTANCE\fP   IS_I2C_ALL_INSTANCE"
.br
.ti -1c
.RI "#define \fBIS_I2S_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_I2S_EXT_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_I2S_ALL_INSTANCE_EXT\fP   IS_I2S_EXT_ALL_INSTANCE"
.br
.ti -1c
.RI "#define \fBIS_RNG_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_RTC_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_SPI_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CC1_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CC2_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CC3_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CC4_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_ADVANCED_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_XOR_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_DMA_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_DMA_CC_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CCDMA_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_DMABURST_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_MASTER_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_SLAVE_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_32B_COUNTER_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_ETR_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_REMAP_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CCX_INSTANCE\fP(INSTANCE,  CHANNEL)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CCXN_INSTANCE\fP(INSTANCE,  CHANNEL)"
.br
.ti -1c
.RI "#define \fBIS_TIM_COUNTER_MODE_SELECT_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLOCK_DIVISION_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_COMMUTATION_EVENT_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OCXREF_CLEAR_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLOCKSOURCE_ETRMODE1_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLOCKSOURCE_ETRMODE2_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLOCKSOURCE_TIX_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLOCKSOURCE_ITRX_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_REPETITION_COUNTER_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_ENCODER_INTERFACE_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_HALL_SENSOR_INTERFACE_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_TIM_BREAK_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_USART_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_UART_HALFDUPLEX_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_UART_INSTANCE\fP   IS_UART_HALFDUPLEX_INSTANCE"
.br
.ti -1c
.RI "#define \fBIS_UART_HWFLOW_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_UART_LIN_INSTANCE\fP   IS_UART_HALFDUPLEX_INSTANCE"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_IRDA_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_PCD_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_HCD_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_SDIO_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_IWDG_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBIS_WWDG_ALL_INSTANCE\fP(INSTANCE)"
.br
.ti -1c
.RI "#define \fBUSB_OTG_FS_HOST_MAX_CHANNEL_NBR\fP   8U"
.br
.ti -1c
.RI "#define \fBUSB_OTG_FS_MAX_IN_ENDPOINTS\fP   4U    /* Including EP0 */"
.br
.ti -1c
.RI "#define \fBUSB_OTG_FS_MAX_OUT_ENDPOINTS\fP   4U    /* Including EP0 */"
.br
.ti -1c
.RI "#define \fBUSB_OTG_FS_TOTAL_FIFO_SIZE\fP   1280U /* in Bytes */"
.br
.ti -1c
.RI "#define \fBRCC_PLLCFGR_RST_VALUE\fP   0x24003010U"
.br
.ti -1c
.RI "#define \fBRCC_PLLI2SCFGR_RST_VALUE\fP   0x20003000U"
.br
.ti -1c
.RI "#define \fBRCC_MAX_FREQUENCY\fP   168000000U"
.br
.ti -1c
.RI "#define \fBRCC_MAX_FREQUENCY_SCALE1\fP   \fBRCC_MAX_FREQUENCY\fP"
.br
.ti -1c
.RI "#define \fBRCC_MAX_FREQUENCY_SCALE2\fP   144000000U"
.br
.ti -1c
.RI "#define \fBRCC_PLLVCO_OUTPUT_MIN\fP   100000000U"
.br
.ti -1c
.RI "#define \fBRCC_PLLVCO_INPUT_MIN\fP   950000U"
.br
.ti -1c
.RI "#define \fBRCC_PLLVCO_INPUT_MAX\fP   2100000U"
.br
.ti -1c
.RI "#define \fBRCC_PLLVCO_OUTPUT_MAX\fP   432000000U"
.br
.ti -1c
.RI "#define \fBRCC_PLLN_MIN_VALUE\fP   50U"
.br
.ti -1c
.RI "#define \fBRCC_PLLN_MAX_VALUE\fP   432U"
.br
.ti -1c
.RI "#define \fBFLASH_SCALE1_LATENCY1_FREQ\fP   30000000U"
.br
.ti -1c
.RI "#define \fBFLASH_SCALE1_LATENCY2_FREQ\fP   60000000U"
.br
.ti -1c
.RI "#define \fBFLASH_SCALE1_LATENCY3_FREQ\fP   90000000U"
.br
.ti -1c
.RI "#define \fBFLASH_SCALE1_LATENCY4_FREQ\fP   120000000U"
.br
.ti -1c
.RI "#define \fBFLASH_SCALE1_LATENCY5_FREQ\fP   150000000U"
.br
.ti -1c
.RI "#define \fBFLASH_SCALE2_LATENCY1_FREQ\fP   30000000U"
.br
.ti -1c
.RI "#define \fBFLASH_SCALE2_LATENCY2_FREQ\fP   60000000U"
.br
.ti -1c
.RI "#define \fBFLASH_SCALE2_LATENCY3_FREQ\fP   90000000U"
.br
.ti -1c
.RI "#define \fBFLASH_SCALE2_LATENCY4_FREQ\fP   120000000U"
.br
.ti -1c
.RI "#define \fBUSB_OTG_HS_HOST_MAX_CHANNEL_NBR\fP   12U"
.br
.ti -1c
.RI "#define \fBUSB_OTG_HS_MAX_IN_ENDPOINTS\fP   6U    /* Including EP0 */"
.br
.ti -1c
.RI "#define \fBUSB_OTG_HS_MAX_OUT_ENDPOINTS\fP   6U    /* Including EP0 */"
.br
.ti -1c
.RI "#define \fBUSB_OTG_HS_TOTAL_FIFO_SIZE\fP   4096U /* in Bytes */"
.br
.ti -1c
.RI "#define \fBFMC_IRQn\fP   \fBFSMC_IRQn\fP"
.br
.ti -1c
.RI "#define \fBFMC_IRQHandler\fP   FSMC_IRQHandler"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FLASH_SCALE1_LATENCY1_FREQ   30000000U"
HCLK frequency to set FLASH latency 1 in power scale 1 
.br
 
.PP
Definition at line \fB15565\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define FLASH_SCALE1_LATENCY2_FREQ   60000000U"
HCLK frequency to set FLASH latency 2 in power scale 1 
.br
 
.PP
Definition at line \fB15566\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define FLASH_SCALE1_LATENCY3_FREQ   90000000U"
HCLK frequency to set FLASH latency 3 in power scale 1 
.br
 
.PP
Definition at line \fB15567\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define FLASH_SCALE1_LATENCY4_FREQ   120000000U"
HCLK frequency to set FLASH latency 4 in power scale 1 
.br
 
.PP
Definition at line \fB15568\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define FLASH_SCALE1_LATENCY5_FREQ   150000000U"
HCLK frequency to set FLASH latency 5 in power scale 1 
.br
 
.PP
Definition at line \fB15569\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define FLASH_SCALE2_LATENCY1_FREQ   30000000U"
HCLK frequency to set FLASH latency 1 in power scale 2 
.br
 
.PP
Definition at line \fB15571\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define FLASH_SCALE2_LATENCY2_FREQ   60000000U"
HCLK frequency to set FLASH latency 2 in power scale 2 
.br
 
.PP
Definition at line \fB15572\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define FLASH_SCALE2_LATENCY3_FREQ   90000000U"
HCLK frequency to set FLASH latency 3 in power scale 2 
.br
 
.PP
Definition at line \fB15573\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define FLASH_SCALE2_LATENCY4_FREQ   120000000U"
HCLK frequency to set FLASH latency 4 in power scale 2 
.br
 
.PP
Definition at line \fB15574\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define FMC_IRQHandler   FSMC_IRQHandler"

.PP
Definition at line \fB15591\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define FMC_IRQn   \fBFSMC_IRQn\fP"

.PP
Definition at line \fB15588\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_ADC_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                       (((INSTANCE) == ADC1) || \\
                                       ((INSTANCE) == ADC2) || \\
                                       ((INSTANCE) == ADC3))
.PP
.fi

.PP
Definition at line \fB15099\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_ADC_COMMON_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
((INSTANCE) == ADC123_COMMON)
.PP
.fi

.PP
Definition at line \fB15105\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_ADC_MULTIMODE_MASTER_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
((INSTANCE) == ADC1)
.PP
.fi

.PP
Definition at line \fB15103\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_CAN_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                       (((INSTANCE) == CAN1) || \\
                                       ((INSTANCE) == CAN2))
.PP
.fi

.PP
Definition at line \fB15108\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_CRC_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
((INSTANCE) == CRC)
.PP
.fi

.PP
Definition at line \fB15111\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_DAC_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
((INSTANCE) == DAC1)
.PP
.fi

.PP
Definition at line \fB15114\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_DCMI_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
((INSTANCE) == DCMI)
.PP
.fi

.PP
Definition at line \fB15117\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_DMA_STREAM_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                              (((INSTANCE) == DMA1_Stream0) || \\
                                              ((INSTANCE) == DMA1_Stream1) || \\
                                              ((INSTANCE) == DMA1_Stream2) || \\
                                              ((INSTANCE) == DMA1_Stream3) || \\
                                              ((INSTANCE) == DMA1_Stream4) || \\
                                              ((INSTANCE) == DMA1_Stream5) || \\
                                              ((INSTANCE) == DMA1_Stream6) || \\
                                              ((INSTANCE) == DMA1_Stream7) || \\
                                              ((INSTANCE) == DMA2_Stream0) || \\
                                              ((INSTANCE) == DMA2_Stream1) || \\
                                              ((INSTANCE) == DMA2_Stream2) || \\
                                              ((INSTANCE) == DMA2_Stream3) || \\
                                              ((INSTANCE) == DMA2_Stream4) || \\
                                              ((INSTANCE) == DMA2_Stream5) || \\
                                              ((INSTANCE) == DMA2_Stream6) || \\
                                              ((INSTANCE) == DMA2_Stream7))
.PP
.fi

.PP
Definition at line \fB15120\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_GPIO_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                        (((INSTANCE) == GPIOA) || \\
                                        ((INSTANCE) == GPIOB) || \\
                                        ((INSTANCE) == GPIOC) || \\
                                        ((INSTANCE) == GPIOD) || \\
                                        ((INSTANCE) == GPIOE) || \\
                                        ((INSTANCE) == GPIOF) || \\
                                        ((INSTANCE) == GPIOG) || \\
                                        ((INSTANCE) == GPIOH) || \\
                                        ((INSTANCE) == GPIOI))
.PP
.fi

.PP
Definition at line \fB15138\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_HCD_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                       (((INSTANCE) == USB_OTG_FS) || \\
                                       ((INSTANCE) == USB_OTG_HS))
.PP
.fi

.PP
Definition at line \fB15530\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_I2C_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                       (((INSTANCE) == I2C1) || \\
                                       ((INSTANCE) == I2C2) || \\
                                       ((INSTANCE) == I2C3))
.PP
.fi

.PP
Definition at line \fB15149\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_I2S_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                       (((INSTANCE) == SPI2) || \\
                                       ((INSTANCE) == SPI3))
.PP
.fi

.PP
Definition at line \fB15158\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_I2S_ALL_INSTANCE_EXT   IS_I2S_EXT_ALL_INSTANCE"

.PP
Definition at line \fB15165\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_I2S_EXT_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                           (((INSTANCE) == I2S2ext)|| \\
                                           ((INSTANCE) == I2S3ext))
.PP
.fi

.PP
Definition at line \fB15162\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_IRDA_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                    (((INSTANCE) == USART1) || \\
                                    ((INSTANCE) == USART2) || \\
                                    ((INSTANCE) == USART3) || \\
                                    ((INSTANCE) == UART4)  || \\
                                    ((INSTANCE) == UART5)  || \\
                                    ((INSTANCE) == USART6))
.PP
.fi

.PP
Definition at line \fB15517\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_IWDG_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
((INSTANCE) == IWDG)
.PP
.fi

.PP
Definition at line \fB15537\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_PCD_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                       (((INSTANCE) == USB_OTG_FS) || \\
                                       ((INSTANCE) == USB_OTG_HS))
.PP
.fi

.PP
Definition at line \fB15526\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_RNG_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
((INSTANCE) == RNG)
.PP
.fi

.PP
Definition at line \fB15168\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_RTC_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
((INSTANCE) == RTC)
.PP
.fi

.PP
Definition at line \fB15171\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_SDIO_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
((INSTANCE) == SDIO)
.PP
.fi

.PP
Definition at line \fB15534\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_SMARTCARD_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                         (((INSTANCE) == USART1) || \\
                                         ((INSTANCE) == USART2) || \\
                                         ((INSTANCE) == USART3) || \\
                                         ((INSTANCE) == USART6))
.PP
.fi

.PP
Definition at line \fB15511\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_SMBUS_ALL_INSTANCE   IS_I2C_ALL_INSTANCE"

.PP
Definition at line \fB15154\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_SPI_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                       (((INSTANCE) == SPI1) || \\
                                       ((INSTANCE) == SPI2) || \\
                                       ((INSTANCE) == SPI3))
.PP
.fi

.PP
Definition at line \fB15175\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_32B_COUNTER_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                              (((INSTANCE) == TIM2) || \\
                                              ((INSTANCE) == TIM5))
.PP
.fi

.PP
Definition at line \fB15302\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_ADVANCED_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                           (((INSTANCE) == TIM1) || \\
                                           ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15237\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_BREAK_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                          (((INSTANCE) == TIM1) || \\
                                          ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15482\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CC1_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                         (((INSTANCE) == TIM1)  || \\
                                         ((INSTANCE) == TIM2)  || \\
                                         ((INSTANCE) == TIM3)  || \\
                                         ((INSTANCE) == TIM4)  || \\
                                         ((INSTANCE) == TIM5)  || \\
                                         ((INSTANCE) == TIM8)  || \\
                                         ((INSTANCE) == TIM9)  || \\
                                         ((INSTANCE) == TIM10) || \\
                                         ((INSTANCE) == TIM11) || \\
                                         ((INSTANCE) == TIM12) || \\
                                         ((INSTANCE) == TIM13) || \\
                                         ((INSTANCE) == TIM14))
.PP
.fi

.PP
Definition at line \fB15197\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CC2_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                       (((INSTANCE) == TIM1) || \\
                                       ((INSTANCE) == TIM2) || \\
                                       ((INSTANCE) == TIM3) || \\
                                       ((INSTANCE) == TIM4) || \\
                                       ((INSTANCE) == TIM5) || \\
                                       ((INSTANCE) == TIM8) || \\
                                       ((INSTANCE) == TIM9) || \\
                                       ((INSTANCE) == TIM12))
.PP
.fi

.PP
Definition at line \fB15211\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CC3_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                         (((INSTANCE) == TIM1) || \\
                                         ((INSTANCE) == TIM2) || \\
                                         ((INSTANCE) == TIM3) || \\
                                         ((INSTANCE) == TIM4) || \\
                                         ((INSTANCE) == TIM5) || \\
                                         ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15221\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CC4_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                       (((INSTANCE) == TIM1) || \\
                                       ((INSTANCE) == TIM2) || \\
                                       ((INSTANCE) == TIM3) || \\
                                       ((INSTANCE) == TIM4) || \\
                                       ((INSTANCE) == TIM5) || \\
                                       ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15229\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CCDMA_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                          (((INSTANCE) == TIM1) || \\
                                          ((INSTANCE) == TIM2) || \\
                                          ((INSTANCE) == TIM3) || \\
                                          ((INSTANCE) == TIM4) || \\
                                          ((INSTANCE) == TIM5) || \\
                                          ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15267\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CCX_INSTANCE( INSTANCE,  CHANNEL)"

.PP
Definition at line \fB15319\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CCXN_INSTANCE( INSTANCE,  CHANNEL)"
\fBValue:\fP
.nf
   ((((INSTANCE) == TIM1) &&                    \\
     (((CHANNEL) == TIM_CHANNEL_1) ||           \\
      ((CHANNEL) == TIM_CHANNEL_2) ||           \\
      ((CHANNEL) == TIM_CHANNEL_3)))            \\
    ||                                          \\
    (((INSTANCE) == TIM8) &&                    \\
     (((CHANNEL) == TIM_CHANNEL_1) ||           \\
      ((CHANNEL) == TIM_CHANNEL_2) ||           \\
      ((CHANNEL) == TIM_CHANNEL_3))))
.PP
.fi

.PP
Definition at line \fB15377\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CLOCK_DIVISION_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                  (((INSTANCE) == TIM1)  || \\
                                                  ((INSTANCE) == TIM2) || \\
                                                  ((INSTANCE) == TIM3) || \\
                                                  ((INSTANCE) == TIM4) || \\
                                                  ((INSTANCE) == TIM5) || \\
                                                  ((INSTANCE) == TIM8) || \\
                                                  ((INSTANCE) == TIM9) || \\
                                                  ((INSTANCE) == TIM10)|| \\
                                                  ((INSTANCE) == TIM11)|| \\
                                                  ((INSTANCE) == TIM12)|| \\
                                                  ((INSTANCE) == TIM13)|| \\
                                                  ((INSTANCE) == TIM14))
.PP
.fi

.PP
Definition at line \fB15397\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CLOCKSOURCE_ETRMODE1_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                        (((INSTANCE) == TIM1) || \\
                                                        ((INSTANCE) == TIM2) || \\
                                                        ((INSTANCE) == TIM3) || \\
                                                        ((INSTANCE) == TIM4) || \\
                                                        ((INSTANCE) == TIM5) || \\
                                                        ((INSTANCE) == TIM8) || \\
                                                        ((INSTANCE) == TIM9) || \\
                                                        ((INSTANCE) == TIM12))
.PP
.fi

.PP
Definition at line \fB15424\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CLOCKSOURCE_ETRMODE2_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                        (((INSTANCE) == TIM1) || \\
                                                        ((INSTANCE) == TIM2) || \\
                                                        ((INSTANCE) == TIM3) || \\
                                                        ((INSTANCE) == TIM4) || \\
                                                        ((INSTANCE) == TIM5) || \\
                                                        ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15434\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CLOCKSOURCE_ITRX_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                        (((INSTANCE) == TIM1) || \\
                                                        ((INSTANCE) == TIM2) || \\
                                                        ((INSTANCE) == TIM3) || \\
                                                        ((INSTANCE) == TIM4) || \\
                                                        ((INSTANCE) == TIM5) || \\
                                                        ((INSTANCE) == TIM8) || \\
                                                        ((INSTANCE) == TIM9) || \\
                                                        ((INSTANCE) == TIM12))
.PP
.fi

.PP
Definition at line \fB15452\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_CLOCKSOURCE_TIX_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                        (((INSTANCE) == TIM1) || \\
                                                        ((INSTANCE) == TIM2) || \\
                                                        ((INSTANCE) == TIM3) || \\
                                                        ((INSTANCE) == TIM4) || \\
                                                        ((INSTANCE) == TIM5) || \\
                                                        ((INSTANCE) == TIM8) || \\
                                                        ((INSTANCE) == TIM9) || \\
                                                        ((INSTANCE) == TIM12))
.PP
.fi

.PP
Definition at line \fB15442\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_COMMUTATION_EVENT_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                     (((INSTANCE) == TIM1)|| \\
                                                     ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15411\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_COUNTER_MODE_SELECT_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                        (((INSTANCE) == TIM1) || \\
                                                        ((INSTANCE) == TIM2) || \\
                                                        ((INSTANCE) == TIM3) || \\
                                                        ((INSTANCE) == TIM4) || \\
                                                        ((INSTANCE) == TIM5) || \\
                                                        ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15389\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_DMA_CC_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                          (((INSTANCE) == TIM1) || \\
                                          ((INSTANCE) == TIM2) || \\
                                          ((INSTANCE) == TIM3) || \\
                                          ((INSTANCE) == TIM4) || \\
                                          ((INSTANCE) == TIM5) || \\
                                          ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15259\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_DMA_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                       (((INSTANCE) == TIM1) || \\
                                       ((INSTANCE) == TIM2) || \\
                                       ((INSTANCE) == TIM3) || \\
                                       ((INSTANCE) == TIM4) || \\
                                       ((INSTANCE) == TIM5) || \\
                                       ((INSTANCE) == TIM6) || \\
                                       ((INSTANCE) == TIM7) || \\
                                       ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15249\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_DMABURST_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                             (((INSTANCE) == TIM1) || \\
                                             ((INSTANCE) == TIM2) || \\
                                             ((INSTANCE) == TIM3) || \\
                                             ((INSTANCE) == TIM4) || \\
                                             ((INSTANCE) == TIM5) || \\
                                             ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15275\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_ENCODER_INTERFACE_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                      (((INSTANCE) == TIM1) || \\
                                                      ((INSTANCE) == TIM2) || \\
                                                      ((INSTANCE) == TIM3) || \\
                                                      ((INSTANCE) == TIM4) || \\
                                                      ((INSTANCE) == TIM5) || \\
                                                      ((INSTANCE) == TIM8) || \\
                                                      ((INSTANCE) == TIM9) || \\
                                                      ((INSTANCE) == TIM12))
.PP
.fi

.PP
Definition at line \fB15466\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_ETR_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                        (((INSTANCE) == TIM1) || \\
                                        ((INSTANCE) == TIM2) || \\
                                        ((INSTANCE) == TIM3) || \\
                                        ((INSTANCE) == TIM4) || \\
                                        ((INSTANCE) == TIM5) || \\
                                        ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15306\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_HALL_SENSOR_INTERFACE_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                          (((INSTANCE) == TIM1) || \\
                                                          ((INSTANCE) == TIM2) || \\
                                                          ((INSTANCE) == TIM3) || \\
                                                          ((INSTANCE) == TIM4) || \\
                                                          ((INSTANCE) == TIM5) || \\
                                                          ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15475\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                    (((INSTANCE) == TIM1)  || \\
                                    ((INSTANCE) == TIM2) || \\
                                    ((INSTANCE) == TIM3) || \\
                                    ((INSTANCE) == TIM4) || \\
                                    ((INSTANCE) == TIM5) || \\
                                    ((INSTANCE) == TIM6) || \\
                                    ((INSTANCE) == TIM7) || \\
                                    ((INSTANCE) == TIM8) || \\
                                    ((INSTANCE) == TIM9) || \\
                                    ((INSTANCE) == TIM10)|| \\
                                    ((INSTANCE) == TIM11)|| \\
                                    ((INSTANCE) == TIM12)|| \\
                                    ((INSTANCE) == TIM13)|| \\
                                    ((INSTANCE) == TIM14))
.PP
.fi

.PP
Definition at line \fB15181\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_MASTER_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                          (((INSTANCE) == TIM1)  || \\
                                          ((INSTANCE) == TIM2)  || \\
                                          ((INSTANCE) == TIM3)  || \\
                                          ((INSTANCE) == TIM4)  || \\
                                          ((INSTANCE) == TIM5)  || \\
                                          ((INSTANCE) == TIM6)  || \\
                                          ((INSTANCE) == TIM7)  || \\
                                          ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15283\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_OCXREF_CLEAR_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                       (((INSTANCE) == TIM1) || \\
                                                       ((INSTANCE) == TIM2) || \\
                                                       ((INSTANCE) == TIM3) || \\
                                                       ((INSTANCE) == TIM4) || \\
                                                       ((INSTANCE) == TIM5) || \\
                                                       ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15416\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_REMAP_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                         (((INSTANCE) == TIM2)  || \\
                                         ((INSTANCE) == TIM5)  || \\
                                         ((INSTANCE) == TIM11))
.PP
.fi

.PP
Definition at line \fB15314\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_REPETITION_COUNTER_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                                       (((INSTANCE) == TIM1) || \\
                                                       ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15462\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_SLAVE_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                         (((INSTANCE) == TIM1) || \\
                                         ((INSTANCE) == TIM2) || \\
                                         ((INSTANCE) == TIM3) || \\
                                         ((INSTANCE) == TIM4) || \\
                                         ((INSTANCE) == TIM5) || \\
                                         ((INSTANCE) == TIM8) || \\
                                         ((INSTANCE) == TIM9) || \\
                                         ((INSTANCE) == TIM12))
.PP
.fi

.PP
Definition at line \fB15293\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_TIM_XOR_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                         (((INSTANCE) == TIM1) || \\
                                         ((INSTANCE) == TIM2) || \\
                                         ((INSTANCE) == TIM3) || \\
                                         ((INSTANCE) == TIM4) || \\
                                         ((INSTANCE) == TIM5) || \\
                                         ((INSTANCE) == TIM8))
.PP
.fi

.PP
Definition at line \fB15241\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_UART_HALFDUPLEX_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                               (((INSTANCE) == USART1) || \\
                                               ((INSTANCE) == USART2) || \\
                                               ((INSTANCE) == USART3) || \\
                                               ((INSTANCE) == UART4)  || \\
                                               ((INSTANCE) == UART5)  || \\
                                               ((INSTANCE) == USART6))
.PP
.fi

.PP
Definition at line \fB15492\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_UART_HWFLOW_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                           (((INSTANCE) == USART1) || \\
                                           ((INSTANCE) == USART2) || \\
                                           ((INSTANCE) == USART3) || \\
                                           ((INSTANCE) == USART6))
.PP
.fi

.PP
Definition at line \fB15503\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_UART_INSTANCE   IS_UART_HALFDUPLEX_INSTANCE"

.PP
Definition at line \fB15500\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_UART_LIN_INSTANCE   IS_UART_HALFDUPLEX_INSTANCE"

.PP
Definition at line \fB15508\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_USART_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
                                     (((INSTANCE) == USART1) || \\
                                     ((INSTANCE) == USART2) || \\
                                     ((INSTANCE) == USART3) || \\
                                     ((INSTANCE) == USART6))
.PP
.fi

.PP
Definition at line \fB15486\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define IS_WWDG_ALL_INSTANCE( INSTANCE)"
\fBValue:\fP
.nf
((INSTANCE) == WWDG)
.PP
.fi

.PP
Definition at line \fB15540\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_MAX_FREQUENCY   168000000U"
Max frequency of family in Hz 
.PP
Definition at line \fB15554\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_MAX_FREQUENCY_SCALE1   \fBRCC_MAX_FREQUENCY\fP"
Maximum frequency for system clock at power scale1, in Hz 
.PP
Definition at line \fB15555\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_MAX_FREQUENCY_SCALE2   144000000U"
Maximum frequency for system clock at power scale2, in Hz 
.PP
Definition at line \fB15556\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_PLLCFGR_RST_VALUE   0x24003010U"

.PP
Definition at line \fB15551\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_PLLI2SCFGR_RST_VALUE   0x20003000U"

.PP
Definition at line \fB15552\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_PLLN_MAX_VALUE   432U"

.PP
Definition at line \fB15563\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_PLLN_MIN_VALUE   50U"

.PP
Definition at line \fB15562\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_PLLVCO_INPUT_MAX   2100000U"
Frequency max for PLLVCO input, in Hz 
.br
 
.PP
Definition at line \fB15559\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_PLLVCO_INPUT_MIN   950000U"
Frequency min for PLLVCO input, in Hz 
.br
 
.PP
Definition at line \fB15558\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_PLLVCO_OUTPUT_MAX   432000000U"
Frequency max for PLLVCO output, in Hz 
.PP
Definition at line \fB15560\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define RCC_PLLVCO_OUTPUT_MIN   100000000U"
Frequency min for PLLVCO output, in Hz 
.PP
Definition at line \fB15557\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define USB_OTG_FS_HOST_MAX_CHANNEL_NBR   8U"

.PP
Definition at line \fB15543\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define USB_OTG_FS_MAX_IN_ENDPOINTS   4U    /* Including EP0 */"

.PP
Definition at line \fB15544\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define USB_OTG_FS_MAX_OUT_ENDPOINTS   4U    /* Including EP0 */"

.PP
Definition at line \fB15545\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define USB_OTG_FS_TOTAL_FIFO_SIZE   1280U /* in Bytes */"

.PP
Definition at line \fB15546\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define USB_OTG_HS_HOST_MAX_CHANNEL_NBR   12U"

.PP
Definition at line \fB15576\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define USB_OTG_HS_MAX_IN_ENDPOINTS   6U    /* Including EP0 */"

.PP
Definition at line \fB15577\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define USB_OTG_HS_MAX_OUT_ENDPOINTS   6U    /* Including EP0 */"

.PP
Definition at line \fB15578\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "#define USB_OTG_HS_TOTAL_FIFO_SIZE   4096U /* in Bytes */"

.PP
Definition at line \fB15579\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
