.TH "EXTI_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_TypeDef \- External Interrupt/Event Controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIMR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEMR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRTSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFTSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSWIER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
External Interrupt/Event Controller\&. 
.PP
Definition at line \fB442\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t EMR"
EXTI Event mask register, Address offset: 0x04 
.PP
Definition at line \fB445\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t FTSR"
EXTI Falling trigger selection register, Address offset: 0x0C 
.PP
Definition at line \fB447\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t IMR"
EXTI Interrupt mask register, Address offset: 0x00 
.PP
Definition at line \fB444\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PR"
EXTI Pending register, Address offset: 0x14 
.PP
Definition at line \fB449\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t RTSR"
EXTI Rising trigger selection register, Address offset: 0x08 
.PP
Definition at line \fB446\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t SWIER"
EXTI Software interrupt event register, Address offset: 0x10 
.PP
Definition at line \fB448\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
