.TH "FLASH_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_TypeDef \- FLASH Registers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBACR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBKEYR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOPTKEYR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOPTCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOPTCR1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FLASH Registers\&. 
.PP
Definition at line \fB456\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t ACR"
FLASH access control register, Address offset: 0x00 
.PP
Definition at line \fB458\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CR"
FLASH control register, Address offset: 0x10 
.PP
Definition at line \fB462\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t KEYR"
FLASH key register, Address offset: 0x04 
.PP
Definition at line \fB459\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t OPTCR"
FLASH option control register , Address offset: 0x14 
.PP
Definition at line \fB463\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t OPTCR1"
FLASH option control register 1, Address offset: 0x18 
.PP
Definition at line \fB464\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t OPTKEYR"
FLASH option key register, Address offset: 0x08 
.PP
Definition at line \fB460\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t SR"
FLASH status register, Address offset: 0x0C 
.PP
Definition at line \fB461\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
