.TH "FSMC_Bank2_3_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_Bank2_3_TypeDef \- Flexible Static Memory Controller Bank2\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPMEM2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPATT2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBECCR2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPCR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPMEM3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPATT3\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBECCR3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Flexible Static Memory Controller Bank2\&. 
.PP
Definition at line \fB491\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t ECCR2"
NAND Flash ECC result registers 2, Address offset: 0x74 
.PP
Definition at line \fB498\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t ECCR3"
NAND Flash ECC result registers 3, Address offset: 0x94 
.PP
Definition at line \fB506\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PATT2"
NAND Flash Attribute memory space timing register 2, Address offset: 0x6C 
.PP
Definition at line \fB496\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PATT3"
NAND Flash Attribute memory space timing register 3, Address offset: 0x8C 
.PP
Definition at line \fB504\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PCR2"
NAND Flash control register 2, Address offset: 0x60 
.PP
Definition at line \fB493\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PCR3"
NAND Flash control register 3, Address offset: 0x80 
.PP
Definition at line \fB501\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PMEM2"
NAND Flash Common memory space timing register 2, Address offset: 0x68 
.PP
Definition at line \fB495\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PMEM3"
NAND Flash Common memory space timing register 3, Address offset: 0x88 
.PP
Definition at line \fB503\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED0"
Reserved, 0x70 
.br
 
.PP
Definition at line \fB497\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED1"
Reserved, 0x78 
.br
 
.PP
Definition at line \fB499\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED2"
Reserved, 0x7C 
.br
 
.PP
Definition at line \fB500\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED3"
Reserved, 0x90 
.br
 
.PP
Definition at line \fB505\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t SR2"
NAND Flash FIFO status and interrupt register 2, Address offset: 0x64 
.PP
Definition at line \fB494\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t SR3"
NAND Flash FIFO status and interrupt register 3, Address offset: 0x84 
.PP
Definition at line \fB502\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
