.TH "FSMC_Bank4_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_Bank4_TypeDef \- Flexible Static Memory Controller Bank4\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPCR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPMEM4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPATT4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPIO4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Flexible Static Memory Controller Bank4\&. 
.PP
Definition at line \fB513\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t PATT4"
PC Card Attribute memory space timing register 4, Address offset: 0xAC 
.PP
Definition at line \fB518\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PCR4"
PC Card control register 4, Address offset: 0xA0 
.PP
Definition at line \fB515\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PIO4"
PC Card I/O space timing register 4, Address offset: 0xB0 
.PP
Definition at line \fB519\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PMEM4"
PC Card Common memory space timing register 4, Address offset: 0xA8 
.PP
Definition at line \fB517\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t SR4"
PC Card FIFO status and interrupt register 4, Address offset: 0xA4 
.PP
Definition at line \fB516\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
