.TH "GPIO_Output_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Output_Type
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBPush_Pull\fP"
.br
.ti -1c
.RI "uint8_t \fBOpen_Drain\fP"
.br
.ti -1c
.RI "uint8_t \fBNone\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBGPIO_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t None"

.PP
Definition at line \fB27\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t Open_Drain"

.PP
Definition at line \fB26\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t Push_Pull"

.PP
Definition at line \fB25\fP of file \fBGPIO_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
