.TH "GPIO_Alternate_Function" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Alternate_Function
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBNone\fP"
.br
.ti -1c
.RI "uint8_t \fBAnalog\fP"
.br
.ti -1c
.RI "uint8_t \fBSYS\fP"
.br
.ti -1c
.RI "uint8_t \fBMCO1\fP"
.br
.ti -1c
.RI "uint8_t \fBMCO2\fP"
.br
.ti -1c
.RI "uint8_t \fBRTC_REFIN\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_1\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_2\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_3\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_4\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_5\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_8\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_9\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_10\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_11\fP"
.br
.ti -1c
.RI "uint8_t \fBI2C_1\fP"
.br
.ti -1c
.RI "uint8_t \fBI2C_2\fP"
.br
.ti -1c
.RI "uint8_t \fBI2C_3\fP"
.br
.ti -1c
.RI "uint8_t \fBSPI_1\fP"
.br
.ti -1c
.RI "uint8_t \fBSPI_2\fP"
.br
.ti -1c
.RI "uint8_t \fBI2S_2\fP"
.br
.ti -1c
.RI "uint8_t \fBI2S_2EXT\fP"
.br
.ti -1c
.RI "uint8_t \fBSPI_3\fP"
.br
.ti -1c
.RI "uint8_t \fBI2S_EXT\fP"
.br
.ti -1c
.RI "uint8_t \fBI2S_3\fP"
.br
.ti -1c
.RI "uint8_t \fBUSART_1\fP"
.br
.ti -1c
.RI "uint8_t \fBUSART_2\fP"
.br
.ti -1c
.RI "uint8_t \fBUSART_3\fP"
.br
.ti -1c
.RI "uint8_t \fBI2S_3EXT\fP"
.br
.ti -1c
.RI "uint8_t \fBUSART_4\fP"
.br
.ti -1c
.RI "uint8_t \fBUART_5\fP"
.br
.ti -1c
.RI "uint8_t \fBUSART_6\fP"
.br
.ti -1c
.RI "uint8_t \fBCAN_1\fP"
.br
.ti -1c
.RI "uint8_t \fBCAN_2\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_12\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_13\fP"
.br
.ti -1c
.RI "uint8_t \fBTIM_14\fP"
.br
.ti -1c
.RI "uint8_t \fBOTG_FS_1\fP"
.br
.ti -1c
.RI "uint8_t \fBOYG_HS_1\fP"
.br
.ti -1c
.RI "uint8_t \fBETH_1\fP"
.br
.ti -1c
.RI "uint8_t \fBFSMC_1\fP"
.br
.ti -1c
.RI "uint8_t \fBSDIO_1\fP"
.br
.ti -1c
.RI "uint8_t \fBOTG_FS_2\fP"
.br
.ti -1c
.RI "uint8_t \fBDCMI_1\fP"
.br
.ti -1c
.RI "uint8_t \fBEVENTOUT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB45\fP of file \fBGPIO_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t Analog"

.PP
Definition at line \fB47\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t CAN_1"

.PP
Definition at line \fB78\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t CAN_2"

.PP
Definition at line \fB79\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t DCMI_1"

.PP
Definition at line \fB89\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t ETH_1"

.PP
Definition at line \fB85\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t EVENTOUT"

.PP
Definition at line \fB90\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t FSMC_1"

.PP
Definition at line \fB86\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t I2C_1"

.PP
Definition at line \fB61\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t I2C_2"

.PP
Definition at line \fB62\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t I2C_3"

.PP
Definition at line \fB63\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t I2S_2"

.PP
Definition at line \fB66\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t I2S_2EXT"

.PP
Definition at line \fB67\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t I2S_3"

.PP
Definition at line \fB70\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t I2S_3EXT"

.PP
Definition at line \fB74\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t I2S_EXT"

.PP
Definition at line \fB69\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t MCO1"

.PP
Definition at line \fB49\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t MCO2"

.PP
Definition at line \fB50\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t None"

.PP
Definition at line \fB46\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t OTG_FS_1"

.PP
Definition at line \fB83\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t OTG_FS_2"

.PP
Definition at line \fB88\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t OYG_HS_1"

.PP
Definition at line \fB84\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t RTC_REFIN"

.PP
Definition at line \fB51\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t SDIO_1"

.PP
Definition at line \fB87\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t SPI_1"

.PP
Definition at line \fB64\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t SPI_2"

.PP
Definition at line \fB65\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t SPI_3"

.PP
Definition at line \fB68\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t SYS"

.PP
Definition at line \fB48\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_1"

.PP
Definition at line \fB52\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_10"

.PP
Definition at line \fB59\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_11"

.PP
Definition at line \fB60\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_12"

.PP
Definition at line \fB80\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_13"

.PP
Definition at line \fB81\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_14"

.PP
Definition at line \fB82\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_2"

.PP
Definition at line \fB53\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_3"

.PP
Definition at line \fB54\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_4"

.PP
Definition at line \fB55\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_5"

.PP
Definition at line \fB56\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_8"

.PP
Definition at line \fB57\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t TIM_9"

.PP
Definition at line \fB58\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t UART_5"

.PP
Definition at line \fB76\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t USART_1"

.PP
Definition at line \fB71\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t USART_2"

.PP
Definition at line \fB72\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t USART_3"

.PP
Definition at line \fB73\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t USART_4"

.PP
Definition at line \fB75\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t USART_6"

.PP
Definition at line \fB77\fP of file \fBGPIO_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
