.TH "GPIO_Pin" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Pin
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBAccess\fP"
.br
.ti -1c
.RI "uint16_t \fBPin_numer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBGPIO\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "bool Access"

.PP
Definition at line \fB17\fP of file \fBGPIO\&.h\fP\&.
.SS "uint16_t Pin_numer"

.PP
Definition at line \fB18\fP of file \fBGPIO\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
