.TH "GPIO_Pull" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Pull
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBNo_Pull_Up_Down\fP"
.br
.ti -1c
.RI "uint8_t \fBPull_Up\fP"
.br
.ti -1c
.RI "uint8_t \fBPull_Down\fP"
.br
.ti -1c
.RI "uint8_t \fBNone\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB38\fP of file \fBGPIO_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t No_Pull_Up_Down"

.PP
Definition at line \fB39\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t None"

.PP
Definition at line \fB42\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t Pull_Down"

.PP
Definition at line \fB41\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t Pull_Up"

.PP
Definition at line \fB40\fP of file \fBGPIO_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
