.TH "GPIO_Interrupt_Edge" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Interrupt_Edge
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBRISING_EDGE\fP"
.br
.ti -1c
.RI "uint8_t \fBFALLING_EDGE\fP"
.br
.ti -1c
.RI "uint8_t \fBRISING_FALLING_EDGE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB94\fP of file \fBGPIO_Defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t FALLING_EDGE"

.PP
Definition at line \fB96\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t RISING_EDGE"

.PP
Definition at line \fB95\fP of file \fBGPIO_Defs\&.h\fP\&.
.SS "uint8_t RISING_FALLING_EDGE"

.PP
Definition at line \fB97\fP of file \fBGPIO_Defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
