.TH "GPIO_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_TypeDef \- General Purpose I/O\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMODER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTYPER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOSPEEDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPUPDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBODR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBSRR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBLCKR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAFR\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
General Purpose I/O\&. 
.PP
Definition at line \fB526\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t AFR[2]"
GPIO alternate function registers, Address offset: 0x20-0x24 
.PP
Definition at line \fB536\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BSRR"
GPIO port bit set/reset register, Address offset: 0x18 
.br
 
.PP
Definition at line \fB534\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t IDR"
GPIO port input data register, Address offset: 0x10 
.br
 
.PP
Definition at line \fB532\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t LCKR"
GPIO port configuration lock register, Address offset: 0x1C 
.br
 
.PP
Definition at line \fB535\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MODER"
GPIO port mode register, Address offset: 0x00 
.br
 
.PP
Definition at line \fB528\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t ODR"
GPIO port output data register, Address offset: 0x14 
.br
 
.PP
Definition at line \fB533\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t OSPEEDR"
GPIO port output speed register, Address offset: 0x08 
.br
 
.PP
Definition at line \fB530\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t OTYPER"
GPIO port output type register, Address offset: 0x04 
.br
 
.PP
Definition at line \fB529\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PUPDR"
GPIO port pull-up/pull-down register, Address offset: 0x0C 
.br
 
.PP
Definition at line \fB531\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
