.TH "Hardware_Constant_Definition" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hardware_Constant_Definition \- Hardware_Constant_Definition
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLSI_STARTUP_TIME\fP   40U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define LSI_STARTUP_TIME   40U"
LSI Maximum startup time in us 
.PP
Definition at line \fB1154\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
