.TH "IPSR_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPSR_Type \- Union type to access the Interrupt Program Status Register (IPSR)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_armv81mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union type to access the Interrupt Program Status Register (IPSR)\&. 
.PP
Definition at line \fB367\fP of file \fBcore_armv81mml\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
