.TH "ITM_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ITM_Type \- Structure type to access the Instrumentation Trace Macrocell Register (ITM)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_armv81mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [864U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBTER\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [15U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBTPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [15U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBTCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [32U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [43U]"
.br
.ti -1c
.RI "__OM uint32_t \fBLAR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBLSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [1U]"
.br
.ti -1c
.RI "__IM uint32_t \fBDEVARCH\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED6\fP [3U]"
.br
.ti -1c
.RI "__IM uint32_t \fBDEVTYPE\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBPID4\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBPID5\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBPID6\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBPID7\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBPID0\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBPID1\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBPID2\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBPID3\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBCID0\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBCID1\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBCID2\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBCID3\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __OM uint8_t \fBu8\fP"
.br
.ti -1c
.RI "   __OM uint16_t \fBu16\fP"
.br
.ti -1c
.RI "   __OM uint32_t \fBu32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Instrumentation Trace Macrocell Register (ITM)\&. 
.PP
Definition at line \fB1078\fP of file \fBcore_armv81mml\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
