.TH "IWDG_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWDG_TypeDef \- Independent WATCHDOG\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBKR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Independent WATCHDOG\&. 
.PP
Definition at line \fB573\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t KR"
IWDG Key register, Address offset: 0x00 
.PP
Definition at line \fB575\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PR"
IWDG Prescaler register, Address offset: 0x04 
.PP
Definition at line \fB576\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t RLR"
IWDG Reload register, Address offset: 0x08 
.PP
Definition at line \fB577\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t SR"
IWDG Status register, Address offset: 0x0C 
.PP
Definition at line \fB578\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
