.TH "Src/main.c" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/main.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include 'main\&.h'\fP
.br
\fR#include 'ADC\&.h'\fP
.br
\fR#include 'GPIO\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBJoystick_Buffer_Size\fP   4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBADC_Config\fP \fBJoystick\fP"
.br
.ti -1c
.RI "uint16_t \fBJoystick_Data_Buffer\fP [Joystick_Buffer_Size]"
.br
.ti -1c
.RI "bool \fBJoystick_1_UP\fP = 0"
.br
.ti -1c
.RI "bool \fBJoystick_1_Down\fP = 0"
.br
.ti -1c
.RI "bool \fBJoystick_1_Left\fP = 0"
.br
.ti -1c
.RI "bool \fBJoystick_1_Right\fP = 0"
.br
.ti -1c
.RI "bool \fBJoystick_2_UP\fP = 0"
.br
.ti -1c
.RI "bool \fBJoystick_2_Down\fP = 0"
.br
.ti -1c
.RI "bool \fBJoystick_2_Left\fP = 0"
.br
.ti -1c
.RI "bool \fBJoystick_2_Right\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Kunal Salvi (kunalsalvius@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2024-08-20
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2024 
.RE
.PP

.PP
Definition in file \fBmain\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define Joystick_Buffer_Size   4"

.PP
Definition at line \fB19\fP of file \fBmain\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (void )"

.PP
Definition at line \fB35\fP of file \fBmain\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBADC_Config\fP Joystick"

.PP
Definition at line \fB17\fP of file \fBmain\&.c\fP\&.
.SS "bool Joystick_1_Down = 0"

.PP
Definition at line \fB24\fP of file \fBmain\&.c\fP\&.
.SS "bool Joystick_1_Left = 0"

.PP
Definition at line \fB25\fP of file \fBmain\&.c\fP\&.
.SS "bool Joystick_1_Right = 0"

.PP
Definition at line \fB26\fP of file \fBmain\&.c\fP\&.
.SS "bool Joystick_1_UP = 0"

.PP
Definition at line \fB23\fP of file \fBmain\&.c\fP\&.
.SS "bool Joystick_2_Down = 0"

.PP
Definition at line \fB29\fP of file \fBmain\&.c\fP\&.
.SS "bool Joystick_2_Left = 0"

.PP
Definition at line \fB30\fP of file \fBmain\&.c\fP\&.
.SS "bool Joystick_2_Right = 0"

.PP
Definition at line \fB31\fP of file \fBmain\&.c\fP\&.
.SS "bool Joystick_2_UP = 0"

.PP
Definition at line \fB28\fP of file \fBmain\&.c\fP\&.
.SS "uint16_t Joystick_Data_Buffer[Joystick_Buffer_Size]"

.PP
Definition at line \fB21\fP of file \fBmain\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
