.TH "NVIC_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NVIC_Type \- Structure type to access the Nested Vectored Interrupt Controller (NVIC)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_armv81mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__IOM uint32_t \fBISER\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBICER\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRSERVED1\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBISPR\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBICPR\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBIABR\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [16U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBITNS\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [16U]"
.br
.ti -1c
.RI "__IOM uint8_t \fBIPR\fP [496U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED6\fP [580U]"
.br
.ti -1c
.RI "__OM uint32_t \fBSTIR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBIPR\fP [124U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [31U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBIP\fP [8U]"
.br
.ti -1c
.RI "__IOM uint8_t \fBIP\fP [240U]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Nested Vectored Interrupt Controller (NVIC)\&. 
.PP
Definition at line \fB475\fP of file \fBcore_armv81mml\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
