.TH "PrcCfgInf_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrcCfgInf_Type \- Structure type to access the Processor Configuration Information Registerss (PRCCFGINF)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_cm55\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__OM uint32_t \fBCFGINFOSEL\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBCFGINFORD\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Processor Configuration Information Registerss (PRCCFGINF)\&. 
.PP
Definition at line \fB1755\fP of file \fBcore_cm55\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
