.TH "PWR_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_TypeDef \- Power Control\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Power Control\&. 
.PP
Definition at line \fB586\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t CR"
PWR power control register, Address offset: 0x00 
.PP
Definition at line \fB588\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CSR"
PWR power control/status register, Address offset: 0x04 
.PP
Definition at line \fB589\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
