.TH "PwrModCtl_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PwrModCtl_Type \- Structure type to access the Power Mode Control Registers (PWRMODCTL)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_cm55\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__IOM uint32_t \fBCPDLPSTATE\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDPDLPSTATE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Power Mode Control Registers (PWRMODCTL)\&. 
.PP
Definition at line \fB1537\fP of file \fBcore_cm55\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
