.TH "RTC_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_TypeDef \- Real-Time Clock\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBISR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPRER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBWUTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCALIBR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBALRMAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBALRMBR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBWPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSHIFTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTSTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTSDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTSSSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCALR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTAFCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBALRMASSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBALRMBSSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED7\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP0R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP1R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP2R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP3R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP4R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP5R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP6R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP7R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP8R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP9R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP10R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP11R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP12R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP13R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP14R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP15R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP16R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP17R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP18R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBKP19R\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Real-Time Clock\&. 
.PP
Definition at line \fB634\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t ALRMAR"
RTC alarm A register, Address offset: 0x1C 
.PP
Definition at line \fB643\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t ALRMASSR"
RTC alarm A sub second register, Address offset: 0x44 
.PP
Definition at line \fB653\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t ALRMBR"
RTC alarm B register, Address offset: 0x20 
.PP
Definition at line \fB644\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t ALRMBSSR"
RTC alarm B sub second register, Address offset: 0x48 
.PP
Definition at line \fB654\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP0R"
RTC backup register 1, Address offset: 0x50 
.PP
Definition at line \fB656\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP10R"
RTC backup register 10, Address offset: 0x78 
.PP
Definition at line \fB666\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP11R"
RTC backup register 11, Address offset: 0x7C 
.PP
Definition at line \fB667\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP12R"
RTC backup register 12, Address offset: 0x80 
.PP
Definition at line \fB668\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP13R"
RTC backup register 13, Address offset: 0x84 
.PP
Definition at line \fB669\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP14R"
RTC backup register 14, Address offset: 0x88 
.PP
Definition at line \fB670\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP15R"
RTC backup register 15, Address offset: 0x8C 
.PP
Definition at line \fB671\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP16R"
RTC backup register 16, Address offset: 0x90 
.PP
Definition at line \fB672\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP17R"
RTC backup register 17, Address offset: 0x94 
.PP
Definition at line \fB673\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP18R"
RTC backup register 18, Address offset: 0x98 
.PP
Definition at line \fB674\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP19R"
RTC backup register 19, Address offset: 0x9C 
.PP
Definition at line \fB675\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP1R"
RTC backup register 1, Address offset: 0x54 
.PP
Definition at line \fB657\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP2R"
RTC backup register 2, Address offset: 0x58 
.PP
Definition at line \fB658\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP3R"
RTC backup register 3, Address offset: 0x5C 
.PP
Definition at line \fB659\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP4R"
RTC backup register 4, Address offset: 0x60 
.PP
Definition at line \fB660\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP5R"
RTC backup register 5, Address offset: 0x64 
.PP
Definition at line \fB661\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP6R"
RTC backup register 6, Address offset: 0x68 
.PP
Definition at line \fB662\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP7R"
RTC backup register 7, Address offset: 0x6C 
.PP
Definition at line \fB663\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP8R"
RTC backup register 8, Address offset: 0x70 
.PP
Definition at line \fB664\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t BKP9R"
RTC backup register 9, Address offset: 0x74 
.PP
Definition at line \fB665\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CALIBR"
RTC calibration register, Address offset: 0x18 
.PP
Definition at line \fB642\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CALR"
RTC calibration register, Address offset: 0x3C 
.PP
Definition at line \fB651\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CR"
RTC control register, Address offset: 0x08 
.PP
Definition at line \fB638\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DR"
RTC date register, Address offset: 0x04 
.PP
Definition at line \fB637\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t ISR"
RTC initialization and status register, Address offset: 0x0C 
.PP
Definition at line \fB639\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PRER"
RTC prescaler register, Address offset: 0x10 
.PP
Definition at line \fB640\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED7"
Reserved, 0x4C 
.br
 
.PP
Definition at line \fB655\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t SHIFTR"
RTC shift control register, Address offset: 0x2C 
.PP
Definition at line \fB647\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t SSR"
RTC sub second register, Address offset: 0x28 
.PP
Definition at line \fB646\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t TAFCR"
RTC tamper and alternate function configuration register, Address offset: 0x40 
.PP
Definition at line \fB652\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t TR"
RTC time register, Address offset: 0x00 
.PP
Definition at line \fB636\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t TSDR"
RTC time stamp date register, Address offset: 0x34 
.PP
Definition at line \fB649\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t TSSSR"
RTC time-stamp sub second register, Address offset: 0x38 
.PP
Definition at line \fB650\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t TSTR"
RTC time stamp time register, Address offset: 0x30 
.PP
Definition at line \fB648\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t WPR"
RTC write protection register, Address offset: 0x24 
.PP
Definition at line \fB645\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t WUTR"
RTC wakeup timer register, Address offset: 0x14 
.PP
Definition at line \fB641\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
