.TH "SCB_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCB_Type \- Structure type to access the System Control Block (SCB)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_armv81mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__IM uint32_t \fBCPUID\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBICSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBVTOR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBAIRCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBSCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCCR\fP"
.br
.ti -1c
.RI "__IOM uint8_t \fBSHPR\fP [12U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBSHCSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCFSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBHFSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDFSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBMMFAR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBBFAR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBAFSR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBID_PFR\fP [2U]"
.br
.ti -1c
.RI "__IM uint32_t \fBID_DFR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBID_AFR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBID_MMFR\fP [4U]"
.br
.ti -1c
.RI "__IM uint32_t \fBID_ISAR\fP [6U]"
.br
.ti -1c
.RI "__IM uint32_t \fBCLIDR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBCTR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBCCSIDR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCSSELR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCPACR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBNSACR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED7\fP [21U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBSFSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBSFAR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [69U]"
.br
.ti -1c
.RI "__OM uint32_t \fBSTIR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBRFSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [14U]"
.br
.ti -1c
.RI "__IM uint32_t \fBMVFR0\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBMVFR1\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBMVFR2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [1U]"
.br
.ti -1c
.RI "__OM uint32_t \fBICIALLU\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED6\fP [1U]"
.br
.ti -1c
.RI "__OM uint32_t \fBICIMVAU\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBDCIMVAC\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBDCISW\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBDCCMVAU\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBDCCMVAC\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBDCCSW\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBDCCIMVAC\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBDCCISW\fP"
.br
.ti -1c
.RI "__OM uint32_t \fBBPIALL\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBSHPR\fP [2U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBSHP\fP [2U]"
.br
.ti -1c
.RI "__IOM uint8_t \fBSHP\fP [12U]"
.br
.ti -1c
.RI "__IM uint32_t \fBPFR\fP [2U]"
.br
.ti -1c
.RI "__IM uint32_t \fBDFR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBADR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBMMFR\fP [4U]"
.br
.ti -1c
.RI "__IM uint32_t \fBISAR\fP [5U]"
.br
.ti -1c
.RI "__IM uint32_t \fBID_MFR\fP [4U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBITCMCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBDTCMCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBAHBPCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCACR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBAHBSCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED8\fP [1U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBABFSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBSFCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED_ADD1\fP [21U]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the System Control Block (SCB)\&. 
.PP
Definition at line \fB511\fP of file \fBcore_armv81mml\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
