.TH "SDIO_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDIO_TypeDef \- SD host Interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPOWER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLKCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBARG\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCMD\fP"
.br
.ti -1c
.RI "\fB__IO\fP const uint32_t \fBRESPCMD\fP"
.br
.ti -1c
.RI "\fB__IO\fP const uint32_t \fBRESP1\fP"
.br
.ti -1c
.RI "\fB__IO\fP const uint32_t \fBRESP2\fP"
.br
.ti -1c
.RI "\fB__IO\fP const uint32_t \fBRESP3\fP"
.br
.ti -1c
.RI "\fB__IO\fP const uint32_t \fBRESP4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTIMER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDLEN\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDCTRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP const uint32_t \fBDCOUNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP const uint32_t \fBSTA\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBICR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMASK\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [2]"
.br
.ti -1c
.RI "\fB__IO\fP const uint32_t \fBFIFOCNT\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [13]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFIFO\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SD host Interface\&. 
.PP
Definition at line \fB682\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t ARG"
SDIO argument register, Address offset: 0x08 
.PP
Definition at line \fB686\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CLKCR"
SDI clock control register, Address offset: 0x04 
.PP
Definition at line \fB685\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CMD"
SDIO command register, Address offset: 0x0C 
.PP
Definition at line \fB687\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP const uint32_t DCOUNT"
SDIO data counter register, Address offset: 0x30 
.PP
Definition at line \fB696\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DCTRL"
SDIO data control register, Address offset: 0x2C 
.PP
Definition at line \fB695\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DLEN"
SDIO data length register, Address offset: 0x28 
.PP
Definition at line \fB694\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DTIMER"
SDIO data timer register, Address offset: 0x24 
.PP
Definition at line \fB693\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t FIFO"
SDIO data FIFO register, Address offset: 0x80 
.PP
Definition at line \fB703\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP const uint32_t FIFOCNT"
SDIO FIFO counter register, Address offset: 0x48 
.PP
Definition at line \fB701\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t ICR"
SDIO interrupt clear register, Address offset: 0x38 
.PP
Definition at line \fB698\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MASK"
SDIO mask register, Address offset: 0x3C 
.PP
Definition at line \fB699\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t POWER"
SDIO power control register, Address offset: 0x00 
.PP
Definition at line \fB684\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED0[2]"
Reserved, 0x40-0x44 
.br
 
.PP
Definition at line \fB700\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED1[13]"
Reserved, 0x4C-0x7C 
.br
 
.PP
Definition at line \fB702\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP const uint32_t RESP1"
SDIO response 1 register, Address offset: 0x14 
.PP
Definition at line \fB689\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP const uint32_t RESP2"
SDIO response 2 register, Address offset: 0x18 
.PP
Definition at line \fB690\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP const uint32_t RESP3"
SDIO response 3 register, Address offset: 0x1C 
.PP
Definition at line \fB691\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP const uint32_t RESP4"
SDIO response 4 register, Address offset: 0x20 
.PP
Definition at line \fB692\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP const uint32_t RESPCMD"
SDIO command response register, Address offset: 0x10 
.PP
Definition at line \fB688\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP const uint32_t STA"
SDIO status register, Address offset: 0x34 
.PP
Definition at line \fB697\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
