.TH "SPI_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_TypeDef \- Serial Peripheral Interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCRCPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRXCRCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTXCRCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBI2SCFGR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBI2SPR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Serial Peripheral Interface\&. 
.PP
Definition at line \fB710\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t CR1"
SPI control register 1 (not used in I2S mode), Address offset: 0x00 
.PP
Definition at line \fB712\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CR2"
SPI control register 2, Address offset: 0x04 
.PP
Definition at line \fB713\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t CRCPR"
SPI CRC polynomial register (not used in I2S mode), Address offset: 0x10 
.PP
Definition at line \fB716\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t DR"
SPI data register, Address offset: 0x0C 
.PP
Definition at line \fB715\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t I2SCFGR"
SPI_I2S configuration register, Address offset: 0x1C 
.PP
Definition at line \fB719\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t I2SPR"
SPI_I2S prescaler register, Address offset: 0x20 
.PP
Definition at line \fB720\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t RXCRCR"
SPI RX CRC register (not used in I2S mode), Address offset: 0x14 
.PP
Definition at line \fB717\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t SR"
SPI status register, Address offset: 0x08 
.PP
Definition at line \fB714\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t TXCRCR"
SPI TX CRC register (not used in I2S mode), Address offset: 0x18 
.PP
Definition at line \fB718\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
