.TH "STL_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STL_Type \- Structure type to access the Software Test Library Observation Registerss (STL)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_cm55\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__IM uint32_t \fBSTLNVICPENDOR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBSTLNVICACTVOR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [2U]"
.br
.ti -1c
.RI "__OM uint32_t \fBSTLIDMPUSR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBSTLIMPUOR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBSTLD0MPUOR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBSTLD1MPUOR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Software Test Library Observation Registerss (STL)\&. 
.PP
Definition at line \fB1778\fP of file \fBcore_cm55\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
