.TH "STM32F4xx_System_Exported_types" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F4xx_System_Exported_types \- STM32F4xx_System_Exported_types
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP"
.br
.ti -1c
.RI "const uint8_t \fBAHBPrescTable\fP [16]"
.br
.ti -1c
.RI "const uint8_t \fBAPBPrescTable\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Variable Documentation"
.PP 
.SS "const uint8_t AHBPrescTable[16]\fR [extern]\fP"
AHB prescalers table values 
.PP
Definition at line \fB138\fP of file \fBsystem_stm32f4xx\&.c\fP\&.
.SS "const uint8_t APBPrescTable[8]\fR [extern]\fP"
APB prescalers table values 
.PP
Definition at line \fB139\fP of file \fBsystem_stm32f4xx\&.c\fP\&.
.SS "uint32_t SystemCoreClock\fR [extern]\fP"
System Clock Frequency (Core Clock) 
.PP
Definition at line \fB137\fP of file \fBsystem_stm32f4xx\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
