.TH "SYSCFG_TypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYSCFG_TypeDef \- System configuration controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMEMRMP\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPMC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEXTICR\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED\fP [2]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCMPCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
System configuration controller\&. 
.PP
Definition at line \fB543\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t CMPCR"
SYSCFG Compensation cell control register, Address offset: 0x20 
.br
 
.PP
Definition at line \fB549\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t EXTICR[4]"
SYSCFG external interrupt configuration registers, Address offset: 0x08-0x14 
.PP
Definition at line \fB547\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t MEMRMP"
SYSCFG memory remap register, Address offset: 0x00 
.br
 
.PP
Definition at line \fB545\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t PMC"
SYSCFG peripheral mode configuration register, Address offset: 0x04 
.br
 
.PP
Definition at line \fB546\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t RESERVED[2]"
Reserved, 0x18-0x1C 
.br
 
.PP
Definition at line \fB548\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
