.TH "TPI_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPI_Type \- Structure type to access the Trace Port Interface Register (TPI)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_armv81mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__IM uint32_t \fBSSPSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCSPSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [2U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBACPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [55U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBSPPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [131U]"
.br
.ti -1c
.RI "__IM uint32_t \fBFFSR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBFFCR\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBPSCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [809U]"
.br
.ti -1c
.RI "__OM uint32_t \fBLAR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBLSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [4U]"
.br
.ti -1c
.RI "__IM uint32_t \fBTYPE\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBDEVTYPE\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBTRIGGER\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBITFTTD0\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBITATBCTR2\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBITATBCTR0\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBITFTTD1\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBITCTRL\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [39U]"
.br
.ti -1c
.RI "__IOM uint32_t \fBCLAIMSET\fP"
.br
.ti -1c
.RI "__IOM uint32_t \fBCLAIMCLR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED7\fP [8U]"
.br
.ti -1c
.RI "__IM uint32_t \fBDEVID\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBFSCR\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBFIFO0\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBITATBCTR2\fP"
.br
.ti -1c
.RI "__IM uint32_t \fBFIFO1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Trace Port Interface Register (TPI)\&. 
.PP
Definition at line \fB1365\fP of file \fBcore_armv81mml\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
