.TH "USART_Config" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_Config
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBUSART_TypeDef\fP * \fBPort\fP"
.br
.ti -1c
.RI "uint32_t \fBbaudrate\fP"
.br
.ti -1c
.RI "uint8_t \fBmode\fP"
.br
.ti -1c
.RI "uint8_t \fBTX_Pin\fP"
.br
.ti -1c
.RI "uint8_t \fBRX_Pin\fP"
.br
.ti -1c
.RI "uint8_t \fBCLK_Pin\fP"
.br
.ti -1c
.RI "uint8_t \fBCTS_Pin\fP"
.br
.ti -1c
.RI "uint8_t \fBRTS_Pin\fP"
.br
.ti -1c
.RI "uint8_t \fBinterrupt\fP"
.br
.ti -1c
.RI "uint8_t \fBhardware_flow\fP"
.br
.ti -1c
.RI "uint8_t \fBstop_bits\fP"
.br
.ti -1c
.RI "uint8_t \fBdma_enable\fP"
.br
.ti -1c
.RI "uint8_t \fBparity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBUSART\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t baudrate"

.PP
Definition at line \fB22\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t CLK_Pin"

.PP
Definition at line \fB26\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t CTS_Pin"

.PP
Definition at line \fB27\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t dma_enable"

.PP
Definition at line \fB32\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t hardware_flow"

.PP
Definition at line \fB30\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t interrupt"

.PP
Definition at line \fB29\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t mode"

.PP
Definition at line \fB23\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t parity"

.PP
Definition at line \fB33\fP of file \fBUSART\&.h\fP\&.
.SS "\fBUSART_TypeDef\fP* Port"

.PP
Definition at line \fB21\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t RTS_Pin"

.PP
Definition at line \fB28\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t RX_Pin"

.PP
Definition at line \fB25\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t stop_bits"

.PP
Definition at line \fB31\fP of file \fBUSART\&.h\fP\&.
.SS "uint8_t TX_Pin"

.PP
Definition at line \fB24\fP of file \fBUSART\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
