.TH "USB_OTG_HostChannelTypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USB_OTG_HostChannelTypeDef \- USB_OTG_Host_Channel_Specific_Registers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHCCHAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHCSPLT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHCINT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHCINTMSK\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHCTSIZ\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHCDMA\fP"
.br
.ti -1c
.RI "uint32_t \fBReserved\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
USB_OTG_Host_Channel_Specific_Registers\&. 
.PP
Definition at line \fB888\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t HCCHAR"
Host Channel Characteristics Register 500h 
.PP
Definition at line \fB890\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HCDMA"
Host Channel DMA Address Register 514h 
.PP
Definition at line \fB895\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HCINT"
Host Channel Interrupt Register 508h 
.PP
Definition at line \fB892\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HCINTMSK"
Host Channel Interrupt Mask Register 50Ch 
.PP
Definition at line \fB893\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HCSPLT"
Host Channel Split Control Register 504h 
.PP
Definition at line \fB891\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HCTSIZ"
Host Channel Transfer Size Register 510h 
.PP
Definition at line \fB894\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t Reserved[2]"
Reserved 
.br
 
.PP
Definition at line \fB896\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
