.TH "USB_OTG_HostTypeDef" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USB_OTG_HostTypeDef \- USB_OTG_Host_Mode_Register_Structures\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <stm32f407xx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHCFG\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHFIR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHFNUM\fP"
.br
.ti -1c
.RI "uint32_t \fBReserved40C\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHPTXSTS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHAINT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHAINTMSK\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
USB_OTG_Host_Mode_Register_Structures\&. 
.PP
Definition at line \fB874\fP of file \fBstm32f407xx\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t HAINT"
Host All Channels Interrupt Register 414h 
.PP
Definition at line \fB881\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HAINTMSK"
Host All Channels Interrupt Mask 418h 
.PP
Definition at line \fB882\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HCFG"
Host Configuration Register 400h 
.PP
Definition at line \fB876\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HFIR"
Host Frame Interval Register 404h 
.PP
Definition at line \fB877\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HFNUM"
Host Frame Nbr/Frame Remaining 408h 
.PP
Definition at line \fB878\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "\fB__IO\fP uint32_t HPTXSTS"
Host Periodic Tx FIFO/ Queue Status 410h 
.PP
Definition at line \fB880\fP of file \fBstm32f407xx\&.h\fP\&.
.SS "uint32_t Reserved40C"
Reserved 40Ch 
.PP
Definition at line \fB879\fP of file \fBstm32f407xx\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
