.TH "xPSR_Type" 3 "Version JSTDRVF4" "Joystick Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xPSR_Type \- Union type to access the Special-Purpose Program Status Registers (xPSR)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core_armv81mml\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:4"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBIT\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:4"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBIT\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBICI_IT_1\fP:6"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:8"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBICI_IT_2\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:4"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBIT\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:4"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBIT\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBICI_IT_1\fP:6"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:4"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBICI_IT_2\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:4"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBIT\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBICI_IT_1\fP:6"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:4"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBICI_IT_2\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBB\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved2\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBIT\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:15"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:3"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBICI_IT_1\fP:6"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:8"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBICI_IT_2\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:7"
.br
.ti -1c
.RI "   uint32_t \fBGE\fP:4"
.br
.ti -1c
.RI "   uint32_t \fB_reserved1\fP:4"
.br
.ti -1c
.RI "   uint32_t \fBT\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBIT\fP:2"
.br
.ti -1c
.RI "   uint32_t \fBQ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBC\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBZ\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBN\fP:1"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union type to access the Special-Purpose Program Status Registers (xPSR)\&. 
.PP
Definition at line \fB385\fP of file \fBcore_armv81mml\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Joystick Driver from the source code\&.
